/** Actual host-module tests with isolated JS dependency doubles. NOT BDS,
 * simulated Minecraft players, or evidence of native client rendering.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {waxFaceParticles,growthParticles,glassBreakParticles,potionSplashParticles,TAVERN_SPLASH_COLOR} from '../../runtime/BP/scripts/core/interaction-particles.js';
import {normalizeFoundation} from '../../runtime/BP/scripts/core/extension-foundation.js';
import {installContent,externalItemParticle} from '../../runtime/BP/scripts/core/extension-content.js';
import {ITEM_PARTICLES} from '../../runtime/BP/scripts/data/item-particles.js';
import {ITEM_PARTICLE_SPRITES} from '../../runtime/BP/scripts/data/item-particle-sprites.js';
const ROOT=fileURLToPath(new URL('../../',import.meta.url)),SCRIPTS=path.join(ROOT,'runtime/BP/scripts');
const NS='kaleidoscope_tavern';
const no=()=>{},plain=x=>JSON.parse(JSON.stringify(x));
function rng(seed=34){return ()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/2**32);}
class Permutation{
 constructor(id,states={}){this.type={id};this.states={...states};}
 getState(k){return this.states[k];}
 withState(k,v){return new Permutation(this.type.id,{...this.states,[k]:v});}
 canContainLiquid(){return true;}
 static resolve(id,states={}){return new Permutation(id,states);}
}
async function fixture(overrides={}){
 const particles=[],sounds=[],records=new Map(),blocks=new Map(),entities=[],jobs=[];let throwsOnParticle=false,throwsOnExchange=false,throwsOnSpawn=false,exchanges=0;
 const server={system:{currentTick:0,run:no,runInterval:no,runTimeout:no,clearRun:no},world:{gameRules:{mobGriefing:true,doTileDrops:true},getDynamicProperty:k=>records.get(k),setDynamicProperty:(k,v)=>v===undefined?records.delete(k):records.set(k,v),getAllPlayers:()=>[]},BlockPermutation:Permutation,GameMode:{Creative:'Creative',Survival:'Survival',Spectator:'Spectator',Adventure:'Adventure'},EntityDamageCause:{magic:'magic'},MolangVariableMap:class{constructor(){this.values={};}setFloat(k,v){assert.ok(Number.isFinite(v),k);this.values[k]=v;}},ItemStack:class{constructor(id,count=1){this.typeId=id;this.amount=count;this.maxAmount=64;this.lore=[];}clone(){const c=Object.assign(new this.constructor(this.typeId,this.amount),this);c.lore=[...this.lore];return c;}isStackableWith(other){return this.typeId===other?.typeId;}getLore(){return [...this.lore];}getRawLore(){return [...this.lore];}setLore(l){this.lore=[...l];return this;}},ItemTypes:{get:id=>({id})}};
 const dimension={id:'minecraft:overworld',playSound(...a){sounds.push(a);},spawnParticle(...a){if(throwsOnParticle)throw Error('injected particle error');particles.push(a);},getBlock(p){return blocks.get([p.x,p.y,p.z].join(','));},getEntities:()=>[],spawnEntity(typeId,location){if(throwsOnSpawn)throw Error('injected spawn error');const data=new Map(),e={id:'projectile-'+entities.length,typeId,dimension,location:{...location},isValid:true,getDynamicProperty:k=>data.get(k),setDynamicProperty:(k,v)=>data.set(k,v),setProperty:no,remove(){this.isValid=false;},getAABB(){return {center:{...this.location},extent:{x:.125,y:.125,z:.125}};},getComponent(){return this.projectile;},projectile:{shoot(v){this.velocity={...v};}}};entities.push(e);return e;}};
 function block(id,location={x:0,y:0,z:0},states={}){const b={dimension,location:{...location},permutation:new Permutation(id,states),get typeId(){return this.permutation.type.id;},get isAir(){return this.typeId==='minecraft:air';},isWaterlogged:false,setWaterlogged:no,setPermutation(v){this.permutation=v;},setType(v){this.permutation=new Permutation(v);}};blocks.set(Object.values(location).join(','),b);return b;}
 const tx={makeStack:(id,n)=>new server.ItemStack(id,n),hand:p=>p.item,handSnapshot:p=>({id:p.item?.typeId}),sameHand:no,canWrite:no,canInteract:no,isBreakRecovery:()=>false,pickupOutputs:o=>o,commitPickupInventory:no,pickupFeedback:no,inventory:p=>p.inventory,commitStoredStateTransaction:no,withBreakInventory:no,withToolWear:no,handSnapshot:p=>({id:p.item?.typeId}),blockAt:(d,p)=>d.getBlock(p),plus:(a,b)=>({x:a.x+b.x,y:a.y+b.y,z:a.z+b.z}),safe:(_,fn)=>fn(),exchangeBlocks:(p,take,give,edits)=>{if(throwsOnExchange)throw Error('injected exchange');exchanges++;for(const e of edits)e.block.setPermutation(e.permutation);},exchangeBlocksToWorld:no,applyBlocks:no,air:()=>Permutation.resolve('minecraft:air'),placementTake:()=>1,playerInteractionReach:()=>6,requireBlockReach:no,tell:no};
 const stubs={'bedrock/transactions.js':tx,'bedrock/custom-effects.js':{applyCustomEffect:()=>true},'bedrock/potions.js':{restorePotion:no},'bedrock/vanilla-bottle-displays.js':{bottleDisplayKey:()=>'',potionDisplayRemoval:no},'bedrock/protected-break-router.js':{registerProtectedBreakRoute:no,playMaterialInteraction:no},'bedrock/java-placement-router.js':{registerJavaBlockUseHandler:no,registerJavaItemUseOnRoute:no,nativeEmptyHandBlockUse:no,nativeBlockUse:no,settleJavaBlockUse:no}};
 Object.assign(stubs,overrides);
 server.ScriptEventSource={Server:'Server'};
 const context=vm.createContext({console:{warn:no,log:no},Math:Object.assign(Object.create(Math),{random:rng()}),structuredClone,TextEncoder,TextDecoder});const modules=new Map();
 function load(id){if(modules.has(id))return modules.get(id);const values=id==='@minecraft/server'?server:stubs[path.relative(SCRIPTS,id).replaceAll('\\','/')];const m=values?new vm.SyntheticModule(Object.keys(values),function(){for(const[k,v]of Object.entries(values))this.setExport(k,v);},{context,identifier:id}):new vm.SourceTextModule(fs.readFileSync(id,'utf8'),{context,identifier:id});modules.set(id,m);return m;}
 async function get(relative){const m=load(path.join(SCRIPTS,relative));if(m.status==='unlinked')await m.link((id,from)=>load(id==='@minecraft/server'?id:path.resolve(path.dirname(from.identifier),id)));if(m.status==='linked')await m.evaluate();return m.namespace;}
 return {get,dimension,block,particles,sounds,records,entities,server,actor:{id:'unit-actor',_item:undefined,get item(){return this._item;},set item(v){this._item=v?Object.assign(new server.ItemStack(v.typeId),v):undefined;},location:{x:0,y:0,z:0},dimension,getGameMode:()=> 'Survival'},get exchanges(){return exchanges;},set failParticles(v){throwsOnParticle=v;},set failExchange(v){throwsOnExchange=v;},set failSpawn(v){throwsOnSpawn=v;}};
}

test('wax uses all six faces, 3..5 particles per face with zero face-normal velocity',()=>{
 for(let seed=0;seed<20;seed++){const rows=waxFaceParticles({x:3,y:4,z:5},rng(seed));assert.ok(rows.length>=18&&rows.length<=30);const faces=new Map();for(const r of rows){faces.set(r.face,(faces.get(r.face)||0)+1);const axis=r.face[0],sign=Number(r.face.slice(1));assert.equal(r.position[axis],{x:3,y:4,z:5}[axis]+.5+sign*.55);assert.equal(r.velocity[axis],0);}assert.equal(faces.size,6);assert.ok([...faces.values()].every(n=>n>=3&&n<=5));}
});
test('invalid geometry/RNG rejected instead of emitting NaN',()=>{assert.throws(()=>waxFaceParticles({x:0,y:0,z:0},()=>1));assert.throws(()=>glassBreakParticles({x:NaN,y:0,z:0}));assert.throws(()=>growthParticles({x:0,y:0,z:0},-1));});
test('growth samples contain unconditional center plus15 candidates',()=>{const rows=growthParticles({x:2,y:3,z:4},.625,15,rng());assert.equal(rows.length,16);assert.equal(rows[0].always,true);for(const r of rows.slice(1)){assert.ok(r.position.y>=3&&r.position.y<3.625);assert.equal(r.always,false);}});
test('glass destruction is a 4x4x4 cube, not a scaled bottle burst',()=>{const rows=glassBreakParticles({x:10,y:-4,z:7});assert.equal(rows.length,64);assert.equal(new Set(rows.map(r=>JSON.stringify(r.position))).size,64);for(const r of rows)assert.equal(r.velocity.x,r.position.x-10.5);});
test('Tavern potion event has8 ITEM plus100 EFFECT and EMPTY-potion colour',()=>{const p=potionSplashParticles({x:-.2,y:3.9,z:1.2},rng());assert.equal(p.shards.length,8);assert.equal(p.spell.length,100);assert.equal(TAVERN_SPLASH_COLOR,0xf800f8);for(const r of p.spell){assert.equal(r.position.y,3.3);assert.equal(r.color[1],0);assert.equal(r.color[0],r.color[2]);assert.ok(r.power>=0&&r.power<4);assert.equal(r.position.x,-.5+r.velocity.x*.1);}});
for(const waxed of [false,true])test(`real trellis transaction emits wax feedback only on commit (${waxed})`,async()=>{
 const f=await fixture(),api=await f.get('bedrock/cultivation.js');const b=f.block(NS+':trellis',undefined,{[NS+':waxed']:!waxed,[NS+':shape']:'single'});f.actor.item={typeId:waxed?'minecraft:honeycomb':'minecraft:iron_axe'};
 assert.equal(api.farmUse(f.actor,b),waxed?'waxed':'unwaxed');assert.equal(f.exchanges,1);assert.ok(f.particles.length>=18&&f.particles.length<=30);assert.ok(f.particles.every(p=>p[0]===NS+':fx_wax_'+(waxed?'on':'off')));assert.equal(f.sounds.length,waxed?2:1);
 const n=f.particles.length;assert.throws(()=>api.farmUse(f.actor,b));assert.equal(f.particles.length,n);
});
test('rejected trellis exchange emits no particles or sounds',async()=>{const f=await fixture(),api=await f.get('bedrock/cultivation.js');const b=f.block(NS+':trellis',undefined,{[NS+':waxed']:false,[NS+':shape']:'single'});f.actor.item={typeId:'minecraft:honeycomb'};f.failExchange=true;assert.throws(()=>api.farmUse(f.actor,b),/injected exchange/);assert.equal(f.particles.length,0);assert.equal(f.sounds.length,0);});
test('wax particle failure never replays the successful material exchange',async()=>{const f=await fixture(),api=await f.get('bedrock/cultivation.js');const b=f.block(NS+':trellis',undefined,{[NS+':waxed']:false,[NS+':shape']:'single'});f.actor.item={typeId:'minecraft:honeycomb'};f.failParticles=true;assert.equal(api.farmUse(f.actor,b),'waxed');assert.equal(f.exchanges,1);});
test('growth accepts support samples and always emits center when support is absent',async()=>{const f=await fixture(),api=await f.get('bedrock/interaction-particles.js'),b=f.block(NS+':light_white');api.plantGrowthFeedback(b);assert.equal(f.particles.length,1);f.block('minecraft:stone',{x:0,y:-1,z:0});api.plantGrowthFeedback(b);assert.equal(f.particles.length,17);});
test('actual string-light dye path includes particles; same colour does not',async()=>{const f=await fixture(),api=await f.get('bedrock/furniture.js'),b=f.block(NS+':light_white',undefined,{[NS+':facing']:0});f.actor.item={typeId:'minecraft:red_dye'};assert.equal(api.recolorLight(f.actor,b),true);assert.equal(f.particles.length,1);assert.equal(api.recolorLight(f.actor,b),false);assert.equal(f.exchanges,1);});
test('failed dye exchange produces no happy-villager feedback',async()=>{const f=await fixture(),api=await f.get('bedrock/furniture.js'),b=f.block(NS+':light_white',undefined,{[NS+':facing']:0});f.actor.item={typeId:'minecraft:red_dye'};f.failExchange=true;assert.throws(()=>api.recolorLight(f.actor,b),/injected exchange/);assert.equal(f.particles.length,0);});
for(const item of ['kaleidoscope_tavern:grape','minecraft:apple','minecraft:rotten_flesh'])test(`press input ${item} uses its bound sprite10 times`,async()=>{const f=await fixture(),api=await f.get('bedrock/pressing-feedback.js'),b=f.block(NS+':pressing_tub');api.pressFeedback(b,{pressEffect:'fail',pressItem:item});assert.equal(f.particles.length,10);assert.ok(f.particles.every(p=>p[0]===NS+':fx_'+(ITEM_PARTICLE_SPRITES[item]?'item_atlas':ITEM_PARTICLES[item])));});
test('foreign grape name never aliases local grapes or wood',async()=>{const f=await fixture(),api=await f.get('bedrock/pressing-feedback.js'),b=f.block(NS+':pressing_tub');api.pressFeedback(b,{pressEffect:'success',pressItem:'other:grape'});assert.equal(f.particles.length,0);assert.equal(f.sounds.length,1);assert.equal(api.pressingParticleDiagnostics.missingSpriteCount,1);});
test('empty dry tub is BLOCK debris, wet/full tub is10 RAIN particles',async()=>{const f=await fixture(),api=await f.get('bedrock/pressing-feedback.js'),b=f.block(NS+':pressing_tub');api.pressFeedback(b,{pressEffect:'fail'});assert.ok(f.particles.every(p=>p[0]===NS+':fx_pressed_tub'));for(const status of ['success','finished']){f.particles.length=0;api.pressFeedback(b,{pressEffect:status});assert.equal(f.particles.length,10);assert.ok(f.particles.every(p=>p[0]===NS+':fx_rain'));}});
test('addon particle contract is optional, namespaced, bounded, and rejects duplicates',()=>{const good={itemParticles:[{item:'sample:fruit',particle:'sample:fruit_fragment'}]};assert.deepEqual(normalizeFoundation(good,'sample',()=>true).itemParticles,good.itemParticles);assert.equal(Object.hasOwn(normalizeFoundation({},'sample',()=>true),'itemParticles'),false);assert.throws(()=>normalizeFoundation({itemParticles:[{item:'minecraft:apple',particle:'sample:p'}]},'sample',()=>true));assert.throws(()=>normalizeFoundation({itemParticles:[{item:'sample:i',particle:'other:p'}]},'sample',()=>true));assert.throws(()=>normalizeFoundation({itemParticles:[...good.itemParticles,...good.itemParticles]},'sample',()=>true));});
test('addon re-registration removes old sprite binding',()=>{installContent('sample',[],{itemParticles:[{item:'sample:i',particle:'sample:p'}]});assert.equal(externalItemParticle('sample:i'),'sample:p');installContent('sample',[],{});assert.equal(externalItemParticle('sample:i'),undefined);});
test('registered addon sprite emitted, without host fx prefix corruption',async()=>{const f=await fixture();const ext=await f.get('core/extension-content.js');ext.installContent('sample',[],{itemParticles:[{item:'sample:fruit',particle:'sample:fragment'}]});const api=await f.get('bedrock/pressing-feedback.js');api.pressFeedback(f.block(NS+':pressing_tub'),{pressEffect:'success',pressItem:'sample:fruit'});assert.equal(f.particles.length,10);assert.ok(f.particles.every(p=>p[0]==='sample:fragment'));});
test('real storage projectile emits impact once even when no effects rolled',async()=>{const f=await fixture(),api=await f.get('bedrock/storage-projectile.js'),p=f.dimension.spawnEntity(NS+':thrown_drink',{x:1.2,y:2.4,z:3.7});p.setDynamicProperty(api.THROWN_ITEM,NS+':wine_q3');p.setDynamicProperty(api.THROWN_EFFECTS,'[]');assert.equal(api.resolveThrownDrinkImpact({projectile:p}),true);assert.equal(f.particles.length,108);assert.equal(f.sounds.length,1);assert.equal(p.isValid,false);assert.equal(api.resolveThrownDrinkImpact({projectile:p}),false);assert.equal(f.particles.length,108);});
test('particle failure cannot prevent projectile effect resolution/removal',async()=>{const f=await fixture(),api=await f.get('bedrock/storage-projectile.js'),p=f.dimension.spawnEntity(NS+':thrown_drink',{x:0,y:1,z:0});p.setDynamicProperty(api.THROWN_ITEM,NS+':wine_q3');p.setDynamicProperty(api.THROWN_EFFECTS,'[]');f.failParticles=true;assert.equal(api.resolveThrownDrinkImpact({projectile:p}),true);assert.equal(api.storageProjectileDiagnostics.impacts,1);assert.equal(p.isValid,false);});
test('invalid effect payload does not claim a successful visual hit',async()=>{const f=await fixture(),api=await f.get('bedrock/storage-projectile.js'),p=f.dimension.spawnEntity(NS+':thrown_drink',{x:0,y:1,z:0});p.setDynamicProperty(api.THROWN_ITEM,NS+':wine_q3');p.setDynamicProperty(api.THROWN_EFFECTS,'bad');assert.equal(api.resolveThrownDrinkImpact({projectile:p}),false);assert.equal(f.particles.length,0);assert.equal(p.isValid,false);});
test('placed empty bottle hit generates full glass fragments and no effect projectile',async()=>{const f=await fixture(),api=await f.get('bedrock/display-projectiles.js'),b=f.block(NS+':bottle_empty'),arrow={getComponent:()=>({})};assert.equal(api.handleDisplayProjectileHit({block:b,projectile:arrow}),true);assert.equal(b.isAir,true);assert.equal(f.particles.length,64);assert.equal(f.entities.length,0);assert.equal(api.handleDisplayProjectileHit({block:b,projectile:arrow}),false);assert.equal(f.particles.length,64);});
test('placed drink hit creates zero-velocity projectile at raw block origin with owner',async()=>{const f=await fixture(),b=f.block(NS+':bottle_wine');const bottles=await f.get('core/bottles.js');new bottles.BottleStore(f.server.world).save(bottles.bottleKey(f.dimension.id,b.location),bottles.displayAdd(undefined,NS+':wine_q3',0),-1);const api=await f.get('bedrock/display-projectiles.js'),owner={getGameMode:()=> 'Survival'},arrow={getComponent:()=>({owner})};assert.equal(api.handleDisplayProjectileHit({block:b,projectile:arrow}),true);assert.equal(f.entities.length,1);const p=f.entities[0];assert.deepEqual(plain(p.location),b.location);assert.deepEqual(plain(p.projectile.velocity),{x:0,y:0,z:0});assert.equal(p.projectile.owner,owner);assert.equal(f.particles.length,64);assert.equal(api.displayProjectileDiagnostics.clouds,1);});
test('failed replacement-potion spawn preserves original placed bottle',async()=>{const f=await fixture(),b=f.block(NS+':bottle_wine');const bottles=await f.get('core/bottles.js');new bottles.BottleStore(f.server.world).save(bottles.bottleKey(f.dimension.id,b.location),bottles.displayAdd(undefined,NS+':wine_q3',0),-1);const api=await f.get('bedrock/display-projectiles.js');f.failSpawn=true;assert.equal(api.handleDisplayProjectileHit({block:b,projectile:{getComponent:()=>({})}}),false);assert.equal(b.typeId,NS+':bottle_wine');assert.equal(f.particles.length,0);assert.ok(f.records.size>0);});
test('protected owner cannot break a bottle or spawn cosmetic effects',async()=>{const f=await fixture(),api=await f.get('bedrock/display-projectiles.js'),b=f.block(NS+':bottle_empty');assert.equal(api.handleDisplayProjectileHit({block:b,projectile:{getComponent:()=>({owner:{getGameMode:()=> 'Adventure'}})}}),false);assert.equal(f.particles.length,0);assert.equal(b.isAir,false);});
test('committed item particle IDs resolve and new textures are reviewed',()=>{for(const name of Object.values(ITEM_PARTICLES)){const p=JSON.parse(fs.readFileSync(path.join(ROOT,'runtime/RP/particles/fx_'+name+'.json'))).particle_effect;assert.equal(p.description.identifier,NS+':fx_'+name);assert.equal(p.components['minecraft:emitter_rate_instant'].num_particles,1);}const data=JSON.parse(fs.readFileSync(path.join(ROOT,'tools/effects/interaction-sources.json')));for(const row of data.assets)assert.equal(createHash('sha256').update(fs.readFileSync(path.join(ROOT,'runtime/RP',row.destination))).digest('hex'),row.sha256);});
test('impact resource emitter honours post-constructor Particle.setPower',()=>{const p=JSON.parse(fs.readFileSync(path.join(ROOT,'runtime/RP/particles/fx_potion_spell.json'))).particle_effect;assert.match(p.events.kt_init.expression,/variable.kt_dy=\(variable.kt_dy-0.1\)/);assert.deepEqual(p.components['minecraft:particle_appearance_tinting'].color,['variable.kt_red ?? 1','variable.kt_green ?? 1','variable.kt_blue ?? 1',1]);const projectile=JSON.parse(fs.readFileSync(path.join(ROOT,'runtime/BP/entities/thrown_drink.json')));assert.equal(projectile['minecraft:entity'].components['minecraft:projectile'].hit_sound,undefined);});
test('interaction generator is byte-for-byte reproducible offline',()=>{const paths=[...Object.values(ITEM_PARTICLES).map(n=>'runtime/RP/particles/fx_'+n+'.json'),'runtime/RP/particles/fx_happy_villager.json','runtime/RP/particles/fx_glass_block.json','runtime/RP/particles/fx_potion_shard.json','runtime/RP/particles/fx_potion_spell.json','runtime/RP/particles/fx_pressed_tub.json','runtime/BP/scripts/data/item-particles.js'];const before=paths.map(p=>fs.readFileSync(path.join(ROOT,p)));const r=spawnSync('python',['tools/effects/build_interaction_particles.py'],{cwd:ROOT,encoding:'utf8'});assert.equal(r.status,0,r.stderr);paths.forEach((p,i)=>assert.deepEqual(fs.readFileSync(path.join(ROOT,p)),before[i],p));});

test('static particle atlas preserves full IDs, source hashes and pixel bounds',()=>{
 const manifest=JSON.parse(fs.readFileSync(path.join(ROOT,'tools/effects/item-debris-sources.json')));
 assert.ok(Object.keys(ITEM_PARTICLE_SPRITES).length>200);
 for(const [item,coords]of Object.entries(ITEM_PARTICLE_SPRITES)){
  assert.ok(item.startsWith(NS+':'));assert.ok(manifest.items[item]);
  assert.equal(coords.length,4);assert.ok(coords.every(Number.isInteger));
  const [u,v,w,h]=coords;assert.ok(u>=0&&v>=0&&w>0&&h>0&&u+w<=1024&&v+h<=1024);
 }
 assert.equal(ITEM_PARTICLE_SPRITES['other:grape'],undefined);
 assert.equal(ITEM_PARTICLE_SPRITES[NS+':mystery_cocktail'],undefined,'Animated model must not be silently flattened');
 for(const [file,row]of Object.entries(manifest.sprites))assert.equal(createHash('sha256').update(fs.readFileSync(path.join(ROOT,'runtime/RP',file))).digest('hex'),row.sha256);
});
test('pressed static model sends its actual atlas rectangle to every single emitter',async()=>{
 const f=await fixture(),api=await f.get('bedrock/pressing-feedback.js');
 const item=NS+':wine_q3',sprite=ITEM_PARTICLE_SPRITES[item];assert.ok(sprite);
 api.pressFeedback(f.block(NS+':pressing_tub'),{pressEffect:'fail',pressItem:item});
 assert.equal(f.particles.length,10);
 for(const [id,pos,variables]of f.particles){
  assert.equal(id,NS+':fx_item_atlas');
  for(const [i,key]of ['u','v','width','height'].entries())assert.equal(variables.values['variable.kt_sprite_'+key],sprite[i]);
 }
});
test('static model atlas rebuild is byte-identical offline',()=>{
 const paths=['runtime/RP/particles/fx_item_atlas.json','runtime/RP/textures/kaleidoscope_tavern/particle/item_debris_atlas.png','runtime/BP/scripts/data/item-particle-sprites.js'];
 const before=paths.map(p=>fs.readFileSync(path.join(ROOT,p)));
 const r=spawnSync('python',['tools/effects/build_item_particle_atlas.py'],{cwd:ROOT,encoding:'utf8'});
 assert.equal(r.status,0,r.stderr);paths.forEach((p,i)=>assert.deepEqual(fs.readFileSync(path.join(ROOT,p)),before[i],p));
});
