# C6 give-only focused kit. Leaves existing builds/world untouched.
give @s kaleidoscope_tavern:guidebook 1
give @s kaleidoscope_tavern:recipe_book 1
give @s kaleidoscope_tavern:blue_bar_stool 2
give @s kaleidoscope_tavern:red_bar_stool 2
give @s kaleidoscope_tavern:string_lights_colorless 4
give @s minecraft:green_dye 4
give @s minecraft:red_dye 4
give @s kaleidoscope_tavern:sculk_special 2
give @s kaleidoscope_tavern:screwdriver 2
give @s kaleidoscope_tavern:mojito 2
give @s kaleidoscope_tavern:nether_special 2
give @s kaleidoscope_tavern:depth_charge 2
give @s kaleidoscope_tavern:brass_heart 2
give @s kaleidoscope_tavern:white_lady 2
give @s kaleidoscope_tavern:blue_sofa 2
give @s kaleidoscope_tavern:red_sofa 2
give @s kaleidoscope_tavern:table 3
give @s kaleidoscope_tavern:bar_counter 3
give @s kaleidoscope_tavern:glassware_holder 2
give @s kaleidoscope_tavern:bell_pendant_lamp 2
give @s kaleidoscope_tavern:blue_pendant_lamp 2
give @s kaleidoscope_tavern:yellow_pendant_lamp 2
give @s kaleidoscope_tavern:empty_glassware 8
