import {check,utf8Bytes} from './util.js';
import {storageBottleItem} from './holder.js';
export const NS='kaleidoscope_tavern',CABINET_TYPES=Object.freeze([NS+':bar_cabinet',NS+':glass_bar_cabinet']),CABINET_POSITION=Object.freeze({SINGLE:0,LEFT:1,MIDDLE:2,RIGHT:3});
export const BAR_CABINET_IRREGULAR=Object.freeze(['brandy','carignan']);
export function barCabinetItem(id){return storageBottleItem(id);}
export function barCabinetIrregular(id){const b=storageBottleItem(id);return !!b&&BAR_CABINET_IRREGULAR.includes(b.base);}
export function emptyBarCabinet(){return {schema:1,revision:0,left:null,right:null,single:false};}
export function validateBarCabinet(s){check(s&&s.schema===1,'BAR_CABINET_SCHEMA');check(Number.isInteger(s.revision)&&s.revision>=0,'BAR_CABINET_REVISION');for(const k of['left','right'])if(s[k]!==null)check(barCabinetItem(s[k]),'BAR_CABINET_ITEM');check(typeof s.single==='boolean','BAR_CABINET_SINGLE');if(s.single)check(!!s.left&&s.right===null&&barCabinetIrregular(s.left),'BAR_CABINET_SINGLE_STATE');else check(!barCabinetIrregular(s.left)&&!barCabinetIrregular(s.right),'BAR_CABINET_IRREGULAR_STATE');return s;}
export function barCabinetClickedLeft(facing,location){check(Number.isInteger(facing)&&facing>=0&&facing<=3,'INVALID_FACING');check(location&&Number.isFinite(location.x)&&Number.isFinite(location.z),'INVALID_FACE_LOCATION');check(location.x>=0&&location.x<=1&&location.z>=0&&location.z<=1,'INVALID_FACE_LOCATION');return facing===0?location.x>.5:facing===2?location.x<.5:facing===1?location.z<.5:location.z>.5;}
export function barCabinetPut(s,clickedLeft,item){validateBarCabinet(s);const b=barCabinetItem(item);check(b,'NOT_BAR_CABINET_BOTTLE');if(s.single)return {changed:false,state:s};let side=clickedLeft?'left':'right',single=false;if(barCabinetIrregular(item)){if(s.left||s.right)return {changed:false,state:s};side='left';single=true;}else if(s.left&&!s.right&&clickedLeft)side='right';else if(!s.left&&s.right&&!clickedLeft)side='left';if(s[side])return {changed:false,state:s};const next={...s,revision:s.revision+1,[side]:b.item,single};return {changed:true,side,state:validateBarCabinet(next)};}
export function barCabinetTake(s,clickedLeft){validateBarCabinet(s);let side=clickedLeft?'left':'right';if(s.single)side='left';else if(!s.left&&s.right&&clickedLeft)side='right';else if(s.left&&!s.right&&!clickedLeft)side='left';const item=s[side];if(!item)return {changed:false,state:s};const next={...s,revision:s.revision+1,[side]:null,single:false};return {changed:true,side,item,state:validateBarCabinet(next)};}
export function barCabinetPosition(typeId,facing,{left,right}={}){check(CABINET_TYPES.includes(typeId),'INVALID_CABINET_TYPE');check(Number.isInteger(facing)&&facing>=0&&facing<=3,'INVALID_FACING');const same=n=>n?.typeId===typeId&&n?.facing===facing,l=same(left),r=same(right);return l&&r?CABINET_POSITION.MIDDLE:l?CABINET_POSITION.RIGHT:r?CABINET_POSITION.LEFT:CABINET_POSITION.SINGLE;}
export function barCabinetKey(d,p,typeId){check(/^minecraft:[a-z_]+$/.test(d),'INVALID_DIMENSION');check(CABINET_TYPES.includes(typeId),'INVALID_CABINET_TYPE');check([p.x,p.y,p.z].every(Number.isInteger),'INVALID_LOCATION');return `kt:bar_cabinet/${d.split(':')[1]}/${typeId.split(':')[1]}/${p.x}_${p.y}_${p.z}`;}
export function barCabinetAnchor(key,side){check(['left','right'].includes(side),'BAR_CABINET_SIDE');return key+'/'+side;}
export function parseBarCabinetAnchor(raw){check(typeof raw==='string','MISSING_BAR_CABINET_ANCHOR');const m=/^kt:bar_cabinet\/([a-z_]+)\/(bar_cabinet|glass_bar_cabinet)\/(-?\d+)_(-?\d+)_(-?\d+)\/(left|right)$/.exec(raw);check(m,'INVALID_BAR_CABINET_ANCHOR');return {dimension:'minecraft:'+m[1],typeId:NS+':'+m[2],position:{x:Number(m[3]),y:Number(m[4]),z:Number(m[5])},side:m[6]};}
function rotate(dx,dz,facing){return facing===0?{x:dx,z:dz}:facing===1?{x:-dz,z:dx}:facing===2?{x:-dx,z:-dz}:{x:dz,z:-dx};}
export function barCabinetVisualPose(side,single,facing){check(['left','right'].includes(side),'BAR_CABINET_SIDE');check(Number.isInteger(facing)&&facing>=0&&facing<=3,'INVALID_FACING');let dx=0;if(!single){const axisZ=facing===0||facing===2;dx=(side==='left'?(axisZ?.25:-.25):(axisZ?-.25:.25));}const r=rotate(dx,0,facing);return {offset:{x:.5+r.x,y:.0625,z:.5+r.z},rotation:{x:0,y:[0,90,180,-90][facing]}};}
export class BarCabinetStore{constructor(backend){this.backend=backend;}raw(k){return this.backend.getDynamicProperty(k);}load(k){const raw=this.raw(k);if(raw===undefined)return undefined;check(typeof raw==='string','CORRUPT_BAR_CABINET_STATE');return validateBarCabinet(JSON.parse(raw));}save(k,s,expected){const prev=this.load(k);check((prev?.revision??-1)===expected,'STATE_CONFLICT');const raw=s?JSON.stringify(validateBarCabinet(s)):undefined;check(!raw||utf8Bytes(raw)<=1024,'STATE_TOO_LARGE');this.backend.setDynamicProperty(k,raw);}restore(k,raw){this.backend.setDynamicProperty(k,raw);}}
