import {rotationSegment} from './java-placement.js';
import {check} from './util.js';
export const NS='kaleidoscope_tavern';
export const SANDWICH_BOARDS=Object.freeze(['base_sandwich_board','grass_sandwich_board','allium_sandwich_board','azure_bluet_sandwich_board','cornflower_sandwich_board','orchid_sandwich_board','peony_sandwich_board','pink_petals_sandwich_board','pitcher_plant_sandwich_board','poppy_sandwich_board','sunflower_sandwich_board','torchflower_sandwich_board','tulip_sandwich_board','wither_rose_sandwich_board'].map(n=>NS+':'+n));
export const CHALKBOARD=NS+':chalkboard',BOARD_HALF=NS+':half',BOARD_ROTATION=NS+':rotation',CHALK_POSITION=NS+':position';
export const FLOWER_BOARD_TRANSFORMS=Object.freeze({
 'minecraft:grass':NS+':grass_sandwich_board','minecraft:allium':NS+':allium_sandwich_board','minecraft:azure_bluet':NS+':azure_bluet_sandwich_board','minecraft:oxeye_daisy':NS+':azure_bluet_sandwich_board','minecraft:lily_of_the_valley':NS+':azure_bluet_sandwich_board','minecraft:cornflower':NS+':cornflower_sandwich_board','minecraft:blue_orchid':NS+':orchid_sandwich_board','minecraft:peony':NS+':peony_sandwich_board','minecraft:lilac':NS+':peony_sandwich_board','minecraft:pink_petals':NS+':pink_petals_sandwich_board','minecraft:pitcher_plant':NS+':pitcher_plant_sandwich_board','minecraft:poppy':NS+':poppy_sandwich_board','minecraft:rose_bush':NS+':poppy_sandwich_board','minecraft:sunflower':NS+':sunflower_sandwich_board','minecraft:dandelion':NS+':sunflower_sandwich_board','minecraft:torchflower':NS+':torchflower_sandwich_board','minecraft:red_tulip':NS+':tulip_sandwich_board','minecraft:orange_tulip':NS+':tulip_sandwich_board','minecraft:white_tulip':NS+':tulip_sandwich_board','minecraft:pink_tulip':NS+':tulip_sandwich_board','minecraft:wither_rose':NS+':wither_rose_sandwich_board'
});
export const BOARD_DYES=Object.freeze(['white','orange','magenta','light_blue','yellow','lime','pink','gray','light_gray','cyan','purple','blue','brown','green','red','black']);
export const BOARD_ALIGNMENTS=Object.freeze(['left','center','right']);
export function boardRotation16(yaw){check(Number.isFinite(yaw),'INVALID_ROTATION');return rotationSegment(yaw);}
export function boardBase(pos,half){check(pos&&Number.isInteger(pos.x)&&Number.isInteger(pos.y)&&Number.isInteger(pos.z),'INVALID_LOCATION');check(half===0||half===1,'INVALID_BOARD_HALF');return {x:pos.x,y:pos.y-half,z:pos.z};}
export function chalkCenter(base,position,facing){check(Number.isInteger(position)&&position>=0&&position<=3,'INVALID_CHALK_POSITION');const cw={north:{x:1,z:0},east:{x:0,z:1},south:{x:-1,z:0},west:{x:0,z:-1}}[facing];check(cw,'INVALID_CHALK_FACING');if(position===1)return {x:base.x+cw.x,y:base.y,z:base.z+cw.z};if(position===3)return {x:base.x-cw.x,y:base.y,z:base.z-cw.z};return base;}
export function boardRuntimeKey(dimension,pos){check(typeof dimension==='string'&&dimension.length,'INVALID_DIMENSION');return `kt:writingBoard/${dimension.replace(':','_')}/${pos.x}_${pos.y}_${pos.z}`;}
export function normalizeBoardData(value,max=320){check(value&&typeof value==='object','INVALID_BOARD_DATA');check(Number.isInteger(max)&&max>0,'INVALID_BOARD_LIMIT');check(typeof value.text==='string'&&value.text.length<=max,'BOARD_TEXT_TOO_LONG');check(BOARD_DYES.includes(value.color),'INVALID_BOARD_COLOR');check(typeof value.glowing==='boolean'&&typeof value.waxed==='boolean','INVALID_BOARD_FLAGS');const alignment=value.alignment??'center';check(BOARD_ALIGNMENTS.includes(alignment),'INVALID_BOARD_ALIGNMENT');return {text:value.text,color:value.color,glowing:value.glowing,waxed:value.waxed,alignment};}
