import {check,utf8Bytes} from './util.js';
import {holderItem} from './holder.js';
import {CABINET_POSITION} from './bar-cabinet.js';
export const NS='kaleidoscope_tavern',CELLAR_CABINET=NS+':cellar_cabinet';
export function cellarCabinetItem(id){return holderItem(id);}
function faceName(facing){check(Number.isInteger(facing)&&facing>=0&&facing<=3,'INVALID_FACING');return ['north','east','south','west'][facing];}
export function cellarCabinetSlot(facing,face,location){check(location&&Number.isFinite(location.x)&&Number.isFinite(location.y)&&Number.isFinite(location.z),'INVALID_FACE_LOCATION');check(location.x>=0&&location.x<=1&&location.y>=0&&location.y<=1&&location.z>=0&&location.z<=1,'INVALID_FACE_LOCATION');if(String(face).toLowerCase()!==faceName(facing))return -1;const localX=facing===0?1-location.x:facing===2?location.x:facing===1?1-location.z:location.z;const column=Math.min(2,Math.floor(localX*3)),row=2-(Math.min(2,Math.floor(location.y*3)));return column+row*3;}
export function emptyCellarCabinet(){return {schema:1,revision:0,slots:Array(9).fill(null)};}
export function validateCellarCabinet(s){check(s&&s.schema===1,'CELLAR_CABINET_SCHEMA');check(Number.isInteger(s.revision)&&s.revision>=0,'CELLAR_CABINET_REVISION');check(Array.isArray(s.slots)&&s.slots.length===9,'CELLAR_CABINET_SLOTS');for(const item of s.slots)if(item!==null)check(cellarCabinetItem(item),'CELLAR_CABINET_ITEM');return s;}
export function cellarCabinetPut(s,slot,item){validateCellarCabinet(s);check(Number.isInteger(slot)&&slot>=0&&slot<9,'CELLAR_CABINET_SLOT');check(s.slots[slot]===null,'CELLAR_CABINET_OCCUPIED');const b=cellarCabinetItem(item);check(b,'NOT_CELLAR_CABINET_BOTTLE');const slots=s.slots.slice();slots[slot]=b.item;return validateCellarCabinet({...s,revision:s.revision+1,slots});}
export function cellarCabinetTake(s,slot){validateCellarCabinet(s);check(Number.isInteger(slot)&&slot>=0&&slot<9,'CELLAR_CABINET_SLOT');const item=s.slots[slot];check(item,'CELLAR_CABINET_EMPTY');const slots=s.slots.slice();slots[slot]=null;return {item,state:validateCellarCabinet({...s,revision:s.revision+1,slots})};}
export function cellarCabinetPosition(facing,{left,right}={}){check(Number.isInteger(facing)&&facing>=0&&facing<=3,'INVALID_FACING');const same=n=>n?.typeId===CELLAR_CABINET&&n?.facing===facing,l=same(left),r=same(right);return l&&r?CABINET_POSITION.MIDDLE:l?CABINET_POSITION.RIGHT:r?CABINET_POSITION.LEFT:CABINET_POSITION.SINGLE;}
export function cellarCabinetKey(d,p){check(/^minecraft:[a-z_]+$/.test(d),'INVALID_DIMENSION');check([p.x,p.y,p.z].every(Number.isInteger),'INVALID_LOCATION');return `kt:cellar_cabinet/${d.split(':')[1]}/${p.x}_${p.y}_${p.z}`;}
export function cellarCabinetAnchor(key,slot){check(Number.isInteger(slot)&&slot>=0&&slot<9,'CELLAR_CABINET_SLOT');return key+'/'+slot;}
export function parseCellarCabinetAnchor(raw){check(typeof raw==='string','MISSING_CELLAR_CABINET_ANCHOR');const m=/^kt:cellar_cabinet\/([a-z_]+)\/(-?\d+)_(-?\d+)_(-?\d+)\/(\d)$/.exec(raw);check(m,'INVALID_CELLAR_CABINET_ANCHOR');const slot=Number(m[5]);check(slot>=0&&slot<9,'CELLAR_CABINET_SLOT');return {dimension:'minecraft:'+m[1],position:{x:Number(m[2]),y:Number(m[3]),z:Number(m[4])},slot};}
function rotate(x,z,facing){const dx=x-.5,dz=z-.5;return facing===0?{x,z}:facing===1?{x:.5-dz,z:.5+dx}:facing===2?{x:.5-dx,z:.5-dz}:{x:.5+dz,z:.5-dx};}
export function cellarCabinetVisualPose(slot,facing){check(Number.isInteger(slot)&&slot>=0&&slot<9,'CELLAR_CABINET_SLOT');check(Number.isInteger(facing)&&facing>=0&&facing<=3,'INVALID_FACING');const row=Math.floor(slot/3),column=slot%3,p=rotate(.825-column*.325,.875,facing);return {offset:{x:p.x,y:.78-row*.29,z:p.z},rotation:{x:-90,y:[0,90,180,-90][facing]}};}
export class CellarCabinetStore{constructor(backend){this.backend=backend;}raw(k){return this.backend.getDynamicProperty(k);}load(k){const raw=this.raw(k);if(raw===undefined)return undefined;check(typeof raw==='string','CORRUPT_CELLAR_CABINET_STATE');return validateCellarCabinet(JSON.parse(raw));}save(k,s,expected){const prev=this.load(k);check((prev?.revision??-1)===expected,'STATE_CONFLICT');const raw=s?JSON.stringify(validateCellarCabinet(s)):undefined;check(!raw||utf8Bytes(raw)<=3072,'STATE_TOO_LARGE');this.backend.setDynamicProperty(k,raw);}restore(k,raw){this.backend.setDynamicProperty(k,raw);}}
