import {check,utf8Bytes} from './util.js';
import {storageBottleItem} from './holder.js';
export const NS='kaleidoscope_tavern',TILTED_RACK=NS+':tilted_rack';
export const TILTED_BLOCKED=Object.freeze(['brandy','carignan']);
export function tiltedRackItem(id){const b=storageBottleItem(id);return b&&!TILTED_BLOCKED.includes(b.base)?b:undefined;}
export function tiltedRackBlockedItem(id){const b=storageBottleItem(id);return !!b&&TILTED_BLOCKED.includes(b.base);}
export function tiltedRackSlot(facing,location){check(Number.isInteger(facing)&&facing>=0&&facing<=3,'INVALID_FACING');check(location&&Number.isFinite(location.x)&&Number.isFinite(location.z),'INVALID_FACE_LOCATION');check(location.x>=0&&location.x<=1&&location.z>=0&&location.z<=1,'INVALID_FACE_LOCATION');const local=facing===0?1-location.x:facing===2?location.x:facing===1?1-location.z:location.z;return local<1/3?0:local<2/3?1:2;}
export function emptyTiltedRack(){return {schema:1,revision:0,slots:[null,null,null]};}
export function validateTiltedRack(s){check(s&&s.schema===1,'TILTED_RACK_SCHEMA');check(Number.isInteger(s.revision)&&s.revision>=0,'TILTED_RACK_REVISION');check(Array.isArray(s.slots)&&s.slots.length===3,'TILTED_RACK_SLOTS');for(const item of s.slots)if(item!==null)check(tiltedRackItem(item),'TILTED_RACK_ITEM');return s;}
export function tiltedRackPut(s,slot,item){validateTiltedRack(s);check(Number.isInteger(slot)&&slot>=0&&slot<3,'TILTED_RACK_SLOT');check(s.slots[slot]===null,'TILTED_RACK_OCCUPIED');const b=tiltedRackItem(item);check(b,'NOT_TILTED_RACK_BOTTLE');const slots=s.slots.slice();slots[slot]=b.item;return validateTiltedRack({...s,revision:s.revision+1,slots});}
export function tiltedRackTake(s,slot){validateTiltedRack(s);check(Number.isInteger(slot)&&slot>=0&&slot<3,'TILTED_RACK_SLOT');const item=s.slots[slot];check(item,'TILTED_RACK_EMPTY');const slots=s.slots.slice();slots[slot]=null;return {item,state:validateTiltedRack({...s,revision:s.revision+1,slots})};}
export function tiltedRackKey(d,p){check(/^minecraft:[a-z_]+$/.test(d),'INVALID_DIMENSION');check([p.x,p.y,p.z].every(Number.isInteger),'INVALID_LOCATION');return `kt:tilted_rack/${d.split(':')[1]}/${p.x}_${p.y}_${p.z}`;}
export function tiltedRackAnchor(key,slot){check(Number.isInteger(slot)&&slot>=0&&slot<3,'TILTED_RACK_SLOT');return key+'/'+slot;}
export function parseTiltedRackAnchor(raw){check(typeof raw==='string','MISSING_TILTED_RACK_ANCHOR');const m=/^kt:tilted_rack\/([a-z_]+)\/(-?\d+)_(-?\d+)_(-?\d+)\/(\d)$/.exec(raw);check(m,'INVALID_TILTED_RACK_ANCHOR');const slot=Number(m[5]);check(slot>=0&&slot<3,'TILTED_RACK_SLOT');return {dimension:'minecraft:'+m[1],position:{x:Number(m[2]),y:Number(m[3]),z:Number(m[4])},slot};}
const S=Math.sin(Math.PI/8),C=Math.cos(Math.PI/8),Y=.9*(.3125-.5*S);
export function tiltedRackVisualPose(slot,facing){check(Number.isInteger(slot)&&slot>=0&&slot<3,'TILTED_RACK_SLOT');check(Number.isInteger(facing)&&facing>=0&&facing<=3,'INVALID_FACING');let x=.9*((.425-.375*slot)+.5),z=.9*((.02+(slot-1)*.005)+.5*C);const dx=x-.5,dz=z-.5;if(facing===1)[x,z]=[.5-dz,.5+dx];else if(facing===2)[x,z]=[.5-dx,.5-dz];else if(facing===3)[x,z]=[.5+dz,.5-dx];return {offset:{x,y:Y,z},rotation:{x:22.5,y:[0,90,180,-90][facing]}};}
export class TiltedRackStore{constructor(backend){this.backend=backend;}raw(k){return this.backend.getDynamicProperty(k);}load(k){const raw=this.raw(k);if(raw===undefined)return undefined;check(typeof raw==='string','CORRUPT_TILTED_RACK_STATE');return validateTiltedRack(JSON.parse(raw));}save(k,s,expected){const prev=this.load(k);check((prev?.revision??-1)===expected,'STATE_CONFLICT');const raw=s?JSON.stringify(validateTiltedRack(s)):undefined;check(!raw||utf8Bytes(raw)<=1024,'STATE_TOO_LARGE');this.backend.setDynamicProperty(k,raw);}restore(k,raw){this.backend.setDynamicProperty(k,raw);}}
