/** Source-focused pure rules; no claims of running a Minecraft world. */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import {NS,KINDS,SHAPES,frameType,updateFrame,speciesForSoil,growthProbability,nextFruitAge,fruitHarvest} from '../runtime/BP/scripts/core/cultivation.js';
import {BOTTLES} from '../runtime/BP/scripts/data/bottles.js';
import {DRINK_EFFECTS} from '../runtime/BP/scripts/data/drink-effects.js';
import {parseBottle,displayAdd,displayTake,validateDisplay,bottleKey,BottleStore} from '../runtime/BP/scripts/core/bottles.js';
import {NATIVE_EFFECTS,drinkRows,rollDrinkEffects} from '../runtime/BP/scripts/core/drink-effects.js';
import {GUIDE_PAGES} from '../runtime/BP/scripts/data/guide-pages.js';
import {EFFECT_PAGES} from '../runtime/BP/scripts/data/effect-pages.js';
const id=(b,q)=>`${NS}:${b}_q${q}`;
const code=(f,c)=>assert.throws(f,e=>e.code===c);
const seq=(...a)=>()=>{assert(a.length,'Unexpected extra random draw');return a.shift();};
const json=p=>JSON.parse(fs.readFileSync(new URL('../'+p,import.meta.url)));

test('new immutable source records all have original SHA256',()=>{for(const r of json('data/upstream/c2/source.lock.json').records){const raw=fs.readFileSync(new URL('../'+r.path,import.meta.url));assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),r.sha256,r.path);}});
test('normal, cold and nether soils select three vines; green is not a planted species',()=>{assert.equal(speciesForSoil('minecraft:dirt'),'grape');assert.equal(speciesForSoil('minecraft:packed_ice'),'ice_grape');assert.equal(speciesForSoil('minecraft:snow_block'),'ice_grape');assert.equal(speciesForSoil('minecraft:netherrack'),'gold_grape');assert.equal(speciesForSoil('minecraft:magma'),'gold_grape');assert.equal(speciesForSoil('minecraft:stone'),undefined);assert(!KINDS.includes('green_grape'));});
test('trellis placement axes source truth table exhaustively covers24 combinations',()=>{const expected={'000':['east_west','single','north_south'],'100':['east_west','cross_east_west','cross_up_down'],'010':['cross_east_west','single','cross_north_south'],'001':['cross_up_down','cross_north_south','north_south'],'110':['cross_east_west','cross_east_west','cross_east_west'],'101':['cross_up_down','cross_up_down','cross_up_down'],'011':['cross_north_south','cross_north_south','cross_north_south'],'111':['six_direction','six_direction','six_direction']};for(const[key,want]of Object.entries(expected))for(const[i,axis]of ['x','y','z'].entries())assert.equal(frameType(...key.padStart(3,'0').split('').map(x=>x==='1'),axis),want[i]);});
test('disconnected basic frames preserve their placement axes',()=>{assert.equal(updateFrame('single',false,false,false),'single');assert.equal(updateFrame('east_west',false,false,false),'east_west');assert.equal(updateFrame('north_south',false,false,false),'north_south');});
test('cross and six-way frames degrade according to surviving neighbor axes',()=>{assert.equal(updateFrame('cross_east_west',true,false,false),'east_west');assert.equal(updateFrame('cross_north_south',false,false,true),'north_south');assert.equal(updateFrame('cross_up_down',false,false,false),'north_south');assert.equal(updateFrame('six_direction',true,false,true),'cross_up_down');for(const s of SHAPES)for(const mask of Array.from({length:8},(_,i)=>i))assert(SHAPES.includes(updateFrame(s,!!(mask&1),!!(mask&2),!!(mask&4))));});
test('climate rule supports exact source thresholds but missing temperatures use0.25',()=>{assert.equal(growthProbability('ice_grape',.149),.8);assert.equal(growthProbability('ice_grape',.15),.25);assert.equal(growthProbability('gold_grape',1.001),.8);assert.equal(growthProbability('gold_grape',1),.25);for(const k of KINDS)assert.equal(growthProbability(k),.25);});
test('fruit increment1 or2 clamps at5 and rejects invalid RNG',()=>{assert.equal(nextFruitAge(1,()=>0),2);assert.equal(nextFruitAge(1,()=>.999),3);assert.equal(nextFruitAge(4,()=>.999),5);code(()=>nextFruitAge(2,()=>1),'INVALID_RNG');code(()=>nextFruitAge(6,()=>0),'BAD_AGE');});
test('immature fruit has no loot and does not draw random values',()=>{for(const k of KINDS)for(let a=0;a<5;a++)assert.deepEqual(fruitHarvest(k,a,true,()=>{throw Error('must not draw');}),[]);});
test('shears return3 primary plus1 or2 green with strict30% threshold',()=>{assert.deepEqual(fruitHarvest('ice_grape',5,true,seq(.2999,.9999)),[{id:NS+':ice_grape',count:3},{id:NS+':green_grape',count:2}]);assert.equal(fruitHarvest('gold_grape',5,true,seq(.3)).length,1);assert.equal(fruitHarvest('grape',5,true,seq(0,0))[1].count,1);});
test('normal ripe break uses source1–2 primary and at most1 green',()=>{assert.deepEqual(fruitHarvest('grape',5,false,seq(.99,.1)),[{id:NS+':grape',count:2},{id:NS+':green_grape',count:1}]);assert.deepEqual(fruitHarvest('grape',5,false,seq(0,.9)),[{id:NS+':grape',count:1}]);});
test('24 actual bottle families use93 exact count arrangements, three families cap3',()=>{assert.equal(Object.keys(BOTTLES).length,24);assert.equal(Object.values(BOTTLES).reduce((n,x)=>n+x.maxCount,0),93);assert.deepEqual(Object.keys(BOTTLES).filter(b=>BOTTLES[b].maxCount===3).sort(),['brandy','carignan','sunset_glow']);assert.equal(parseBottle(NS+':watermelon_juice_q3'),undefined);});
test('bottle IDs strictly validate family and all six quality values',()=>{for(const b of Object.keys(BOTTLES))for(let q=1;q<=6;q++)assert.deepEqual(parseBottle(id(b,q)),{base:b,quality:q,id:id(b,q)});for(const x of ['wine_q0','wine_q7','wine_q01','wine_q3:extra','absent_q3'])assert.equal(parseBottle(NS+':'+x),undefined);});
test('mixed qualities are retained in order and inputs never mutated',()=>{let s=displayAdd(undefined,id('wine',1),2);const first=structuredClone(s);s=displayAdd(s,id('wine',6));assert.deepEqual(first.items,[id('wine',1)]);s=displayAdd(s,id('wine',2));assert.deepEqual(s.items,[id('wine',1),id('wine',6),id('wine',2)]);const r=displayTake(s);assert.equal(r.give[0].id,id('wine',2));assert.deepEqual(r.state.items,[id('wine',1),id('wine',6)]);assert.equal(s.items.length,3);});
test('taking all mixed-quality bottles does not average, reorder or relabel',()=>{let s;for(const q of [6,1,4,2])s=displayAdd(s,id('wine',q));const r=displayTake(s,true);assert.equal(r.state,undefined);assert.deepEqual(r.give.map(x=>x.id),[6,1,4,2].map(q=>id('wine',q)));});
test('different drinks and fourth bottle for3-cap families reject before state changes',()=>{let s;for(let q=1;q<=3;q++)s=displayAdd(s,id('brandy',q));code(()=>displayAdd(s,id('brandy',4)),'BOTTLE_CAPACITY');code(()=>displayAdd(s,id('wine',4)),'DIFFERENT_DRINK');assert.equal(s.items.length,3);});
test('all families return exactly placed quality inventory across exhaustive quality sequences',()=>{for(const b of Object.keys(BOTTLES))for(let seed=0;seed<36;seed++){let s;const ids=[];for(let i=0;i<BOTTLES[b].maxCount;i++){const x=id(b,(seed+i*5)%6+1);ids.push(x);s=displayAdd(s,x);}const out=[];while(s){const t=displayTake(s);out.push(t.give[0].id);s=t.state;}assert.deepEqual(out.reverse(),ids);}});
test('bottle storage is persistent by dimension with revision conflict guard',()=>{const dp=new Map(),backend={getDynamicProperty:k=>dp.get(k),setDynamicProperty:(k,v)=>v===undefined?dp.delete(k):dp.set(k,v)};const a=new BottleStore(backend),k=bottleKey('minecraft:overworld',{x:-9,y:64,z:0}),s=displayAdd(undefined,id('wine',5));a.save(k,s,-1);assert.deepEqual(new BottleStore(backend).load(k),s);code(()=>a.save(k,s,-1),'STATE_CONFLICT');assert.notEqual(k,bottleKey('minecraft:nether',{x:-9,y:64,z:0}));a.save(k,undefined,0);assert.equal(a.load(k),undefined);});
test('malformed stored qualities or future schema cannot produce substituted output',()=>{const good=displayAdd(undefined,id('wine',3));code(()=>validateDisplay({...good,schema:2}),'BOTTLE_SCHEMA');code(()=>validateDisplay({...good,items:[id('brandy',3)]}),'CORRUPT_BOTTLES');code(()=>validateDisplay({...good,items:[]}),'BOTTLE_CAPACITY');});
test('generated effect data is exactly the24 uploaded JAR JSON rows',()=>{for(const[b,rows]of Object.entries(DRINK_EFFECTS)){assert.deepEqual(rows,json(`data/upstream/c2/data/${NS}/datamap/drink_effect/${b}.json`).effects);assert.equal(rows.length,6);}});
test('Q1 indexes first source row and nausea30seconds becomes600ticks',()=>{assert.deepEqual(rollDrinkEffects(id('wine',1),()=>0),[{effect:'minecraft:nausea',duration:30,amplifier:0,probability:1,bedrockId:'nausea',ticks:600}]);});
test('Q3/Q6 regeneration uses source seconds and zero-based amplifier',()=>{let row=rollDrinkEffects(id('wine',3),()=>0).find(x=>x.bedrockId==='regeneration');assert.equal(row.ticks,1600);assert.equal(row.amplifier,0);row=rollDrinkEffects(id('wine',6),()=>0).find(x=>x.bedrockId==='regeneration');assert.equal(row.ticks,10800);assert.equal(row.amplifier,1);});
test('probability rolls are independent and strictly below source probability',()=>{const match=Object.entries(DRINK_EFFECTS).flatMap(([b,rows])=>rows.map((r,q)=>({b,q:q+1,r}))).find(x=>x.r.some(e=>e.probability<1&&e.probability>0));assert(match);const i=match.r.findIndex(e=>e.probability<1&&e.probability>0);const e=match.r[i];let n=0;const selected=rollDrinkEffects(id(match.b,match.q),()=>n++===i?e.probability:.999999);assert(!selected.some(x=>x.effect===e.effect));assert.equal(n,match.r.length);});
test('instant health uses one tick; source instant duration is not reused as a timed buff',()=>{const m=Object.entries(DRINK_EFFECTS).flatMap(([b,rs])=>rs.map((r,q)=>({b,q:q+1,r}))).find(x=>x.r.some(e=>e.effect==='minecraft:instant_health'));assert(m);assert.equal(rollDrinkEffects(id(m.b,m.q),()=>0).find(x=>x.bedrockId==='instant_health').ticks,1);});
test('custom effects have no fabricated vanilla mapping and original rows remain unchanged',()=>{const before=JSON.stringify(DRINK_EFFECTS),a=rollDrinkEffects(id('wine',2),()=>0);assert.equal(a[0].bedrockId,null);assert.equal(a[0].effect,NS+':slightly_tipsy');assert.equal(NATIVE_EFFECTS[NS+':slightly_tipsy'],undefined);assert.equal(JSON.stringify(DRINK_EFFECTS),before);assert.deepEqual(drinkRows('foreign:drink'),[]);});
test('every existing quality item uses the complete-use hook without a competing food behavior',()=>{for(const b of Object.keys(BOTTLES))for(let q=1;q<=6;q++){const c=json(`runtime/BP/items/${b}_q${q}.json`)['minecraft:item'].components;assert(c[NS+':drink_effects']);assert.equal(c['minecraft:food'],undefined);assert.deepEqual(c['minecraft:use_modifiers'],{use_duration:1.6,movement_modifier:.35,start_using:'if_first'});assert.equal(c['minecraft:use_animation'],'drink');assert.equal(c['minecraft:max_stack_size'],16);}});
test('eight crafting recipes include exact source trellis and clearly separate port starter',()=>{const trellis=json('runtime/BP/recipes/trellis.json')['minecraft:recipe_shaped'],src=json('data/upstream/recipes/trellis.json');assert.deepEqual(trellis.pattern,src.pattern);assert.equal(trellis.result.count,8);const starter=json('runtime/BP/recipes/grapevine_starter.json')['minecraft:recipe_shapeless'];assert.deepEqual(starter.ingredients,[{item:'minecraft:vine'},{item:'minecraft:sweet_berries'}]);assert.equal(starter.result.item,NS+':grapevine');});
test('independent guides explicitly report climate/worldgen/custom-effect limitations and show24 effect pages',()=>{assert.equal(EFFECT_PAGES.length,24);assert(GUIDE_PAGES.some(x=>x.id===NS+':cultivation'&&x.body.zh_TW.includes('移植版新增')));assert(GUIDE_PAGES.find(x=>x.id===NS+':limitations').body.zh_TW.includes('氣候加速'));assert(EFFECT_PAGES.every(x=>x.body.zh_TW.includes('Q1:')&&x.body.zh_TW.includes('Q6:')));assert(EFFECT_PAGES.some(x=>x.body.en_US.includes('[not implemented]')));});

import {isBottleSupport,SUPPORT_TAG} from '../runtime/BP/scripts/core/bottle-support.js';
test('stable support whitelist rejects uncertain partial blocks, third-party block tag opts in',()=>{for(const id of ['minecraft:stone','minecraft:oak_planks','minecraft:purple_wool','minecraft:glass'])assert(isBottleSupport(id));for(const id of ['minecraft:air','minecraft:water','minecraft:oak_stairs','minecraft:fence','foreign:table'])assert(!isBottleSupport(id));assert(isBottleSupport('foreign:table',[SUPPORT_TAG]));});

test('probability comparison uses Java float32 semantics at a 0.15 source boundary',()=>{const id15=Object.entries(DRINK_EFFECTS).flatMap(([b,rows])=>rows.map((r,q)=>({b,q:q+1,r}))).find(x=>x.r.some(e=>Math.fround(e.probability)===Math.fround(.15)));assert(id15);const effect=id15.r.find(e=>Math.fround(e.probability)===Math.fround(.15));const exact=rollDrinkEffects(id(id15.b,id15.q),()=>.15);assert(!exact.some(x=>x.effect===effect.effect));const below=rollDrinkEffects(id(id15.b,id15.q),()=>.149999);assert(below.some(x=>x.effect===effect.effect));});
