/** Event/adapter integration with local test doubles, NOT Bedrock engine acceptance. */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {world,system,startup,Player,ItemStack,Container,GameMode,BlockPermutation} from './fake-server.js';
import {ui} from './fake-ui.js';
import {book,runtimeRegistry,diagnosticSnapshot} from '../runtime/BP/scripts/main.js';
import {NS,BARE} from '../runtime/BP/scripts/core/cultivation.js';
import {FARM_IDS,framePermutation,refreshFrame,refreshAround,growthChanges,grow,maintain,farmUse,farmBreak} from '../runtime/BP/scripts/bedrock/cultivation.js';
import {placeBottle,takeBottles,BOTTLE_TEST,DISPLAY_IDS} from '../runtime/BP/scripts/bedrock/bottles.js';
import {BottleStore,bottleKey} from '../runtime/BP/scripts/core/bottles.js';
import {consumeDrink,effectDiagnostics} from '../runtime/BP/scripts/bedrock/drink-effects.js';
import {initializeTub,createBarrel,operate,press,tickBarrel,TEST_ACCESS} from '../runtime/BP/scripts/bedrock/machines.js';
import {machineKey} from '../runtime/BP/scripts/core/storage.js';
import {guideEntries,searchEntries} from '../runtime/BP/scripts/core/guide.js';
const regs=startup();system.advance(2);const dim=world.getDimension('overworld');let n=0;
const target=()=>({x:(++n)*20,y:64,z:0});
const player=()=>new Player('c2-'+(++n),dim);
const h=(p,id,count=1)=>{p.selectedSlotIndex=0;p.inventory.setItem(0,id?new ItemStack(id,count):undefined);};
const code=(f,c)=>assert.throws(f,e=>e.code===c);
const seq=(...a)=>()=>{assert(a.length,'Unexpected RNG');return a.shift();};
const count=(p,id)=>Array.from({length:p.inventory.size},(_,i)=>p.inventory.getItem(i)).filter(x=>x?.typeId===id).reduce((a,x)=>a+x.amount,0);
const beneath=(p)=>({x:p.x,y:p.y-1,z:p.z});
const above=(p)=>({x:p.x,y:p.y+1,z:p.z});
function frame({kind='bare',age=0,shape='single',wax=false,soil='minecraft:dirt'}={}){const loc=target(),b=dim.getBlock(loc);b.setPermutation(framePermutation(kind==='bare'?BARE:`${NS}:${kind}vine_trellis`,shape,age,wax));if(soil)dim.getBlock(beneath(loc)).setType(soil);return b;}
function crop(kind='grape',age=5){const loc=target(),b=dim.getBlock(loc);b.setPermutation(BlockPermutation.resolve(`${NS}:${kind}_crop`,{[NS+':age']:age}));dim.getBlock(above(loc)).setPermutation(framePermutation(`${NS}:${kind}vine_trellis`,'east_west',3));return b;}
function site(){const pos=target();dim.getBlock(beneath(pos)).setType('minecraft:stone');return pos;}
function bottle(p,q=3,base='wine',pos=site()){h(p,`${NS}:${base}_q${q}`);placeBottle(p,pos);return dim.getBlock(pos);}
const state=b=>BOTTLE_TEST.store.load(bottleKey(b.dimension.id,b.location));
function click(p,b,face='Up'){const e={player:p,block:b,blockFace:face,isFirstEvent:true,cancel:false};world.beforeEvents.playerInteractWithBlock.emit(e);return e;}
function fillInventory(p,exceptHand=true){for(let i=exceptHand?1:0;i<p.inventory.size;i++)p.inventory.setItem(i,new ItemStack('minecraft:stone',64));}

test('startup registers7 block and4 item components without any Cookery overrides',()=>{assert.equal(regs.blocks.size,7);assert.equal(regs.items.size,4);assert(regs.blocks.has(NS+':trellis'));assert(regs.items.has(NS+':drink_effects'));assert.equal(runtimeRegistry().allRecipes().length,29);});
test('all three soil species actually plant consuming one grapevine, not the stack',()=>{for(const[soil,kind]of[['minecraft:dirt','grape'],['minecraft:ice','ice_grape'],['minecraft:netherrack','gold_grape']]){const b=frame({soil}),p=player();h(p,NS+':grapevine',6);farmUse(p,b);assert.equal(b.typeId,`${NS}:${kind}vine_trellis`);assert.equal(b.permutation.getState(NS+':age'),0);assert.equal(count(p,NS+':grapevine'),5);}});
test('bad soil and waxed frame reject planting without consuming material',()=>{for(const opts of [{soil:'minecraft:stone'},{wax:true}]){const b=frame(opts),p=player();h(p,NS+':grapevine',2);code(()=>farmUse(p,b),opts.wax?'WAXED_TRELLIS':'UNSUITABLE_SOIL');assert.equal(b.typeId,BARE);assert.equal(count(p,NS+':grapevine'),2);}});
test('named grapevine or bone meal is not stripped into a raw item',()=>{const b=frame(),p=player();h(p,NS+':grapevine');const x=p.inventory.getItem(0);x.nameTag='Do not lose me';p.inventory.setItem(0,x);code(()=>farmUse(p,b),'METADATA_ITEM_REJECTED');assert.equal(p.inventory.getItem(0).nameTag,x.nameTag);});
test('wax and axe unwax change only requested state, preserving named tool and durability',()=>{const b=frame(),p=player();h(p,'minecraft:honeycomb',3);farmUse(p,b);assert(b.permutation.getState(NS+':waxed'));assert.equal(count(p,'minecraft:honeycomb'),2);h(p,'minecraft:wooden_axe');const axe=p.inventory.getItem(0);axe.nameTag='Custom axe';p.inventory.setItem(0,axe);farmUse(p,b,{rng:()=>0});assert.equal(b.permutation.getState(NS+':waxed'),false);assert.equal(p.inventory.getItem(0).nameTag,'Custom axe');assert.equal(p.inventory.getItem(0).getComponent('minecraft:durability').damage,1);});
test('native trellis placement against a frame is NOT intercepted as inspection',()=>{const b=frame(),p=player();h(p,BARE,5);const e=click(p,b,'East');assert.equal(e.cancel,false);assert.equal(count(p,BARE),5);});
test('onPlace source face changes bare frame axis and connects existing neighbors',()=>{const b=frame();b.setPermutation(b.permutation.withState('minecraft:block_face','east'));regs.blocks.get(NS+':trellis').onPlace({block:b});assert.equal(b.permutation.getState(NS+':shape'),'east_west');const upper=dim.getBlock(above(b.location));upper.setPermutation(framePermutation(BARE));refreshAround(upper);assert.equal(b.permutation.getState(NS+':shape'),'cross_east_west');});
test('three bone meals advance a standalone vine0 to3 using individual items',()=>{const b=frame({kind:'grape'}),p=player();h(p,'minecraft:bone_meal',8);for(let i=0;i<3;i++)farmUse(p,b);assert.equal(b.permutation.getState(NS+':age'),3);assert.equal(count(p,'minecraft:bone_meal'),5);});
test('a non-single young vine matures in one accepted growth',()=>{const b=frame({kind:'ice_grape',shape:'east_west',age:0});assert(grow(b,{force:true}));assert.equal(b.permutation.getState(NS+':age'),3);});
test('mature spread prioritizes up before east then west and sideways starts ripe',()=>{const b=frame({kind:'grape',age:3});const up=dim.getBlock(above(b.location));up.setPermutation(framePermutation(BARE));const east=dim.getBlock({x:b.location.x+1,y:64,z:0});east.setPermutation(framePermutation(BARE));assert(grow(b,{force:true}));assert.equal(up.typeId,NS+':grapevine_trellis');assert.equal(up.permutation.getState(NS+':age'),0);assert.equal(east.typeId,BARE);assert(grow(b,{force:true}));assert.equal(east.typeId,NS+':grapevine_trellis');assert.equal(east.permutation.getState(NS+':age'),3);});
test('waxed spread target is skipped and fruit appears only below free mature frame',()=>{const b=frame({kind:'gold_grape',age:3,soil:null});const upper=dim.getBlock(above(b.location));upper.setPermutation(framePermutation(BARE,'single',0,true));assert(grow(b,{force:true}));assert.equal(upper.typeId,BARE);assert.equal(dim.getBlock(beneath(b.location)).typeId,NS+':gold_grape_crop');});
test('unloaded priority neighbor postpones growth and preserves all blocks',()=>{const b=frame({kind:'grape',age:3,soil:null});const p=above(b.location),k=`${p.x}_${p.y}_${p.z}`;dim.unloaded.add(k);assert.equal(grow(b,{force:true}),false);assert(dim.getBlock(beneath(b.location)).isAir);dim.unloaded.delete(k);assert(grow(b,{force:true}));});
test('no growth room and ripe fruit do not consume bone meal',()=>{const b=frame({kind:'grape',age:3}),p=player();h(p,'minecraft:bone_meal',5);code(()=>farmUse(p,b),'NO_GROWTH_SPACE');assert.equal(count(p,'minecraft:bone_meal'),5);const c=crop();code(()=>farmUse(p,c),'NO_GROWTH_SPACE');assert.equal(count(p,'minecraft:bone_meal'),5);});
test('random tick callback observes explicit0.25 baseline; does not grow on rejected roll',()=>{const b=frame({kind:'ice_grape'});assert.equal(grow(b,{rng:()=>.25}),false);assert.equal(b.permutation.getState(NS+':age'),0);assert(grow(b,{rng:()=>.249}));assert.equal(b.permutation.getState(NS+':age'),1);});
test('fruit grows1–2 levels capped5 and does not grow without mature support',()=>{const c=crop('grape',3);assert(grow(c,{force:true,rng:()=>.99}));assert.equal(c.permutation.getState(NS+':age'),5);const c2=crop('grape',1);dim.getBlock(above(c2.location)).setType('minecraft:air');assert.equal(grow(c2,{force:true}),false);});
test('support loss clears fruit but unloaded support defers cleanup',()=>{const c=crop(),p=above(c.location),k=`${p.x}_${p.y}_${p.z}`;dim.unloaded.add(k);maintain(c);assert.equal(c.typeId,NS+':grape_crop');dim.unloaded.delete(k);dim.getBlock(p).setType('minecraft:air');maintain(c);assert(c.isAir);});
test('shears harvest3 species and2 green on source rolls while preserving custom tool data',()=>{const c=crop('ice_grape'),p=player();h(p,'minecraft:shears');const shears=p.inventory.getItem(0);shears.nameTag='Garden tool';shears.meta.lore=['keep'];p.inventory.setItem(0,shears);farmUse(p,c,{rng:seq(.1,.99,0)});assert(c.isAir);assert.equal(count(p,NS+':ice_grape'),3);assert.equal(count(p,NS+':green_grape'),2);assert.equal(p.inventory.getItem(0).nameTag,'Garden tool');assert.deepEqual(p.inventory.getItem(0).getLore(),['keep']);assert.equal(p.inventory.getItem(0).getComponent('minecraft:durability').damage,1);});
test('full inventory cancels harvest, retains ripe fruit and causes no tool wear',()=>{const c=crop(),p=player();h(p,'minecraft:shears');fillInventory(p);code(()=>farmUse(p,c,{rng:()=>.9}),'INVENTORY_FULL');assert.equal(c.typeId,NS+':grape_crop');assert.equal(c.permutation.getState(NS+':age'),5);assert.equal(p.inventory.getItem(0).getComponent('minecraft:durability').damage,0);});
test('Unbreaking can prevent wear; tool breaks exactly on final durability use',()=>{const c=crop(),p=player();h(p,'minecraft:shears');let s=p.inventory.getItem(0);s.meta.enchantments=[{type:{id:'unbreaking'},level:3}];p.inventory.setItem(0,s);farmUse(p,c,{rng:seq(.9,.9)});assert.equal(p.inventory.getItem(0).getComponent('minecraft:durability').damage,0);const c2=crop();s=p.inventory.getItem(0);s.meta.enchantments=[];s.getComponent('minecraft:durability').damage=237;p.inventory.setItem(0,s);farmUse(p,c2,{rng:seq(.9,0)});assert.equal(count(p,'minecraft:shears'),0);assert.equal(count(p,NS+':grape'),6);});
test('pruning returns vine and bare frame while removing unsupported child fruit without duplicate loot',()=>{const c=crop(),b=dim.getBlock(above(c.location)),p=player();h(p,'minecraft:shears');farmUse(p,b,{rng:()=>0});assert.equal(b.typeId,BARE);assert(c.isAir);assert.equal(count(p,NS+':grapevine'),1);assert.equal(count(p,NS+':grape'),0);});
test('normal breaking ripe crop follows smaller source loot; immature breaking returns nothing',()=>{const p=player(),c=crop();farmBreak(p,c,{rng:seq(.99,.1)});assert.equal(count(p,NS+':grape'),2);assert.equal(count(p,NS+':green_grape'),1);const d=crop('gold_grape',4);farmBreak(p,d);assert.equal(count(p,NS+':gold_grape'),0);});
test('block-write failure rolls planting inventory back and keeps bare frame',()=>{const b=frame(),p=player();h(p,NS+':grapevine',3);b.failSet=true;assert.throws(()=>farmUse(p,b),/INJECTED_BLOCK_FAILURE/);assert.equal(count(p,NS+':grapevine'),3);assert.equal(b.typeId,BARE);});
test('two player harvest events in one tick award only one crop',()=>{const c=crop(),p=player(),q=player();h(p,'minecraft:shears');h(q,'minecraft:shears');click(p,c);click(q,c);system.advance();assert.equal(count(p,NS+':grape')+count(q,NS+':grape'),3);assert.equal(p.inventory.getItem(0).getComponent('minecraft:durability').damage+q.inventory.getItem(0).getComponent('minecraft:durability').damage,1);});
test('changed held stack and dimension cancel deferred plant use',()=>{const b=frame(),p=player();h(p,NS+':grapevine',3);click(p,b);h(p,NS+':grapevine',2);system.advance();assert.equal(b.typeId,BARE);click(p,b);p.dimension=world.getDimension('nether');system.advance();assert.equal(b.typeId,BARE);});
test('display actual placement consumes exactly one even from a16-stack',()=>{const p=player(),pos=site();h(p,NS+':wine_q3',16);placeBottle(p,pos);assert.equal(count(p,NS+':wine_q3'),15);const b=dim.getBlock(pos);assert.equal(b.typeId,NS+':bottle_wine');assert.deepEqual(state(b).items,[NS+':wine_q3']);});
test('display routes sneak top-face placement, then mixes qualities without averaging',()=>{const p=player(),pos=site(),support=dim.getBlock(beneath(pos));h(p,NS+':wine_q1',2);p.isSneaking=true;assert(click(p,support).cancel);system.advance();const b=dim.getBlock(pos);h(p,NS+':wine_q6');p.isSneaking=false;click(p,b);system.advance();assert.deepEqual(state(b).items,[NS+':wine_q1',NS+':wine_q6']);h(p,undefined);click(p,b);system.advance();assert.equal(count(p,NS+':wine_q6'),1);assert.deepEqual(state(b).items,[NS+':wine_q1']);});
test('display break returns all exact qualities, destroys block and removes own state',()=>{const p=player(),b=bottle(p,1);for(const q of[6,3]){h(p,`${NS}:wine_q${q}`);placeBottle(p,b.location);}h(p,undefined);takeBottles(p,b,{all:true});assert(b.isAir);assert.equal(state(b),undefined);for(const q of[1,6,3])assert.equal(count(p,`${NS}:wine_q${q}`),1);});
test('three-cap overflow and different drink reject before input is consumed',()=>{const p=player(),b=bottle(p,1,'brandy');for(let q=2;q<=3;q++){h(p,`${NS}:brandy_q${q}`);placeBottle(p,b.location);}h(p,NS+':brandy_q6',2);code(()=>placeBottle(p,b.location),'BOTTLE_CAPACITY');assert.equal(count(p,NS+':brandy_q6'),2);h(p,NS+':wine_q6',2);code(()=>placeBottle(p,b.location),'DIFFERENT_DRINK');assert.equal(count(p,NS+':wine_q6'),2);});
test('unsupported, occupied and unloaded placement never consumes bottle',()=>{const p=player(),pos=target();h(p,NS+':wine_q3',2);code(()=>placeBottle(p,pos),'NEEDS_SOLID_SUPPORT');dim.getBlock(beneath(pos)).setType('minecraft:stone');dim.getBlock(pos).setType('minecraft:stone');code(()=>placeBottle(p,pos),'SPACE_NOT_CLEAR');const k=`${pos.x}_${pos.y}_${pos.z}`;dim.unloaded.add(k);code(()=>placeBottle(p,pos),'UNLOADED_TARGET');dim.unloaded.delete(k);assert.equal(count(p,NS+':wine_q3'),2);});
test('full inventory aborts display retrieval, keeping content and permutation intact',()=>{const p=player(),b=bottle(p,6);fillInventory(p,false);const before=JSON.stringify(state(b));code(()=>takeBottles(p,b,{all:true}),'INVENTORY_FULL');assert.equal(JSON.stringify(state(b)),before);assert.equal(b.typeId,NS+':bottle_wine');});
test('failed bottle-state save rolls back input and world permutation',()=>{const p=player(),pos=site();h(p,NS+':wine_q3',2);world.failSet=true;assert.throws(()=>placeBottle(p,pos),/INJECTED_SAVE_FAILURE/);assert.equal(count(p,NS+':wine_q3'),2);assert(dim.getBlock(pos).isAir);assert.equal(state(dim.getBlock(pos)),undefined);});
test('failed removal save restores bottle content, block and received inventory',()=>{const p=player(),b=bottle(p,4);h(p,undefined);const before=JSON.stringify(state(b));world.failSet=true;assert.throws(()=>takeBottles(p,b),/INJECTED_SAVE_FAILURE/);assert.equal(count(p,NS+':wine_q4'),0);assert.equal(JSON.stringify(state(b)),before);assert.equal(b.typeId,NS+':bottle_wine');});
test('fresh bottle store reloads exact mixed qualities without recomputing recipe',()=>{const p=player(),b=bottle(p,2);h(p,NS+':wine_q5');placeBottle(p,b.location);const fresh=new BottleStore(world);assert.deepEqual(fresh.load(bottleKey(dim.id,b.location)).items,[NS+':wine_q2',NS+':wine_q5']);});
test('same-tick two players cannot take or append the same display revision twice',()=>{const owner=player(),b=bottle(owner,5),p=player(),q=player();click(p,b);click(q,b);system.advance();assert.equal(count(p,NS+':wine_q5')+count(q,NS+':wine_q5'),1);const next=bottle(owner,1);h(p,NS+':wine_q3',2);h(q,NS+':wine_q3',2);click(p,next);click(q,next);system.advance();assert.equal(state(next).items.length,2);assert.equal(count(p,NS+':wine_q3')+count(q,NS+':wine_q3'),3);});
test('creative display roundtrip conserves real bottle inventory',()=>{const p=new Player('creative-'+(++n),dim,GameMode.Creative),pos=site();h(p,NS+':wine_q6',8);placeBottle(p,pos);assert.equal(count(p,NS+':wine_q6'),7);takeBottles(p,dim.getBlock(pos));assert.equal(count(p,NS+':wine_q6'),8);});
test('named quality bottle is not reduced to plain-ID display state',()=>{const p=player(),pos=site();h(p,NS+':wine_q3');const x=p.inventory.getItem(0);x.nameTag='Gift';p.inventory.setItem(0,x);code(()=>placeBottle(p,pos),'METADATA_ITEM_REJECTED');assert.equal(p.inventory.getItem(0).nameTag,'Gift');assert(dim.getBlock(pos).isAir);});
test('externally mismatched display is kept for recovery, not refunded as invented contents',()=>{const p=player(),b=bottle(p,4),raw=JSON.stringify(state(b));b.setType('minecraft:stone');code(()=>takeBottles(p,b),'DISPLAY_MISMATCH');assert.equal(JSON.stringify(state(b)),raw);assert.equal(count(p,NS+':wine_q4'),0);});
test('removing support does not silently delete contents and empty-hand take remains possible',()=>{const p=player(),b=bottle(p,4);dim.getBlock(beneath(b.location)).setType('minecraft:air');takeBottles(p,b);assert.equal(count(p,NS+':wine_q4'),1);assert(b.isAir);});
test('adventure and spectator modes cannot exchange cultivated or placed items',()=>{for(const mode of [GameMode.Adventure,GameMode.Spectator]){const p=new Player('locked-'+(++n),dim,mode),b=frame();h(p,NS+':grapevine');code(()=>farmUse(p,b),'GAME_MODE_LOCKED');h(p,NS+':wine_q3');code(()=>placeBottle(p,site()),'GAME_MODE_LOCKED');}});
test('protection filters compose with C1 machines and leave unrelated blocks impacted',()=>{const farm=crop(),p=player(),display=bottle(p),stone=dim.getBlock(target());stone.setType('minecraft:stone');let impacted=[farm,display,stone];world.beforeEvents.explosion.emit({getImpactedBlocks:()=>impacted,setImpactedBlocks:x=>impacted=x});assert.deepEqual(impacted,[stone]);});
test('Q1 consumption applies600tick nausea but never changes the post-consume inventory itself',()=>{const p=player();h(p,NS+':wine_q1',15);p.inventory.setItem(1,new ItemStack(NS+':empty_bottle'));const before=JSON.stringify(p.inventory.items);const out=consumeDrink({source:p,itemStack:new ItemStack(NS+':wine_q1')},()=>0);assert.equal(out[0].status,'APPLIED');assert.deepEqual(p.effects,[{id:'nausea',ticks:600,amplifier:0,showParticles:true}]);assert.equal(JSON.stringify(p.inventory.items),before);});
test('native regeneration gets source duration and custom tipsy is explicitly unsupported',()=>{const p=player(),out=consumeDrink({source:p,itemStack:new ItemStack(NS+':wine_q6')},()=>0);assert.equal(out.find(x=>x.effect===NS+':slightly_tipsy').status,'UNIMPLEMENTED_CUSTOM_EFFECT');assert.deepEqual(p.effects,[{id:'regeneration',ticks:10800,amplifier:1,showParticles:true}]);assert(effectDiagnostics.unsupported[NS+':slightly_tipsy']>0);});
test('onConsume registration has no onUse effect shortcut; engine errors are bounded diagnostics',()=>{const c=regs.items.get(NS+':drink_effects');assert.equal(typeof c.onConsume,'function');assert.equal(c.onUse,undefined);const p=player();p.failEffect=true;for(let i=0;i<20;i++)consumeDrink({source:p,itemStack:new ItemStack(NS+':wine_q1')},()=>0);assert.equal(effectDiagnostics.errors.length,16);assert.equal(p.effects.length,0);});
test('independent guide contains cultivation, bottle handling and24 effect tables, without Cookery writes',async()=>{const p=player();p.setDynamicProperty('kc:guidebook_language','en_US');const entries=guideEntries(runtimeRegistry(),'zh_TW');assert(entries.some(x=>x.id===NS+':cultivation'));assert.equal(entries.filter(x=>x.id.startsWith(NS+':effects/')).length,24);assert(searchEntries(entries,'Q6').length>=24);ui.forms=[];ui.responses=[];await book(p);assert.match(ui.forms[0].content,/C2/);assert.equal(p.getDynamicProperty('kc:guidebook_language'),'en_US');assert.equal(diagnosticSnapshot().bottlePlacement,true);});
test('end-to-end adapters: cultivate33 grapes, press4 buckets, brew, place and return original quality, then effect hook',()=>{
 const p=player(),vine=frame({kind:'grape',age:3,shape:'east_west',soil:null});
 h(p,'minecraft:shears');
 for(let i=0;i<11;i++){
  assert(grow(vine,{force:true}));const fruit=dim.getBlock(beneath(vine.location));
  while(fruit.permutation.getState(NS+':age')<5)assert(grow(fruit,{force:true,rng:()=>.99}));
  farmUse(p,fruit,{rng:()=>.9});
 }
 assert.equal(count(p,NS+':grape'),33);
 const tub=dim.getBlock(target());tub.setType(NS+':pressing_tub');initializeTub(tub);
 p.selectedSlotIndex=p.inventory.items.findIndex(x=>x?.typeId===NS+':grape');operate(p,tub,'use');
 // Give only the empty containers/machine installation inputs; all fruit comes from the cultivation adapter.
 h(p,'minecraft:bucket',16);
 const barrelPos=target(),builder=player();h(builder,NS+':barrel');createBarrel(builder,barrelPos);const barrel=dim.getBlock(barrelPos);
 for(let k=0;k<4;k++){
  for(let j=0;j<8;j++)press(tub,p,1);
  p.selectedSlotIndex=p.inventory.items.findIndex(x=>x?.typeId==='minecraft:bucket');operate(p,tub,'use');
  p.selectedSlotIndex=p.inventory.items.findIndex(x=>x?.typeId===NS+':grape_bucket');operate(p,barrel,'use');
 }
 assert.equal(count(p,'minecraft:bucket'),16);operate(p,barrel,'lid');tickBarrel(barrel);
 for(let i=0;i<27;i++)tickBarrel(barrel);
 const batch=TEST_ACCESS.store.load(machineKey(dim.id,barrelPos)).batch;assert(batch.quality>=2);
 h(p,NS+':empty_bottle',16);operate(p,barrel,'extract');
 const drink=p.inventory.items.find(x=>x?.typeId?.startsWith(NS+':wine_q'));assert(drink);const original=drink.typeId;
 p.selectedSlotIndex=p.inventory.items.findIndex(x=>x?.typeId===original);const pos=site();placeBottle(p,pos);takeBottles(p,dim.getBlock(pos));
 assert.equal(count(p,original),1);consumeDrink({source:p,itemStack:new ItemStack(original)},()=>0);
 assert.equal(count(p,original),1); // hook intentionally does not model or repeat native consumption
});

test('tagged custom top surface supports a bottle without touching pre-release isSolid',()=>{const p=player(),pos=target(),support=dim.getBlock(beneath(pos));support.setType('foreign:table');support.tags=['kaleidoscope_tavern:bottle_support'];h(p,NS+':wine_q3');placeBottle(p,pos);assert.equal(state(dim.getBlock(pos)).items[0],NS+':wine_q3');});

test('already-cancelled third-party interact/break events are respected for crops and bottle displays',()=>{const p=player(),b=frame();h(p,NS+':grapevine',3);world.beforeEvents.playerInteractWithBlock.emit({player:p,block:b,blockFace:'Up',isFirstEvent:true,cancel:true});system.advance();assert.equal(b.typeId,BARE);assert.equal(count(p,NS+':grapevine'),3);const display=bottle(p,6);h(p,undefined);world.beforeEvents.playerBreakBlock.emit({player:p,block:display,cancel:true});system.advance();assert.equal(state(display).items.length,1);assert.equal(count(p,NS+':wine_q6'),0);});
