import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {emptyShaker,addInput,removeInput,finishShake,serveShaker,timingBand,signaturePayload,mergeEffects,validateShaker,validatePayload,validateCup,MixStore,shakerKey,cupKey,SIGNATURE,EMPTY_CUP,MYSTERY,inputSnapshot} from '../runtime/BP/scripts/core/mixology.js';
import {ExtensionRegistry,matchIngredients,CAPABILITIES} from '../runtime/BP/scripts/core/registry.js';
import {SHAKER_INPUTS,SHAKER_RECIPES,COCKTAILS} from '../runtime/BP/scripts/data/mixology.js';
import {BUILTIN_RECIPES} from '../runtime/BP/scripts/data/recipes.js';
import {FLUIDS} from '../runtime/BP/scripts/data/fluids.js';
import {guideEntries,recipePage,searchEntries} from '../runtime/BP/scripts/core/guide.js';
const N='kaleidoscope_tavern';const code=(f,c)=>assert.throws(f,e=>e.code===c);
const reg=()=>new ExtensionRegistry({recipes:[...BUILTIN_RECIPES,...SHAKER_RECIPES],fluids:FLUIDS});
function full(ids=[N+':wine_q4',N+':wine_q5',N+':wine_q6']){let s=emptyShaker();for(const id of ids)s=addInput(s,id,reg());return s;}
const ext=()=>({api:1,source:'mix_demo',version:'1.0.0',recipes:[{id:'mix_demo:test',kind:'shaker',ingredients:[['minecraft:apple'],['minecraft:sugar'],['minecraft:glow_berries']],output:{item:N+':mojito'}}],pages:[{id:'mix_demo:guide',title:{zh_TW:'示範調酒'},body:{zh_TW:'獨立酒館附屬'},recipeIds:['mix_demo:test']}]});
class Props{constructor(){this.v=new Map();}getDynamicProperty(k){return this.v.get(k);}setDynamicProperty(k,v){v===undefined?this.v.delete(k):this.v.set(k,v);}}
test('all twelve source fixed recipes,14 cocktail artworks and69 qualified input IDs exist',()=>{assert.equal(SHAKER_RECIPES.length,12);assert.equal(Object.keys(COCKTAILS).length,14);assert.equal(Object.keys(SHAKER_INPUTS).length,69);assert(SHAKER_RECIPES.every(r=>r.ingredients.length===3&&r.ingredients.every(s=>s.every(id=>SHAKER_INPUTS[id]))));assert(CAPABILITIES.includes('shaker_recipes'));});
test('all timing values0..250 match source boundary bands, not a common off-by-one table',()=>{for(let t=0;t<=250;t++)assert.equal(timingBand(t),t<=18?'abort':t<=68?'mystery':t<=88?'signature':t<=98?'recipe':'mystery');for(const t of [-1,NaN,Infinity,1.5])assert.throws(()=>timingBand(t));});
test('under19 ticks preserves all three poured quality IDs and revision',()=>{const s=full(),r=reg().findShaker(s.slots);assert.deepEqual(finishShake(s,18,r),s);});
test('early and overlong shake are mystery; middle window is signature',()=>{const s=full(),r=reg().findShaker(s.slots);for(const t of [19,68,99,111])assert.equal(finishShake(s,t,r).result.item,MYSTERY);for(const t of [69,88])assert.equal(finishShake(s,t,r).result.item,SIGNATURE);});
test('every one of the twelve fixed recipes can be matched at ticks89 and98 with all slot permutations',()=>{const r=reg();for(const recipe of SHAKER_RECIPES){const a=recipe.ingredients.map(s=>s[0]);for(const perm of [[0,1,2],[2,1,0],[1,0,2],[1,2,0],[2,0,1],[0,2,1]]){const s=full(perm.map(i=>a[i]));assert.equal(r.findShaker(s.slots).id,recipe.id);for(const t of [89,98])assert.equal(finishShake(s,t,r.findShaker(s.slots)).result.item,recipe.output.item);}}});
test('perfect timing without fixed match makes Signature, never missing-output state',()=>{const s=full([N+':wine_q4',N+':vodka_q4',N+':honey_wine_q4']);assert.equal(reg().findShaker(s.slots),undefined);assert.equal(finishShake(s,94,undefined).result.item,SIGNATURE);});
test('Q1–Q3 reject for all23 base wines before slots change',()=>{for(const item of Object.keys(SHAKER_INPUTS).filter(x=>x.endsWith('_q4'))){for(let q=1;q<4;q++){const s=emptyShaker();code(()=>addInput(s,item.replace('_q4','_q'+q),reg()),'QUALITY_TOO_LOW');assert.equal(s.slots.length,0);}}});
test('all Q4–Q6 inputs preserve their own effects, container and exact ID',()=>{for(const[id,known]of Object.entries(SHAKER_INPUTS)){const s=addInput(emptyShaker(),id,reg());assert.deepEqual(s.slots[0],known);assert.equal(s.slots[0].container,N+':empty_bottle');}});
test('fourth input, empty removal and re-shaking ready result are rejected',()=>{code(()=>addInput(full(),N+':wine_q4',reg()),'SHAKER_FULL');code(()=>removeInput(emptyShaker()),'NO_INGREDIENT');const ready=finishShake(full(),70);code(()=>finishShake(ready,95),'RESULT_PENDING');code(()=>removeInput(ready),'RESULT_PENDING');});
test('partial unpour preserves original quality and specifies the container owed back',()=>{const tx=removeInput(full());assert.equal(tx.input.item,N+':wine_q6');assert.equal(tx.input.container,N+':empty_bottle');assert.equal(tx.state.slots.length,2);});
test('all vanilla potion IDs reject rather than erasing their effect payload',()=>{for(const id of ['minecraft:potion','minecraft:splash_potion','minecraft:lingering_potion'])code(()=>inputSnapshot(id,reg()),'POTION_DATA_NOT_ADAPTED');});
test('Signature uses quality-specific snapshots rather than latest config or an average quality',()=>{const s=full(),saved=structuredClone(s);const payload=signaturePayload(s.slots);assert.deepEqual(payload.ingredients,[N+':wine_q4',N+':wine_q5',N+':wine_q6']);assert.deepEqual(s,saved);assert.deepEqual(payload.effects,mergeEffects(s.slots.flatMap(x=>x.effects)));});
test('merge uses max amplifier/probability and1.2f even for singleton effects',()=>{const e=[{effect:'minecraft:speed',duration:101,amplifier:0,probability:.3},{effect:'minecraft:speed',duration:99,amplifier:2,probability:.7},{effect:'minecraft:strength',duration:3,amplifier:1,probability:1}];assert.deepEqual(mergeEffects(e),[{effect:'minecraft:speed',duration:240,amplifier:2,probability:.7},{effect:'minecraft:strength',duration:3,amplifier:1,probability:1}]);});
test('float32 duration multiplication matches independent expected numeric boundary samples',()=>{for(const seconds of [0,1,3,101,540,2700,100000]){const actual=mergeEffects([{effect:'minecraft:speed',duration:seconds,amplifier:0,probability:1}])[0].duration;const f=new Float32Array(1);f[0]=1.2;f[0]=f[0]*seconds;assert.equal(actual,Math.trunc(f[0]));}});
test('colour channels are truncated arithmetic means of original format colours',()=>{const s=full([N+':wine_q4',N+':vodka_q4',N+':ice_wine_q4']);assert.equal(signaturePayload(s.slots).color,0xc68dff);});
test('mutating returned signature does not modify machine input snapshots',()=>{const s=full(),r=finishShake(s,80);r.result.payload.ingredients[0]='evil:test';assert.equal(s.slots[0].item,N+':wine_q4');});
test('serve clears all logical contents exactly once and preserves result data',()=>{const ready=finishShake(full(),80),out=serveShaker(ready);assert.equal(out.state.slots.length,0);assert.equal(out.state.result,null);assert.equal(out.result.item,SIGNATURE);code(()=>serveShaker(out.state),'NOT_READY');assert.equal(ready.slots.length,3);});
test('shaker and cup keys cannot collide across dimensions,negative coordinates or each other',()=>{const p={x:-1,y:64,z:-3};assert.notEqual(shakerKey('minecraft:overworld',p),cupKey('minecraft:overworld',p));assert.notEqual(shakerKey('minecraft:overworld',p),shakerKey('minecraft:nether',p));assert.throws(()=>cupKey('evil/../x',p));assert.throws(()=>shakerKey('minecraft:overworld',{x:.5,y:0,z:0}));});
test('independent store reload preserves ready payload and rejects stale revisions',()=>{const b=new Props(),a=new MixStore(b,validateShaker),key='t';a.save(key,full(),-1);const fresh=new MixStore(b,validateShaker);assert.deepEqual(fresh.load(key),full());code(()=>fresh.save(key,emptyShaker(),-1),'STATE_CONFLICT');assert.equal(fresh.load(key).slots.length,3);});
test('invalid future schema never resets existing data',()=>{const b=new Props();b.setDynamicProperty('t',JSON.stringify({...full(),schema:99}));const a=new MixStore(b,validateShaker);code(()=>a.load('t'),'SHAKER_SCHEMA');assert(b.getDynamicProperty('t').includes('99'));});
test('oversized or malicious signature fields are rejected',()=>{const p=signaturePayload(full().slots);for(const bad of [{...p,color:-1},{...p,color:0x1000000},{...p,ingredients:[]},{...p,effects:Array(65).fill(p.effects[0])},{...p,effects:[{effect:'minecraft:speed',duration:NaN,amplifier:0,probability:1}]}])assert.throws(()=>validatePayload(bad));});
test('fixed cups may not carry arbitrary signature data',()=>{code(()=>validateCup({schema:1,revision:0,facing:0,item:N+':mojito',payload:signaturePayload(full().slots)}),'UNEXPECTED_PAYLOAD');});
test('extension shaker registration is atomic and appears in the same guide registry',()=>{const r=reg();r.install(ext());assert.equal(r.allRecipes().length,42);const pages=guideEntries(r,'zh_TW');assert(searchEntries(pages,'示範調酒').length);const page=recipePage(r.recipe('mix_demo:test'),'en_US');assert.match(page.body,/89–98/);assert.doesNotMatch(page.body,/4000|undefined/);});
test('invalid extension ingredient count rejects the whole replacement bundle',()=>{const r=reg();r.install(ext());const bad=ext();bad.recipes[0].ingredients.pop();code(()=>r.install(bad),'INVALID_SHAKER_SLOTS');assert.equal(r.recipe('mix_demo:test').ingredients.length,3);});
test('extension cannot request arbitrary Signature,undefined quality or raw potion outputs',()=>{for(const mutation of [p=>p.recipes[0].output={item:SIGNATURE},p=>p.recipes[0].output={byQuality:Array(6).fill(N+':mojito')},p=>p.recipes[0].ingredients[0]=['minecraft:potion'],p=>p.recipes[0].ingredients[0]=[N+':wine_q3']]){const p=ext();mutation(p);assert.throws(()=>reg().install(p));}});
test('unknown items and output carriers reject extension before registration',()=>{for(const bad of ['missing:result','missing:carrier']){const r=new ExtensionRegistry({fluids:FLUIDS,itemExists:i=>!i.startsWith('missing:')}),p=ext();if(bad.includes('result'))p.recipes[0].output.item=bad;else p.recipes[0].carrier=bad;code(()=>r.install(p),'UNKNOWN_ITEM');assert.equal(r.list().length,0);}});
test('alternative ingredient backtracking handles overlaps and repeated slots',()=>{assert(matchIngredients([['x:a','x:b'],['x:a'],['x:c']],[{id:'x:a'},{id:'x:b'},{id:'x:c'}]));assert(!matchIngredients([['x:a'],['x:a'],['x:c']],[{id:'x:a'},{id:'x:b'},{id:'x:c'}]));});
test('new plain extension ingredient snapshots have no invented effect or bottle return',()=>{const r=reg();r.install(ext());assert.deepEqual(inputSnapshot('minecraft:apple',r),{item:'minecraft:apple',container:null,color:0xffffff,effects:[]});});
test('fixed result snapshots survive extension replacement/removal',()=>{const r=reg();r.install(ext());let s=emptyShaker();for(const i of ['minecraft:apple','minecraft:sugar','minecraft:glow_berries'])s=addInput(s,i,r);const chosen=structuredClone(r.findShaker(s.slots));r.remove('mix_demo');const out=finishShake(s,95,chosen);assert.equal(out.result.item,N+':mojito');assert.equal(out.result.recipeId,'mix_demo:test');});
test('all fixed cocktail effect definitions are visibly custom,not substitute native buffs',()=>{assert(Object.values(COCKTAILS).flatMap(x=>x.effects).every(e=>e.effect.startsWith(N+':')));assert.equal(COCKTAILS[N+':emerald'].effects[0].effect,N+':long_reach');});
test('source recipes and tags are traceable to exact local copied JAR members',()=>{const lock=JSON.parse(fs.readFileSync(new URL('../data/upstream/c3/source.lock.json',import.meta.url)));assert.equal(lock.records.filter(x=>x.member.includes('/recipe/shaker/')).length,12);assert(lock.records.some(x=>x.member.endsWith('CocktailEffectHelper.class')));});

test('registration rejects unsupported vinegar quality inputs upfront rather than advertising an unusable recipe',()=>{const r=reg(),x=ext();x.recipes[0].ingredients[0]=[N+':vinegar_q4'];code(()=>r.install(x),'NOT_MIXABLE_DRINK');assert.equal(r.list().length,0);});

test('a signature cannot be accepted as a plain extension ingredient losing its dynamic payload',()=>{const x=ext();x.recipes[0].ingredients[0]=[SIGNATURE];code(()=>reg().install(x),'SIGNATURE_INPUT_NOT_ADAPTED');code(()=>inputSnapshot(SIGNATURE,{acceptsShakerInput:()=>true}),'SIGNATURE_INPUT_NOT_ADAPTED');});
