/** C3 actual adapters in Node mocks. Does not simulate native food consumption, graphics or Bedrock. */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {world,system,startup,Player,ItemStack,ItemTypes,Container,GameMode} from './fake-server.js';
import {runtimeRegistry,diagnosticSnapshot} from '../runtime/BP/scripts/main.js';
import {placeShaker,pourIngredient,unpourIngredient,breakShaker,startShake,stopShake,tickShakers,serveInHand,resultStack,placeCup,takeCup,pourIntoPlacedCup,syncCupVisual,consumeCocktail,pickupShaker,readPortableItem,MIX_TEST,mixologyDiagnostics} from '../runtime/BP/scripts/bedrock/mixology.js';
import {NS,EMPTY_CUP,SIGNATURE,SIGNATURE_DATA,shakerKey,cupKey,MixStore,validateShaker,validateCup} from '../runtime/BP/scripts/core/mixology.js';
import {SHAKER_RECIPES,COCKTAILS,SHAKER_INPUTS} from '../runtime/BP/scripts/data/mixology.js';
import {registerTavernExtension} from '../sdk/tavern-extension-client.js';
import {guideEntries,recipePage} from '../runtime/BP/scripts/core/guide.js';
import {planInventory,commitInventory} from '../runtime/BP/scripts/core/inventory.js';
const regs=startup();system.advance(2);const dim=world.getDimension('overworld');let index=0;
const registry=()=>runtimeRegistry();
const code=(fn,c)=>assert.throws(fn,e=>e.code===c);
const count=(p,id)=>p.inventory.items.filter(i=>i?.typeId===id).reduce((n,i)=>n+i.amount,0);
const dropCount=id=>[...dim.entities.values()].filter(e=>e.typeId==='minecraft:item'&&e.getComponent('minecraft:item')?.itemStack.typeId===id).reduce((n,e)=>n+e.getComponent('minecraft:item').itemStack.amount,0);
const h=(p,id,n=1)=>{p.selectedSlotIndex=0;p.inventory.setItem(0,id?new ItemStack(id,n):undefined);};
const pos=()=>({x:(++index)*20,y:64,z:0});
function site(d=dim,at=pos()){d.getBlock({...at,y:at.y-1}).setType('minecraft:stone');return at;}
function actor(at=pos(),d=dim,mode=GameMode.Survival){const p=new Player('c3-'+(++index),d,mode);p.location={x:at.x+.5,y:at.y+1,z:at.z+2};return p;}
function setup(){const at=site(),p=actor(at);h(p,NS+':shaker');placeShaker(p,at);return {p,b:dim.getBlock(at),at};}
const state=b=>MIX_TEST.shakerStore.load(shakerKey(b.dimension.id,b.location));
const cs=b=>MIX_TEST.cupStore.load(cupKey(b.dimension.id,b.location));
const full=(p,b,items=[NS+':vodka_q4',NS+':riesling_dry_white_q4',NS+':glowflower_brew_q4'])=>{for(const id of items){h(p,id);pourIngredient(p,b);}h(p,undefined);return b;};
const finish=(p,b,t=90)=>{h(p,undefined);startShake(p,b);return stopShake(p,b,{tick:system.currentTick+t});};
function cupNear(p,b,item=EMPTY_CUP,payload){const at=site(b.dimension,{...b.location,x:b.location.x+1});const stack=resultStack({item,payload});p.selectedSlotIndex=0;p.inventory.setItem(0,stack);placeCup(p,at);return b.dimension.getBlock(at);}
const fillBag=(p)=>{for(let i=1;i<p.inventory.size;i++)p.inventory.setItem(i,new ItemStack('minecraft:stone',64));};
function eventClick(p,b,{sneak=false,first=true,cancel=false,face='Up'}={}){p.isSneaking=sneak;const e={player:p,block:b,blockFace:face,isFirstEvent:first,cancel};world.beforeEvents.playerInteractWithBlock.emit(e);return e;}
test.beforeEach(()=>MIX_TEST.sessions.clear());

test('entrypoint advertises41 machine recipes and dedicated mixology components',()=>{assert.equal(registry().allRecipes().length,41);assert.equal(registry().allRecipes().filter(r=>r.kind==='shaker').length,12);assert(regs.blocks.has(NS+':shaker_station'));assert(regs.blocks.has(NS+':cocktail_cup'));assert.equal(typeof regs.items.get(NS+':cocktail_effects').onConsume,'function');});
test('shared break router makes an empty placed shaker a Survival drop with lantern/metal feedback',()=>{
 const {p,b}=setup(),before=dropCount(NS+':shaker'),sounds=dim.sounds?.filter(s=>s.id==='break.iron').length??0;h(p,undefined);
 const e={player:p,block:b,cancel:false};world.beforeEvents.playerBreakBlock.emit(e);system.advance();
 assert(e.cancel);assert(b.isAir);assert.equal(count(p,NS+':shaker'),0);assert.equal(dropCount(NS+':shaker'),before+1);assert.equal((dim.sounds??[]).filter(s=>s.id==='break.iron').length,sounds+1);
});
test('shared break router preserves placed glassware item identity and glass feedback',()=>{
 const at=site(),p=actor(at);h(p,EMPTY_CUP);placeCup(p,at);const b=dim.getBlock(at),before=dropCount(EMPTY_CUP),sounds=dim.sounds?.filter(s=>s.id==='random.glass').length??0;h(p,undefined);
 const e={player:p,block:b,cancel:false};world.beforeEvents.playerBreakBlock.emit(e);system.advance();
 assert(e.cancel);assert(b.isAir);assert.equal(count(p,EMPTY_CUP),0);assert.equal(dropCount(EMPTY_CUP),before+1);assert.equal((dim.sounds??[]).filter(s=>s.id==='random.glass').length,sounds+1);
});
test('shaker placement roundtrip consumes and returns the original one machine',()=>{const {p,b}=setup();assert.equal(count(p,NS+':shaker'),0);assert.equal(state(b).slots.length,0);breakShaker(p,b);assert(b.isAir);assert.equal(count(p,NS+':shaker'),1);assert.equal(state(b),undefined);});
test('Java ShakerBlock has no custom floor-support gate; occupied unloaded and distant placement still fail losslessly',()=>{const floating=pos(),p0=actor(floating);h(p0,NS+':shaker');assert.doesNotThrow(()=>placeShaker(p0,floating));assert.equal(dim.getBlock(floating).typeId,MIX_TEST.STATION);for(const kind of['occupied','unloaded','far']){const at=site(),p=actor(at);h(p,NS+':shaker');if(kind==='occupied')dim.getBlock(at).setType('minecraft:stone');if(kind==='unloaded')dim.unloaded.add(`${at.x}_${at.y}_${at.z}`);if(kind==='far')p.location.x+=10;code(()=>placeShaker(p,at),{occupied:'SPACE_NOT_CLEAR',unloaded:'UNLOADED_TARGET',far:'OUT_OF_REACH'}[kind]);assert.equal(count(p,NS+':shaker'),1);dim.unloaded.delete(`${at.x}_${at.y}_${at.z}`);}});
test('place with store exception restores air and original shaker',()=>{const at=site(),p=actor(at);h(p,NS+':shaker');world.failSet=true;assert.throws(()=>placeShaker(p,at),/INJECTED_SAVE/);assert(dim.getBlock(at).isAir);assert.equal(count(p,NS+':shaker'),1);});
test('one from a16 bottle stack is poured and exactly one empty bottle is returned',()=>{const {p,b}=setup();h(p,NS+':wine_q4',16);pourIngredient(p,b);assert.equal(count(p,NS+':wine_q4'),15);assert.equal(count(p,NS+':empty_bottle'),1);assert.equal(state(b).slots[0].item,NS+':wine_q4');});
test('all69 supported ingredient qualities run through actual input adapter',()=>{for(const id of Object.keys(SHAKER_INPUTS)){const {p,b}=setup();h(p,id,2);pourIngredient(p,b);assert.equal(state(b).slots[0].item,id);assert.equal(count(p,id),1);assert.equal(count(p,NS+':empty_bottle'),1);}});
test('Q1-Q3 and potion inputs fail without a refund or taking input',()=>{for(const id of[NS+':wine_q1',NS+':wine_q2',NS+':wine_q3','minecraft:potion']){const {p,b}=setup();h(p,id);code(()=>pourIngredient(p,b),id.startsWith('minecraft:')?'POTION_COMPONENT_UNAVAILABLE':'QUALITY_TOO_LOW');assert.equal(state(b).slots.length,0);assert.equal(count(p,id),1);assert.equal(count(p,NS+':empty_bottle'),0);}});
test('named input or additional item data is not silently erased',()=>{for(const mode of['name','lore']){const {p,b}=setup();h(p,NS+':wine_q4');const x=p.inventory.getItem(0);if(mode==='name')x.nameTag='Gift';else x.setLore(['Private']);p.inventory.setItem(0,x);code(()=>pourIngredient(p,b),'METADATA_ITEM_REJECTED');assert.equal(state(b).slots.length,0);assert.deepEqual(p.inventory.getItem(0),x);}});
test('full bag rejects poured stacked bottle when no space to return container',()=>{const {p,b}=setup();h(p,NS+':wine_q4',16);fillBag(p);code(()=>pourIngredient(p,b),'INVENTORY_FULL');assert.equal(count(p,NS+':wine_q4'),16);assert.equal(state(b).slots.length,0);});
test('last bottle can exchange in a full bag using its newly freed slot',()=>{const {p,b}=setup();h(p,NS+':wine_q4');fillBag(p);pourIngredient(p,b);assert.equal(p.inventory.getItem(0).typeId,NS+':empty_bottle');assert.equal(state(b).slots.length,1);});
test('input save or native inventory write failure rolls back material and container',()=>{for(const kind of['save','write']){const {p,b}=setup();h(p,NS+':wine_q4',2);if(kind==='save')world.failSet=true;else p.inventory.failAt=p.inventory.writes+1;assert.throws(()=>pourIngredient(p,b),/INJECTED_/);assert.equal(state(b).slots.length,0);assert.equal(count(p,NS+':wine_q4'),2);assert.equal(count(p,NS+':empty_bottle'),0);}});
test('fourth material never overwrites a full three-slot shaker',()=>{const {p,b}=setup();full(p,b);h(p,NS+':wine_q4',16);const before=state(b);code(()=>pourIngredient(p,b),'SHAKER_FULL');assert.deepEqual(state(b),before);assert.equal(count(p,NS+':wine_q4'),16);});
test('recover poured ingredient requires and consumes the earlier returned container',()=>{const {p,b}=setup();h(p,NS+':wine_q6');pourIngredient(p,b);h(p,undefined);code(()=>unpourIngredient(p,b),'NEED_RETURNED_CONTAINER');h(p,NS+':empty_bottle',16);unpourIngredient(p,b);assert.equal(count(p,NS+':empty_bottle'),15);assert.equal(count(p,NS+':wine_q6'),1);assert.equal(state(b).slots.length,0);});
test('recover without returned container fails and cannot duplicate a filled bottle',()=>{const {p,b}=setup();h(p,NS+':wine_q4');pourIngredient(p,b);h(p,EMPTY_CUP);code(()=>unpourIngredient(p,b),'NEED_RETURNED_CONTAINER');assert.equal(state(b).slots.length,1);assert.equal(count(p,NS+':wine_q4'),0);});
test('nonempty shaker cannot be destroyed into a blank portable item',()=>{const {p,b}=setup();h(p,NS+':wine_q4');pourIngredient(p,b);code(()=>breakShaker(p,b),'EMPTY_SHAKER_FIRST');assert.equal(state(b).slots.length,1);assert.equal(count(p,NS+':shaker'),0);});
test('shake requires exactly three materials and rejects interleaved mutation',()=>{const {p,b}=setup();code(()=>startShake(p,b),'NEED_THREE_INGREDIENTS');full(p,b);startShake(p,b);h(p,NS+':empty_bottle');code(()=>unpourIngredient(p,b),'SHAKER_BUSY');code(()=>breakShaker(p,b),'SHAKER_BUSY');code(()=>pourIngredient(p,b),'SHAKER_BUSY');});
test('each of12 recipes can be shaken and served using actual adapters',()=>{for(const r of SHAKER_RECIPES){const {p,b}=setup();full(p,b,r.ingredients.map(a=>a[0]));finish(p,b,90);assert.equal(state(b).result.item,r.output.item);h(p,EMPTY_CUP,16);serveInHand(p,b);assert.equal(count(p,EMPTY_CUP),15);assert.equal(count(p,r.output.item),1);assert.equal(state(b).slots.length,0);assert.equal(state(b).result,null);}});
test('actual adapter covers original timing edges and preserves abort materials',()=>{for(const[t,want]of[[18,null],[19,NS+':mystery_cocktail'],[68,NS+':mystery_cocktail'],[69,SIGNATURE],[88,SIGNATURE],[89,NS+':white_lady'],[98,NS+':white_lady'],[99,NS+':mystery_cocktail'],[110,NS+':mystery_cocktail']]){const {p,b}=setup();full(p,b);finish(p,b,t);assert.equal(state(b).result?.item??null,want);assert.equal(state(b).slots.length,3);}});
test('only owner can stop and duplicate same-tick stop does not finish',()=>{const {p,b}=setup();full(p,b);const other=actor(b.location);startShake(p,b);code(()=>stopShake(other,b,{tick:system.currentTick+90}),'NOT_SHAKE_OWNER');code(()=>stopShake(p,b),'REPEATED_CLICK');stopShake(p,b,{tick:system.currentTick+90});code(()=>stopShake(p,b,{tick:system.currentTick+91}),'NOT_SHAKE_OWNER');});
test('auto stop at111 ticks makes Mystery once and retains ingredients until poured',()=>{const {p,b}=setup();full(p,b);startShake(p,b);system.advance(111);assert.equal(state(b).result.item,NS+':mystery_cocktail');assert.equal(MIX_TEST.sessions.size,0);const after=state(b);system.advance(10);assert.deepEqual(state(b),after);});
test('walking away, changing dimension, logout and unloaded block cancel not complete',()=>{for(const mode of['far','dimension','logout','unloaded']){const {p,b}=setup();full(p,b);startShake(p,b);const k=`${b.location.x}_${b.location.y}_${b.location.z}`;if(mode==='far')p.location.x+=100;if(mode==='dimension')p.dimension=world.getDimension('nether');if(mode==='logout')p.isValid=false;if(mode==='unloaded')dim.unloaded.add(k);system.advance();assert.equal(MIX_TEST.sessions.size,0);assert.equal(state(b).slots.length,3);assert.equal(state(b).result,null);dim.unloaded.delete(k);}});
test('fresh store reload preserves materials/result but active sessions are not persisted',()=>{const {p,b}=setup();full(p,b);startShake(p,b);MIX_TEST.sessions.clear();const fresh=new MixStore(world,validateShaker);assert.deepEqual(fresh.load(shakerKey(dim.id,b.location)),state(b));assert.equal(state(b).result,null);finish(p,b,75);assert.deepEqual(fresh.load(shakerKey(dim.id,b.location)),state(b));});
test('finish save failure preserves materials and releases in-memory ownership',()=>{const {p,b}=setup();full(p,b);startShake(p,b);const before=state(b);world.failSet=true;assert.throws(()=>stopShake(p,b,{tick:system.currentTick+90}),/INJECTED_SAVE/);assert.deepEqual(state(b),before);assert.equal(MIX_TEST.sessions.size,0);});
test('ready result cannot be shaken, extracted as original inputs, or refilled',()=>{const {p,b}=setup();full(p,b);finish(p,b);h(p,NS+':wine_q6');code(()=>pourIngredient(p,b),'RESULT_PENDING');code(()=>unpourIngredient(p,b),'RESULT_PENDING');code(()=>startShake(p,b),'RESULT_PENDING');});
test('wrong serving container and full bag keep the prepared result',()=>{const {p,b}=setup();full(p,b);finish(p,b);h(p,NS+':empty_bottle');code(()=>serveInHand(p,b),'WRONG_SERVING_CONTAINER');h(p,EMPTY_CUP,16);fillBag(p);code(()=>serveInHand(p,b),'INVENTORY_FULL');assert(state(b).result);assert.equal(count(p,EMPTY_CUP),16);});
test('serving failure rolls back the actual cup and the prepared result',()=>{const {p,b}=setup();full(p,b);finish(p,b);h(p,EMPTY_CUP,16);const before=state(b);world.failSet=true;assert.throws(()=>serveInHand(p,b),/INJECTED_SAVE/);assert.deepEqual(state(b),before);assert.equal(count(p,EMPTY_CUP),16);assert.equal(count(p,NS+':white_lady'),0);});
test('signature output is a nonstackable exact payload preserving all qualities',()=>{const {p,b}=setup();const ing=[NS+':wine_q4',NS+':vodka_q5',NS+':ice_wine_q6'];full(p,b,ing);finish(p,b,80);const payload=state(b).result.payload;h(p,EMPTY_CUP,16);serveInHand(p,b);const item=p.inventory.items.find(x=>x?.typeId===SIGNATURE);assert.equal(item.maxAmount,1);assert.deepEqual(JSON.parse(item.getDynamicProperty(SIGNATURE_DATA)),payload);assert.deepEqual(payload.ingredients,ing);assert.equal(count(p,EMPTY_CUP),15);});
test('signature place, reload and return preserve effect duration probability andRGB',()=>{const {p,b}=setup();full(p,b);finish(p,b,75);const payload=state(b).result.payload,cup=cupNear(p,b,SIGNATURE,payload);assert.deepEqual(cs(cup).payload,payload);assert.deepEqual(new MixStore(world,validateCup).load(cupKey(dim.id,cup.location)).payload,payload);h(p,undefined);takeCup(p,cup);const item=p.inventory.items.find(x=>x?.typeId===SIGNATURE);assert.deepEqual(JSON.parse(item.getDynamicProperty(SIGNATURE_DATA)),payload);assert(cup.isAir);});
test('all14 filled cup models and empty glass place and recover correctly',()=>{for(const id of[EMPTY_CUP,...Object.keys(COCKTAILS)]){const {p,b}=setup();full(p,b);finish(p,b,80);const payload=id===SIGNATURE?state(b).result.payload:undefined;const c=cupNear(p,b,id,payload);assert.equal(cs(c).item,id);h(p,undefined);takeCup(p,c);assert.equal(count(p,id),1);assert(c.isAir);}});
test('placed cup takes only1 from16 and cannot be overwritten or merged with another',()=>{const at=site(),p=actor(at);h(p,EMPTY_CUP,16);placeCup(p,at);assert.equal(count(p,EMPTY_CUP),15);code(()=>placeCup(p,at),'SPACE_NOT_CLEAR');assert.equal(count(p,EMPTY_CUP),15);});
test('full inventory rejects cup recovery without erasing payload',()=>{const {p,b}=setup();full(p,b);finish(p,b,80);const c=cupNear(p,b,SIGNATURE,state(b).result.payload),before=cs(c);h(p,'minecraft:stone',64);fillBag(p);code(()=>takeCup(p,c),'INVENTORY_FULL');assert.deepEqual(cs(c),before);});
test('unsupported or missing signature metadata is rejected rather than becoming a white drink',()=>{const at=site(),p=actor(at);h(p,SIGNATURE);code(()=>placeCup(p,at),'UNKNOWN_COCKTAIL_DATA');const x=p.inventory.getItem(0);x.setDynamicProperty(SIGNATURE_DATA,'{}');p.inventory.setItem(0,x);code(()=>placeCup(p,at),'COCKTAIL_SCHEMA');assert(dim.getBlock(at).isAir);});
test('signature helper syncs onlyRGB fields with existing geometry, removes duplicates and cleans up',()=>{const {p,b}=setup();full(p,b);finish(p,b,80);const payload=state(b).result.payload,c=cupNear(p,b,SIGNATURE,payload);const key=cupKey(dim.id,c.location),at={x:c.location.x+.5,y:c.location.y,z:c.location.z+.5};const all=()=>dim.getEntities({type:MIX_TEST.HELPER}).filter(e=>e.getDynamicProperty(MIX_TEST.ANCHOR)===key);assert.equal(all().length,1);assert.deepEqual(all()[0].properties,{'kt_art:red':payload.color>>16&255,'kt_art:green':payload.color>>8&255,'kt_art:blue':payload.color&255});const dup=dim.spawnEntity(MIX_TEST.HELPER,at);dup.setDynamicProperty(MIX_TEST.ANCHOR,key);syncCupVisual(c);assert.equal(all().length,1);h(p,undefined);takeCup(p,c);assert.equal(all().length,0);});
test('signature helper onEntityLoad removes orphan or bad anchors but defers unloaded owner',()=>{const at=site(),k=cupKey(dim.id,at),e=dim.spawnEntity(MIX_TEST.HELPER,at);e.setDynamicProperty(MIX_TEST.ANCHOR,k);const bk=`${at.x}_${at.y}_${at.z}`;dim.unloaded.add(bk);world.afterEvents.entityLoad.emit({entity:e});system.advance();assert.equal(e.removed,false);dim.unloaded.delete(bk);world.afterEvents.entityLoad.emit({entity:e});system.advance();assert(e.removed);const bad=dim.spawnEntity(MIX_TEST.HELPER,at);world.afterEvents.entityLoad.emit({entity:bad});system.advance();assert(bad.removed);});
test('adjacent placed empty glass receives output without a second glass deduction',()=>{const {p,b}=setup();full(p,b);finish(p,b);const c=cupNear(p,b);h(p,'minecraft:stone',9);const before=JSON.stringify(p.inventory.items);pourIntoPlacedCup(p,c,b);assert.equal(cs(c).item,NS+':white_lady');assert.equal(state(b).result,null);assert.equal(JSON.stringify(p.inventory.items),before);});
test('nonadjacent cup and nonempty cup are not overwritten',()=>{const {p,b}=setup();full(p,b);finish(p,b);const c=cupNear(p,b,NS+':emerald');code(()=>pourIntoPlacedCup(p,c,b),'NEED_PLACED_EMPTY_GLASS');assert(state(b).result);const distantAt=site(dim,{...b.location,x:b.location.x+3});h(p,EMPTY_CUP);placeCup(p,distantAt);code(()=>pourIntoPlacedCup(p,dim.getBlock(distantAt),b),'CUP_NOT_ADJACENT');});
test('two-state pour rolls back BOTHDPs and block when second write fails',()=>{const {p,b}=setup();full(p,b);finish(p,b);const c=cupNear(p,b),beforeS=state(b),beforeC=cs(c),original=world.setDynamicProperty;let once=true;world.setDynamicProperty=function(k,v){if(k===shakerKey(dim.id,b.location)&&once){once=false;throw Error('INJECTED_SECOND_SAVE');}return original.call(this,k,v);};try{assert.throws(()=>pourIntoPlacedCup(p,c,b),/INJECTED_SECOND/);}finally{world.setDynamicProperty=original;}assert.deepEqual(state(b),beforeS);assert.deepEqual(cs(c),beforeC);assert.equal(c.typeId,NS+':cup_empty_glassware');});
test('foreign block replacement preserves unreachable state for recovery, never refunds a phantom cup',()=>{const {p,b}=setup(),c=cupNear(p,b),before=cs(c);c.setType('minecraft:stone');code(()=>takeCup(p,c),'CUP_MISMATCH');assert.deepEqual(cs(c),before);assert.equal(count(p,EMPTY_CUP),0);});
test('Java ShakerBlock empty-hand use picks up the placed shaker with exact stored result',()=>{const {p,b}=setup();full(p,b);finish(p,b);h(p,undefined);const e=eventClick(p,b);assert(e.cancel);system.advance();assert(b.isAir);const item=p.inventory.getItem(0);assert.equal(item.typeId,NS+':shaker');assert.equal(readPortableItem(item).state.result.item,NS+':white_lady');});
test('Java BlockItem parity: Shaker and empty glassware place without sneaking, including side-face targets',()=>{for(const item of[NS+':shaker',EMPTY_CUP]){const at=site(),p=actor(at),base=dim.getBlock({...at,y:at.y-1});h(p,item);assert(eventClick(p,base,{sneak:false}).cancel);system.advance();assert.equal(dim.getBlock(at).typeId,item===EMPTY_CUP?NS+':cup_empty_glassware':MIX_TEST.STATION);assert.equal(count(p,item),0);}const clicked=dim.getBlock(pos());clicked.setType('minecraft:stone');const target={x:clicked.location.x+1,y:clicked.location.y,z:clicked.location.z},p=actor(clicked.location);h(p,NS+':shaker');assert(eventClick(p,clicked,{face:'East'}).cancel);system.advance();assert.equal(dim.getBlock(target).typeId,MIX_TEST.STATION);});
test('CocktailBlockItem parity: non-sneak remains drink use, sneak use places the cocktail block',()=>{const at=site(),p=actor(at),base=dim.getBlock({...at,y:at.y-1});h(p,NS+':white_lady');let e=eventClick(p,base,{sneak:false});assert.equal(e.cancel,false);system.advance();assert(dim.getBlock(at).isAir);assert.equal(count(p,NS+':white_lady'),1);e=eventClick(p,base,{sneak:true});assert(e.cancel);system.advance();assert.equal(dim.getBlock(at).typeId,NS+':cup_white_lady');assert.equal(count(p,NS+':white_lady'),0);});

test('deferred Java BlockItem placement aborts when hand or dimension changes',()=>{for(const kind of['hand','dimension']){const at=site(),p=actor(at),base=dim.getBlock({...at,y:at.y-1});h(p,NS+':shaker');eventClick(p,base,{sneak:false});if(kind==='hand')h(p,'minecraft:stone');else p.dimension=world.getDimension('nether');system.advance();assert(dim.getBlock(at).isAir);}});
test('same revision double input event only pours one item and returns one bottle',()=>{const {p,b}=setup(),other=actor(b.location);h(p,NS+':wine_q4',2);h(other,NS+':wine_q4',2);eventClick(p,b);eventClick(other,b);system.advance();assert.equal(state(b).slots.length,1);assert.equal(count(p,NS+':wine_q4')+count(other,NS+':wine_q4'),3);assert.equal(count(p,NS+':empty_bottle')+count(other,NS+':empty_bottle'),1);});
test('two players racing empty-hand pickup can retrieve one placed Shaker state only once',()=>{const {p,b}=setup();full(p,b);finish(p,b);const other=actor(b.location);h(p,undefined);h(other,undefined);eventClick(p,b);eventClick(other,b);system.advance();assert(b.isAir);assert.equal(count(p,NS+':shaker')+count(other,NS+':shaker'),1);});
test('two players cannot both retrieve a placed signature',()=>{const {p,b}=setup();full(p,b);finish(p,b,75);const c=cupNear(p,b,SIGNATURE,state(b).result.payload),other=actor(c.location);h(p,undefined);h(other,undefined);eventClick(p,c);eventClick(other,c);system.advance();assert.equal(count(p,SIGNATURE)+count(other,SIGNATURE),1);});
test('already cancelled interactions/breaks and held-repeat events are respected',()=>{const {p,b}=setup();h(p,NS+':wine_q4',2);eventClick(p,b,{cancel:true});eventClick(p,b,{first:false});world.beforeEvents.playerBreakBlock.emit({player:p,block:b,cancel:true});system.advance();assert.equal(state(b).slots.length,0);assert.equal(count(p,NS+':wine_q4'),2);assert.equal(b.typeId,MIX_TEST.STATION);});
test('Java GlasswareBlock empty-hand use retrieves the cup; it never auto-selects an adjacent Shaker',()=>{const {p,b}=setup();full(p,b);finish(p,b);const c=cupNear(p,b);h(p,undefined);const e=eventClick(p,c);assert(e.cancel);system.advance();assert(c.isAir);assert(state(b).result);assert.equal(count(p,EMPTY_CUP),1);});
test('Java ShakerItem useOn pours its carried result into a placed empty glass before standard placement',()=>{const {p,b}=setup();full(p,b);finish(p,b);h(p,undefined);const portable=pickupShaker(p,b);assert.equal(readPortableItem(portable).state.result.item,NS+':white_lady');const at=site(),cupSlot=1;p.selectedSlotIndex=cupSlot;p.inventory.setItem(cupSlot,new ItemStack(EMPTY_CUP));placeCup(p,at);const cup=dim.getBlock(at);p.selectedSlotIndex=0;const e=eventClick(p,cup);assert(e.cancel);system.advance();assert.equal(cs(cup).item,NS+':white_lady');assert.equal(readPortableItem(p.inventory.getItem(0)).state.result,null);});
test('explosion exclusion composes with other protection callbacks',()=>{const {p,b}=setup(),c=cupNear(p,b),stone=dim.getBlock(pos());stone.setType('minecraft:stone');let impacted=[b,c,stone];world.beforeEvents.explosion.emit({getImpactedBlocks:()=>impacted,setImpactedBlocks:v=>impacted=v});assert.deepEqual(impacted,[stone]);});
test('adventure/spectator and distant users cannot operate or retrieve',()=>{for(const mode of[GameMode.Adventure,GameMode.Spectator]){const {p,b}=setup();p.mode=mode;h(p,NS+':wine_q4');code(()=>pourIngredient(p,b),'GAME_MODE_LOCKED');}const {p,b}=setup();full(p,b);p.location.x+=20;code(()=>startShake(p,b),'OUT_OF_REACH');});
test('Creative roundtrip conserves real machine/cup and ingredient counts',()=>{const at=site(),p=actor(at,dim,GameMode.Creative);h(p,NS+':shaker');placeShaker(p,at);const b=dim.getBlock(at);h(p,NS+':wine_q4',16);pourIngredient(p,b);assert.equal(count(p,NS+':wine_q4'),15);p.selectedSlotIndex=p.inventory.items.findIndex(x=>x?.typeId===NS+':empty_bottle');unpourIngredient(p,b);assert.equal(count(p,NS+':empty_bottle'),0);assert.equal(count(p,NS+':wine_q4'),16);breakShaker(p,b);assert.equal(count(p,NS+':shaker'),1);});
test('signature consumption applies saved native effects only and never modifies native post-drink inventory',()=>{const {p,b}=setup();full(p,b,[NS+':wine_q6',NS+':wine_q6',NS+':wine_q6']);finish(p,b,75);const result=state(b).result,item=resultStack(result);h(p,EMPTY_CUP,1);const before=JSON.stringify(p.inventory.items);const outcomes=consumeCocktail({source:p,itemStack:item},()=>0);const native=result.payload.effects.find(x=>x.effect==='minecraft:regeneration');assert.deepEqual(p.effects.find(x=>x.id==='regeneration'),{id:'regeneration',ticks:native.duration*20,amplifier:native.amplifier,showParticles:true});assert(outcomes.some(x=>x.status==='UNIMPLEMENTED_CUSTOM_EFFECT'));assert.equal(JSON.stringify(p.inventory.items),before);});
test('fixed cocktails retain pending custom effects instead of inventing native substitutes',()=>{for(const id of Object.keys(COCKTAILS).filter(x=>x!==SIGNATURE)){const p=actor();const out=consumeCocktail({source:p,itemStack:new ItemStack(id)},()=>0);assert(out.length>0);assert(out.every(x=>['kaleidoscope_tavern:bloody_mary','kaleidoscope_tavern:xp_drain','kaleidoscope_tavern:zenith','kaleidoscope_tavern:upside_down','kaleidoscope_tavern:vision','kaleidoscope_tavern:tomb_raider','kaleidoscope_tavern:ardent_heat','kaleidoscope_tavern:high_heels'].includes(x.effect)?x.status==='APPLIED_CUSTOM':x.status==='UNIMPLEMENTED_CUSTOM_EFFECT'));assert.equal(p.effects.length,0);}});
test('malformed signature consume and API effect error remain explicit diagnostics',()=>{const p=actor();assert.equal(consumeCocktail({source:p,itemStack:new ItemStack(SIGNATURE)})[0].status,'INVALID_PAYLOAD');const {p:q,b}=setup();full(q,b,[NS+':wine_q6',NS+':wine_q6',NS+':wine_q6']);finish(q,b,75);q.failEffect=true;assert(consumeCocktail({source:q,itemStack:resultStack(state(b).result)},()=>0).some(x=>x.status==='ENGINE_REJECTED'));assert(mixologyDiagnostics.errors.length<=16);});
test('clone-output transaction writes changed payload even if type and amount are identical',()=>{const c=new Container(1),old=new ItemStack(SIGNATURE),next=new ItemStack(SIGNATURE);old.setDynamicProperty(SIGNATURE_DATA,'old');next.setDynamicProperty(SIGNATURE_DATA,'new');c.setItem(0,old);const tx=planInventory(c,0,1,[{stack:next,count:1}],(id,n)=>new ItemStack(id,n));assert.deepEqual(tx.changes,[0]);commitInventory(tx,c,()=>{},()=>{});assert.equal(c.getItem(0).getDynamicProperty(SIGNATURE_DATA),'new');});
test('extension handshake creates independent recipe page AND executable shaker recipe',()=>{const payload={api:1,source:'c3_rice_demo',version:'1.0.0',recipes:[{id:'c3_rice_demo:rice',kind:'shaker',ingredients:[['kaleidoscope_cookery:rice'],['kaleidoscope_cookery:rice'],['kaleidoscope_cookery:rice']],output:{item:NS+':emerald'}}],pages:[{id:'c3_rice_demo:about',title:{en_US:'C3 rice mix'},body:{en_US:'TEST only'},recipeIds:['c3_rice_demo:rice']}]};const client=registerTavernExtension(system,payload,{log:()=>{}});system.advance(50);assert(client.registered);try{assert.equal(registry().allRecipes().length,42);assert(guideEntries(registry(),'en_US').some(e=>e.id==='c3_rice_demo:about'));const {p,b}=setup();full(p,b,Array(3).fill('kaleidoscope_cookery:rice'));assert.equal(count(p,NS+':empty_bottle'),0);finish(p,b);h(p,EMPTY_CUP);serveInHand(p,b);assert.equal(count(p,NS+':emerald'),1);}finally{client.dispose();registry().remove(payload.source);}});
test('extension recipe snapshot survives unregister while shaking then still serves original result',()=>{const source='c3_snapshot',raw={api:1,source,version:'1.0.0',recipes:[{id:source+':recipe',kind:'shaker',ingredients:Array(3).fill(['minecraft:apple']),output:{item:NS+':emerald'}}]};registry().install(raw);const {p,b}=setup();full(p,b,Array(3).fill('minecraft:apple'));startShake(p,b);registry().remove(source);stopShake(p,b,{tick:system.currentTick+90});assert.equal(state(b).result.item,NS+':emerald');h(p,EMPTY_CUP);serveInHand(p,b);assert.equal(count(p,NS+':emerald'),1);});
test('unknown external output pack refuses serving without deducting result or glass',()=>{const {p,b}=setup();full(p,b);finish(p,b);h(p,EMPTY_CUP,16);const get=ItemTypes.get;ItemTypes.get=id=>id===NS+':white_lady'?undefined:get(id);try{code(()=>serveInHand(p,b),'OUTPUT_PACK_MISSING');}finally{ItemTypes.get=get;}assert.equal(count(p,EMPTY_CUP),16);assert(state(b).result);});
test('external result must be received in hand, not put in a nonexistent cup model',()=>{const source='c3_foreign',raw={api:1,source,version:'1.0.0',recipes:[{id:source+':recipe',kind:'shaker',ingredients:Array(3).fill(['minecraft:apple']),output:{item:'minecraft:apple'},carrier:'minecraft:bucket'}]};registry().install(raw);try{const {p,b}=setup();full(p,b,Array(3).fill('minecraft:apple'));finish(p,b);const c=cupNear(p,b);code(()=>pourIntoPlacedCup(p,c,b),'EXTERNAL_OUTPUT_USE_HAND');h(p,'minecraft:bucket',16);serveInHand(p,b);assert.equal(count(p,'minecraft:bucket'),15);assert.equal(count(p,'minecraft:apple'),1);}finally{registry().remove(source);}});
test('Cookery-published guide data lists12 shaker recipes and keeps shaker-specific descriptions',()=>{const entries=guideEntries(registry(),'en_US');assert(entries.some(e=>e.id===NS+':mixology'));for(const r of SHAKER_RECIPES){const page=recipePage(r,'en_US');assert(!page.body.includes('4000'));assert(!page.body.includes('undefined'));}assert.equal(diagnosticSnapshot().guideAuthority,'kaleidoscope_cookery:guidebook');assert.equal(registry().allRecipes().length,41);});

test('entity death immediately cancels session while preserving poured materials',()=>{const {p,b}=setup();full(p,b);startShake(p,b);world.afterEvents.entityDie.emit({deadEntity:p});assert.equal(MIX_TEST.sessions.size,0);system.advance(120);assert.equal(state(b).result,null);assert.equal(state(b).slots.length,3);});
test('public SDK refuses mixology payload to a v1 host lacking the additive capability',()=>{const payload=JSON.parse(fs.readFileSync(new URL('../examples/mixology-extension-payload.json',import.meta.url)));const seen=[],signals=[];const local={afterEvents:{scriptEventReceive:{subscribe:f=>signals.push(f),unsubscribe:()=>{}}},sendScriptEvent:(...x)=>seen.push(x),run:()=>1,runTimeout:()=>2,clearRun:()=>{}};const client=registerTavernExtension(local,payload,{log:()=>{}});signals[0]({id:NS+':api_ready',sourceType:'Server',message:JSON.stringify({api:1,capabilities:['barrel_recipes']})});assert.equal(client.attempts,0);assert.equal(seen.length,0);client.dispose();});
test('packaged optional Mixology Demo loads own SDK and actual example recipe is executable',async()=>{const demo=await import('../examples/Tavern-Mixology-Demo/BP/scripts/main.js');system.advance(50);assert(demo.registration.registered);try{const {p,b}=setup();full(p,b,Array(3).fill('kaleidoscope_cookery:rice'));finish(p,b);assert.equal(state(b).result.recipeId,'tavern_mixology_demo:rice_emerald');h(p,EMPTY_CUP);serveInHand(p,b);assert.equal(count(p,NS+':emerald'),1);assert(guideEntries(registry(),'en_US').some(x=>x.id==='tavern_mixology_demo:about'));}finally{demo.registration.dispose();registry().remove('tavern_mixology_demo');}});

test('pouring a valid metadata-bearing signature back into a shaker is rejected losslessly',()=>{const {p,b}=setup();full(p,b);finish(p,b,75);const item=resultStack(state(b).result),at=site(dim,{...b.location,x:b.location.x+2});h(p,NS+':shaker');placeShaker(p,at);p.inventory.setItem(0,item);code(()=>pourIngredient(p,dim.getBlock(at)),'SIGNATURE_INPUT_NOT_ADAPTED');assert.deepEqual(p.inventory.getItem(0),item.clone());assert.equal(state(dim.getBlock(at)).slots.length,0);});
