/** C5 native events/potions/health simulation. No client rendering or native engine consumption. */
import test from 'node:test';import assert from 'node:assert/strict';
import {world,system,startup,Player,ItemStack,Potions,Entity,mockHealth} from './fake-server.js';
import {runtimeRegistry,book} from '../runtime/BP/scripts/main.js';
import {placeShaker,pourIngredient,unpourIngredient,pickupShaker,readPortableItem,MIX_TEST,NATIVE_TEST,pruneNativeLatches,cancelHeldShake,consumeCocktail,startShake,stopShake,serveInHand} from '../runtime/BP/scripts/bedrock/mixology.js';
import {potionIdentity,potionInput,restorePotion,potionCapabilities} from '../runtime/BP/scripts/bedrock/potions.js';
import {statusNow,clearCustomEffects,applyCustomEffect,handleKill,tickCustomEffects,CUSTOM_TEST} from '../runtime/BP/scripts/bedrock/custom-effects.js';
import {CUSTOM_STATUS_KEY,activeStatus} from '../runtime/BP/scripts/core/custom-effects.js';
import {NS,EMPTY_CUP,SIGNATURE,shakerKey} from '../runtime/BP/scripts/core/mixology.js';
import {PORTABLE_DATA} from '../runtime/BP/scripts/core/immersion.js';
import {INPUT_MODE_KEY,HOLD_TAG} from '../runtime/BP/scripts/core/native-use.js';
const regs=startup();system.advance(2);const d=world.getDimension('overworld');let counter=0,online=[];world.getAllPlayers=()=>online;
const hand=p=>p.inventory.getItem(p.selectedSlotIndex);
const put=(p,item,n=1)=>p.inventory.setItem(p.selectedSlotIndex,typeof item==='string'?new ItemStack(item,n):item);
const state=b=>MIX_TEST.shakerStore.load(shakerKey(d.id,b.location));
const count=(p,id)=>p.inventory.items.filter(i=>i?.typeId===id).reduce((s,i)=>s+i.amount,0);
function setup(full=true){const pos={x:++counter*20,y:64,z:0};const p=new Player('c5-'+counter,d);p.location={x:pos.x+.5,y:65,z:2};d.getBlock({...pos,y:63}).setType('minecraft:stone');put(p,NS+':shaker');placeShaker(p,pos);const b=d.getBlock(pos);if(full)for(const id of['vodka','riesling_dry_white','glowflower_brew']){put(p,NS+':'+id+'_q4');pourIngredient(p,b);}put(p,undefined);return {p,b};}
function portable(){const r=setup();pickupShaker(r.p,r.b);return r;}
function start(p){world.afterEvents.itemStartUse.emit({source:p,itemStack:hand(p),useDuration:72000});}
function stop(p,t,kind='itemReleaseUse'){world.afterEvents[kind].emit({source:p,itemStack:hand(p),useDuration:72000-t});}
test.afterEach(()=>{for(const id of [...MIX_TEST.handSessions.keys()])cancelHeldShake(id);NATIVE_TEST.nativeLatches.clear();for(const k of [...MIX_TEST.sessions.keys()])MIX_TEST.sessions.delete(k);online=[];CUSTOM_TEST.tracks.clear();CUSTOM_TEST.deaths.clear();d.failAudio=false;d.failParticles=false;});
test('native onUse does not toggle: start comes only from itemStartUse',()=>{const {p}=portable();regs.items.get(NS+':portable_shaker').onUse({source:p,itemStack:hand(p)});assert(!MIX_TEST.handSessions.has(p.id));start(p);assert(MIX_TEST.handSessions.get(p.id).native);});
test('native start makes ZERO inventory writes and retains type, token and payload',()=>{const {p}=portable(),before=hand(p),writes=p.inventory.writes;start(p);assert.equal(p.inventory.writes,writes);assert.deepEqual(hand(p),before);assert(p.hasTag(HOLD_TAG));});
for(const [t,id]of[[0,null],[18,null],[19,'mystery_cocktail'],[68,'mystery_cocktail'],[69,'signature_cocktail'],[88,'signature_cocktail'],[89,'white_lady'],[98,'white_lady'],[99,'mystery_cocktail'],[110,'mystery_cocktail']])test('native remaining duration boundary '+t,()=>{const {p}=portable();start(p);system.advance(t);stop(p,t);assert.equal(readPortableItem(hand(p)).state.result?.item??null,id?NS+':'+id:null);assert.equal(hand(p).typeId,NS+':shaker');assert(!p.hasTag(HOLD_TAG));});
test('release then stop callback finalizes only once',()=>{const {p}=portable();start(p);system.advance(90);stop(p,90);const before=hand(p),writes=p.inventory.writes;stop(p,90,'itemStopUse');assert.deepEqual(hand(p),before);assert.equal(p.inventory.writes,writes);});
test('stop-only platform event also finalizes through the same path',()=>{const {p}=portable();start(p);system.advance(90);stop(p,90,'itemStopUse');assert.equal(readPortableItem(hand(p)).state.result.item,NS+':white_lady');});
test('duplicate native start does not reset the session time',()=>{const {p}=portable();start(p);system.advance(70);start(p);system.advance(20);stop(p,90);assert.equal(readPortableItem(hand(p)).state.result.item,NS+':white_lady');});
test('111 watchdog latches held input and never restarts/re-rolls before physical release',()=>{const {p}=portable();start(p);system.advance(111);const before=hand(p);start(p);system.advance(30);stop(p,141);assert.deepEqual(hand(p),before);assert.equal(readPortableItem(hand(p)).state.result.item,NS+':mystery_cocktail');});
test('duration mismatch cancels and leaves ingredients intact',()=>{const {p}=portable(),before=hand(p);start(p);system.advance(50);stop(p,90);assert.deepEqual(hand(p),before);assert(!MIX_TEST.handSessions.has(p.id));});
test('undefined stop item (dimension/teleport interruption) cannot count as release',()=>{const {p}=portable(),before=hand(p);start(p);system.advance(90);world.afterEvents.itemStopUse.emit({source:p,useDuration:71910});assert.deepEqual(hand(p),before);});
test('switched hotbar cancels native hold without converting/replacing the old tool',()=>{const {p}=portable(),before=hand(p);start(p);p.inventory.setItem(1,new ItemStack('minecraft:stone',4));p.selectedSlotIndex=1;system.advance();stop(p,1);assert.equal(hand(p).amount,4);assert.deepEqual(p.inventory.getItem(0),before);assert(!p.hasTag(HOLD_TAG));});
test('sneaking cancels, and a late release does not create a result',()=>{const {p}=portable(),before=hand(p);start(p);system.advance(75);p.isSneaking=true;system.advance();stop(p,76);assert.deepEqual(hand(p),before);});
test('unavailable native input is not silently converted to two clicks',()=>{const {p}=portable(),before=hand(p),c=regs.items.get(NS+':portable_shaker');c.onUse({source:p,itemStack:hand(p)});system.advance(90);c.onUse({source:p,itemStack:hand(p)});assert.deepEqual(hand(p),before);});
test('explicit fallback works and ignores native-start callbacks',()=>{const {p}=portable();p.setDynamicProperty(INPUT_MODE_KEY,'toggle');start(p);assert(!MIX_TEST.handSessions.has(p.id));regs.items.get(NS+':portable_shaker').onUse({source:p,itemStack:hand(p)});assert(MIX_TEST.handSessions.has(p.id));});
test('server/player registries are independent for simultaneous native uses',()=>{const a=portable().p,b=portable().p;start(a);start(b);system.advance(75);stop(a,75);system.advance(15);stop(b,90);assert.equal(readPortableItem(hand(a)).state.result.item,SIGNATURE);assert.equal(readPortableItem(hand(b)).state.result.item,NS+':white_lady');});
for(const delivery of ['minecraft:consumable','minecraft:splash','minecraft:lingering'])for(const effect of ['minecraft:swiftness','minecraft:long_poison','minecraft:strong_healing'])test('native potion round-trip '+effect+'/'+delivery,()=>{const {p,b}=setup(false),original=Potions.resolve(effect,delivery);put(p,original);pourIngredient(p,b);assert.equal(count(p,'minecraft:glass_bottle'),1);assert.deepEqual(state(b).slots[0].potion,potionIdentity(original));put(p,'minecraft:glass_bottle');unpourIngredient(p,b);assert.deepEqual(hand(p),original);assert.equal(state(b).slots.length,0);});
test('native potion duration is recorded in snapshot seconds, not guessed by base ID',()=>{const p=Potions.resolve('minecraft:strong_swiftness','minecraft:consumable'),s=potionInput(p);assert.equal(s.effects[0].duration,90);assert.equal(s.effects[0].amplifier,1);assert.equal(s.color,0xffffff);});
test('unknown native potion effect rejects intake without taking potion or giving bottle',()=>{const {p,b}=setup(false);put(p,Potions.resolve('minecraft:weaving','minecraft:consumable'));const before=hand(p);assert.throws(()=>pourIngredient(p,b),e=>e.code==='POTION_EFFECT_UNSUPPORTED');assert.deepEqual(hand(p),before);assert.equal(state(b).slots.length,0);});
test('custom named/lore/DP potions rejected intact',()=>{for(const change of[i=>i.nameTag='named',i=>i.setLore(['lore']),i=>i.setDynamicProperty('foreign:data','a')]){const {p,b}=setup(false),i=Potions.resolve('minecraft:water','minecraft:consumable');change(i);put(p,i);assert.throws(()=>pourIngredient(p,b));assert.deepEqual(hand(p),i);}});
test('potion changed during deferred interaction is not consumed as an older potion',()=>{const {p,b}=setup(false);put(p,Potions.resolve('minecraft:swiftness','minecraft:consumable'));world.beforeEvents.playerInteractWithBlock.emit({player:p,block:b,blockFace:'Up',isFirstEvent:true,cancel:false});const next=Potions.resolve('minecraft:long_poison','minecraft:consumable');put(p,next);system.advance();assert.equal(state(b).slots.length,0);assert.deepEqual(hand(p),next);});
test('potion state survives portable pickup and re-placement',()=>{const {p,b}=setup(false);put(p,Potions.resolve('minecraft:long_poison','minecraft:lingering'));pourIngredient(p,b);const before=state(b);put(p,undefined);pickupShaker(p,b);placeShaker(p,b.location);assert.deepEqual(state(b),before);});
test('save failure during potion insertion returns exact variant without an extra bottle',()=>{const {p,b}=setup(false);const original=Potions.resolve('minecraft:strong_healing','minecraft:splash');put(p,original);world.failSet=true;assert.throws(()=>pourIngredient(p,b));assert.deepEqual(hand(p),original);assert.equal(count(p,'minecraft:glass_bottle'),0);assert.equal(state(b).slots.length,0);});
test('source WHITE recipe tag now admits drinkable potions, not invented splash tags',()=>{const {p,b}=setup(false);put(p,Potions.resolve('minecraft:water','minecraft:consumable'));pourIngredient(p,b);for(const name of['riesling_dry_white','glowflower_brew']){put(p,NS+':'+name+'_q4');pourIngredient(p,b);}put(p,undefined);startShake(p,b);stopShake(p,b,{tick:system.currentTick+90});assert.equal(state(b).result.item,NS+':white_lady');});
test('mixed potion signature applies actual native effects and returns no second glass',()=>{const {p,b}=setup(false);for(const type of['minecraft:strong_swiftness','minecraft:healing','minecraft:long_poison']){put(p,Potions.resolve(type,'minecraft:consumable'));pourIngredient(p,b);}put(p,undefined);startShake(p,b);stopShake(p,b,{tick:system.currentTick+75});put(p,EMPTY_CUP,16);serveInHand(p,b);const sig=p.inventory.items.find(x=>x?.typeId===SIGNATURE);const before=count(p,EMPTY_CUP);const result=consumeCocktail({source:p,itemStack:sig},()=>0);assert.equal(result.filter(x=>x.status==='APPLIED').length,3);assert(p.effects.some(e=>e.id==='speed'&&e.amplifier===1));assert.equal(count(p,EMPTY_CUP),before);});
test('potion diagnostic reflects actual runtime available registry, not all theoretical specs',()=>{const c=potionCapabilities();assert(c.recognizedEffects.includes('minecraft:water'));assert(c.unrecognizedEffects.includes('minecraft:weaving'));assert.equal(c.deliveryTypes.length,3);});
test('blood Mary drinking applies a timed custom status, not a replacement native buff',()=>{const p=setup(false).p;const out=consumeCocktail({source:p,itemStack:new ItemStack(NS+':bloody_mary')},()=>0);assert.equal(out[0].status,'APPLIED_CUSTOM');assert.equal(activeStatus(statusNow(p),NS+':bloody_mary').ticks,36000);assert.equal(p.effects.length,0);});
test('kill heal uses victim maximum health, caps at own maximum and deduplicates',()=>{const p=setup(false).p;p.health=mockHealth(5,20);applyCustomEffect(p,{effect:NS+':bloody_mary',duration:10,amplifier:0});const v=new Entity('minecraft:zombie',d,p.location);v.health=mockHealth(0,30);const e={deadEntity:v,damageSource:{damagingEntity:p}};world.afterEvents.entityDie.emit(e);assert.equal(p.health.currentValue,15);world.afterEvents.entityDie.emit(e);assert.equal(p.health.currentValue,15);const v2=new Entity('minecraft:zombie',d,p.location);v2.health=mockHealth(0,30);handleKill({deadEntity:v2,damageSource:{damagingEntity:p}});assert.equal(p.health.currentValue,20);});
test('no status, own death or dead killer grants no healing',()=>{const p=setup(false).p;p.health=mockHealth(5,20);const v=new Entity('minecraft:zombie',d,p.location);v.health=mockHealth(0,30);handleKill({deadEntity:v,damageSource:{damagingEntity:p}});assert.equal(p.health.currentValue,5);applyCustomEffect(p,{effect:NS+':bloody_mary',duration:10,amplifier:0});handleKill({deadEntity:p,damageSource:{damagingEntity:p}});assert.equal(p.health.currentValue,5);});
test('timed effects expire online and do not become permanent DP buffs',()=>{const p=setup(false).p;online=[p];applyCustomEffect(p,{effect:NS+':bloody_mary',duration:1,amplifier:0});system.advance(20);assert(!activeStatus(statusNow(p),NS+':bloody_mary'));system.advance(5);assert.equal(p.getDynamicProperty(CUSTOM_STATUS_KEY),undefined);});
test('milk clears only Tavern custom status keys',()=>{const p=setup(false).p;p.setDynamicProperty('kc:guidebook_language','en_US');applyCustomEffect(p,{effect:NS+':xp_drain',duration:10,amplifier:0});world.afterEvents.itemCompleteUse.emit({source:p,itemStack:new ItemStack('minecraft:milk_bucket')});assert.equal(p.getDynamicProperty(CUSTOM_STATUS_KEY),undefined);assert.equal(p.getDynamicProperty('kc:guidebook_language'),'en_US');});
test('logout freezes remaining custom time and reconnect restores it',()=>{const p=setup(false).p;online=[p];applyCustomEffect(p,{effect:NS+':bloody_mary',duration:10,amplifier:0});system.advance(12);world.afterEvents.playerLeave.emit({playerId:p.id});online=[];const before=p.getDynamicProperty(CUSTOM_STATUS_KEY);system.advance(100);world.afterEvents.playerSpawn.emit({player:p,initialSpawn:true});assert.equal(p.getDynamicProperty(CUSTOM_STATUS_KEY),before);assert.equal(statusNow(p).entries[0].ticks,188);});
test('XP drain moves existing orbs without replacing or increasing their values',()=>{const p=setup(false).p,orb=d.spawnEntity('minecraft:xp_orb',{...p.location,x:p.location.x+4});orb.xpValue=17;applyCustomEffect(p,{effect:NS+':xp_drain',duration:10,amplifier:0});online=[p];tickCustomEffects();assert(orb.velocity.x<0);assert.equal(orb.xpValue,17);assert(d.entities.has(orb.id));});
test('Zenith teleports only to a checked top surface and applies source hunger time',()=>{const p=setup(false).p;p.location={x:counter*20+.5,y:50,z:.5};d.getBlock({x:counter*20,y:70,z:0}).setType('minecraft:stone');const out=consumeCocktail({source:p,itemStack:new ItemStack(NS+':godfather')},()=>0);assert.equal(out[0].status,'APPLIED_CUSTOM');assert.equal(p.location.y,71);assert(p.effects.some(e=>e.id==='hunger'&&e.ticks===600));});
test('unsupported source effect still has no fabricated substitute',()=>{const p=setup(false).p;const out=consumeCocktail({source:p,itemStack:new ItemStack(NS+':white_lady')},()=>0);assert.equal(out[0].status,'UNIMPLEMENTED_CUSTOM_EFFECT');assert.equal(p.effects.length,0);});


test('missing native stop is recoverable after a hotbar context change',()=>{const {p}=portable();start(p);p.selectedSlotIndex=1;system.advance();pruneNativeLatches();assert(!NATIVE_TEST.nativeLatches.has(p.id));p.selectedSlotIndex=0;start(p);assert(MIX_TEST.handSessions.has(p.id));cancelHeldShake(p.id);stop(p,0);});
test('auto-complete latch is kept until release, so holding cannot reroll results',()=>{const {p}=portable();start(p);system.advance(111);const saved=hand(p);pruneNativeLatches();assert(NATIVE_TEST.nativeLatches.has(p.id));start(p);assert(!MIX_TEST.handSessions.has(p.id));assert.deepEqual(hand(p),saved);stop(p,111);assert(!NATIVE_TEST.nativeLatches.has(p.id));});
test('full inventory potion withdrawal preserves the slot snapshot and sixteen glass bottles',()=>{const {p,b}=setup(false);put(p,Potions.resolve('minecraft:long_poison','minecraft:consumable'));pourIngredient(p,b);put(p,'minecraft:glass_bottle',16);for(let i=1;i<p.inventory.size;i++)p.inventory.setItem(i,new ItemStack('minecraft:stone',64));const saved=state(b);assert.throws(()=>unpourIngredient(p,b));assert.equal(hand(p).amount,16);assert.deepEqual(state(b),saved);});
test('potion resolver silently changing type is detected before any consumption',()=>{const {p,b}=setup(false),original=Potions.resolve('minecraft:strong_healing','minecraft:splash'),old=Potions.resolve;put(p,original);try{Potions.resolve=()=>old('minecraft:water','minecraft:consumable');assert.throws(()=>pourIngredient(p,b),e=>e.code==='POTION_ROUNDTRIP_FAILED');assert.deepEqual(hand(p),original);assert.equal(state(b).slots.length,0);}finally{Potions.resolve=old;}});
test('potion return save failure rolls back to the exact stored potion identity',()=>{const {p,b}=setup(false);put(p,Potions.resolve('minecraft:strong_harming','minecraft:lingering'));pourIngredient(p,b);put(p,'minecraft:glass_bottle',16);const before=state(b);world.failSet=true;assert.throws(()=>unpourIngredient(p,b));assert.deepEqual(state(b),before);assert.equal(hand(p).amount,16);});
test('Zenith rejects an unsafe top surface without teleport, hunger or editing blocks',()=>{const p=setup(false).p;p.location={x:counter*20+.5,y:50,z:.5};const top=d.getBlock({x:counter*20,y:70,z:0});top.setType('minecraft:lava');const here={...p.location};applyCustomEffect(p,{effect:NS+':zenith',duration:1,amplifier:0});assert.deepEqual(p.location,here);assert.equal(p.effects.length,0);assert.equal(top.typeId,'minecraft:lava');});
test('dead killer remains dead despite an attributed kill event',()=>{const p=setup(false).p;p.health=mockHealth(0,20);applyCustomEffect(p,{effect:NS+':bloody_mary',duration:10,amplifier:0});const v=new Entity('minecraft:zombie',d,p.location);v.health=mockHealth(0,30);handleKill({deadEntity:v,damageSource:{damagingEntity:p}});assert.equal(p.health.currentValue,0);});
test('native potion extension waits for capability instead of claiming registration on an old host',async()=>{const {registerTavernExtension}=await import('../sdk/tavern-extension-client.js');const {EVENTS}=await import('../sdk/protocol.js');const bus=new system.constructor(),logs=[];const payload={api:1,source:'potion_demo',version:'1.0.0',recipes:[{id:'potion_demo:white',kind:'shaker',ingredients:[['minecraft:potion'],['minecraft:potion'],['minecraft:potion']],output:{item:NS+':white_lady'}}]};const c=registerTavernExtension(bus,payload,{log:m=>logs.push(m)});bus.afterEvents.scriptEventReceive.emit({id:EVENTS.ready,sourceType:'Server',message:JSON.stringify({api:1,capabilities:['shaker_recipes']})});bus.advance(5);assert(!c.registered);assert(!bus.sent.some(e=>e.id===EVENTS.begin));assert(logs.some(x=>x.includes('native_potion_inputs')));bus.afterEvents.scriptEventReceive.emit({id:EVENTS.ready,sourceType:'Server',message:JSON.stringify({api:1,capabilities:['shaker_recipes','native_potion_inputs']})});bus.advance(10);assert(bus.sent.some(e=>e.id===EVENTS.begin));assert(!c.registered);c.dispose();});
