/** Full C6 adapter calls on deterministic API doubles, NOT Minecraft/Realms/player animation tests. */
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import './c6-fixtures.js';
import {world,system,startup,Player,Entity,ItemStack,GameMode,BlockPermutation,mockHealth} from './fake-server.js';
import {runtimeRegistry,diagnosticSnapshot} from '../runtime/BP/scripts/main.js';
import {placeFurniture,sitOnFurniture,recoverFurniture,recolorLight,ensureSeat,maintainSeat,tickFurniture,syncSofa,syncTable,syncBarCounter,useGlasswareHolder,FURNITURE_TEST,furnitureDiagnostics} from '../runtime/BP/scripts/bedrock/furniture.js';
import {NS,COLORS,LIGHT_COLORS,FACING,CONNECTION,AXIS,POSITION,SEAT_ANCHOR,SOFA_CONNECTION,SOFA_SEAT_ID,TABLE_AXIS,TABLE_POSITION,GLASSWARE_SLOTS,anchorKey,seatId} from '../runtime/BP/scripts/core/furniture.js';
import {performShriek,COMBAT_TEST,combatDiagnostics} from '../runtime/BP/scripts/bedrock/combat-effects.js';
import {applyCustomEffect,clearCustomEffects,customEffectDiagnostics,pulseVision,handleTombRaider,TOMB_PICKUP_UNLOCK,pulseArdentHeat,ARDENT_COLLISION_COUNT,pulseHighHeels} from '../runtime/BP/scripts/bedrock/custom-effects.js';
import {consumeCocktail} from '../runtime/BP/scripts/bedrock/mixology.js';
const regs=startup();system.advance(2);const d=world.getDimension('overworld');let seq=0,online=[];world.getAllPlayers=()=>online;
const pos={x:0,y:64,z:0};
const hand=(p,id,n=1)=>p.inventory.setItem(p.selectedSlotIndex,id?typeof id==='string'?new ItemStack(id,n):id:undefined);
const count=(p,id)=>p.inventory.items.filter(v=>v?.typeId===id).reduce((a,b)=>a+b.amount,0);
function player(name){const p=new Player(name??'c6-'+(++seq),d);p.location={x:.5,y:65,z:2};p.health=mockHealth(20,20);p.exhaustion=mockHealth(0,20);p.hunger=mockHealth(20,20);p.saturation=mockHealth(5,20);online.push(p);return p;}
function stool(color='blue',p=player()){d.getBlock({...pos,y:63}).setType('minecraft:stone');hand(p,NS+':'+color+'_bar_stool',2);const b=placeFurniture(p,pos);p.selectedSlotIndex=1;hand(p,undefined);return {p,b,e:ensureSeat(b)};}
function light(color='colorless',p=player()){d.getBlock({...pos,y:63}).setType('minecraft:stone');hand(p,NS+':string_lights_'+color,2);const b=placeFurniture(p,pos);p.selectedSlotIndex=1;hand(p,undefined);return {p,b};}
function sofa(color='blue',p=player(),at=pos,yaw=0){d.getBlock({x:at.x,y:at.y-1,z:at.z}).setType('minecraft:stone');p.rotation.y=yaw;p.selectedSlotIndex=0;hand(p,NS+':'+color+'_sofa',2);const b=placeFurniture(p,at);p.selectedSlotIndex=1;hand(p,undefined);return {p,b};}
function table(p=player(),at=pos,yaw=0){p.rotation.y=yaw;p.selectedSlotIndex=0;hand(p,NS+':table',2);const b=placeFurniture(p,at);p.selectedSlotIndex=1;hand(p,undefined);return {p,b};}
function barCounter(p=player(),at=pos,yaw=0){p.rotation.y=yaw;p.selectedSlotIndex=0;hand(p,NS+':bar_counter',2);const b=placeFurniture(p,at);p.selectedSlotIndex=1;hand(p,undefined);return {p,b};}
function glasswareHolder(p=player(),at=pos,yaw=0){p.rotation.y=yaw;p.selectedSlotIndex=0;hand(p,NS+':glassware_holder',2);const b=placeFurniture(p,at);p.selectedSlotIndex=1;hand(p,undefined);return {p,b};}
function mob(p,{x=0,y=0,z=8,type='minecraft:zombie',health=100,extent=.3}={}){const h=p.getHeadLocation(),e=d.spawnEntity(type,{x:h.x+x,y:h.y+y-1,z:h.z+z});e.health=mockHealth(health,health);e.box={center:{x:h.x+x,y:h.y+y,z:h.z+z},extent:{x:extent,y:1,z:extent}};return e;}
function equipMob(e,item='minecraft:diamond_sword'){e._held=typeof item==='string'?new ItemStack(item,1):item?.clone();e.equippable={getEquipment:slot=>slot==='Mainhand'?e._held?.clone():undefined,setEquipment:(slot,value)=>{if(slot!=='Mainhand'||e.rejectEquipment)return false;e._held=value?.clone();return true;}};return e;}
function equipPlayer(p,entries={Head:'minecraft:iron_helmet'}){const worn=new Map(Object.entries(entries).map(([slot,item])=>[slot,typeof item==='string'?new ItemStack(item,1):item.clone()]));p._armor=worn;p.equippable={getEquipment:slot=>worn.get(slot)?.clone(),setEquipment:(slot,value)=>{if(p.rejectEquipment)return false;if(value)worn.set(slot,value.clone());else worn.delete(slot);return true;}};return p;}
function click(p,b,face='Up',faceLocation={x:.5,y:.5,z:.5}){const event={player:p,block:b,blockFace:face,faceLocation,isFirstEvent:true,cancel:false};world.beforeEvents.playerInteractWithBlock.emit(event);system.advance();return event;}
function full(p){for(let i=0;i<36;i++)p.inventory.setItem(i,new ItemStack('minecraft:stone',64));}
test.beforeEach(()=>{d.blocks.clear();d.entities.clear();d.unloaded.clear();d.failSpawn=false;d.failSpawnItem=false;d.failAudio=false;d.failParticles=false;d.sounds=[];d.particles=[];world.dp.clear();online=[];FURNITURE_TEST.helpers.clear();COMBAT_TEST.lastCast.clear();});
for(const c of COLORS)test('full place -> sit -> turn -> dismount -> recover '+c,()=>{const {p,b,e}=stool(c);assert.equal(count(p,NS+':'+c+'_bar_stool'),1);assert.equal(b.typeId,NS+':stool_'+c);assert.equal(e.typeId,seatId(c));assert.equal(sitOnFurniture(p,b),e);assert.equal(e.rideable.getRiders()[0],p);p.rotation.y=45;tickFurniture();assert.equal(e.getProperty(NS+':seat_yaw'),-135);assert.deepEqual(e.rotation,{x:0,y:180});p.isSneaking=true;tickFurniture();assert.equal(e.rideable.getRiders().length,0);recoverFurniture(p,b);assert(b.isAir);assert(e.removed);assert.equal(count(p,NS+':'+c+'_bar_stool'),2);});
for(const c of LIGHT_COLORS)test('place and recover exact light design '+c,()=>{const {p,b}=light(c);assert.equal(b.typeId,NS+':light_'+c);assert.equal(recoverFurniture(p,b),NS+':string_lights_'+c);assert(b.isAir);assert.equal(count(p,NS+':string_lights_'+c),2);});
test('three mixed-color sofas auto-connect as right-middle-left using source connection rules',()=>{const p=player(),a=sofa('blue',p,{x:0,y:64,z:0}).b,b=sofa('red',p,{x:1,y:64,z:0}).b,c=sofa('green',p,{x:-1,y:64,z:0}).b;assert.equal(c.permutation.getState(CONNECTION),SOFA_CONNECTION.RIGHT);assert.equal(a.permutation.getState(CONNECTION),SOFA_CONNECTION.MIDDLE);assert.equal(b.permutation.getState(CONNECTION),SOFA_CONNECTION.LEFT);});
test('perpendicular sofa front connection selects source corner geometry state',()=>{const p=player(),a=sofa('blue',p,{x:0,y:64,z:0},0).b,b=sofa('orange',p,{x:0,y:64,z:-1},90).b;assert.equal(a.permutation.getState(CONNECTION),SOFA_CONNECTION.RIGHT_CORNER);assert([SOFA_CONNECTION.LEFT_CORNER,SOFA_CONNECTION.RIGHT_CORNER,SOFA_CONNECTION.LEFT,SOFA_CONNECTION.RIGHT,SOFA_CONNECTION.SINGLE].includes(b.permutation.getState(CONNECTION)));});
test('sofa seat helper is lazy, one-rider, invisible helper and disappears after sneak dismount',()=>{const {p,b}=sofa();assert.equal([...d.entities.values()].filter(e=>e.typeId===SOFA_SEAT_ID).length,0);const e=sitOnFurniture(p,b);assert.equal(e.typeId,SOFA_SEAT_ID);assert.deepEqual(e.rideable.getRiders(),[p]);p.isSneaking=true;tickFurniture();assert(e.removed);assert.equal(p.ridingOn,undefined);p.isSneaking=false;recoverFurniture(p,b);assert(b.isAir);assert.equal(count(p,NS+':blue_sofa'),2);});
test('occupied sofa refuses recovery and removing middle sofa reconnects remaining pieces',()=>{const p=player(),left=sofa('blue',p,{x:-1,y:64,z:0}).b,mid=sofa('red',p,{x:0,y:64,z:0}).b,right=sofa('yellow',p,{x:1,y:64,z:0}).b;const q=player('sofa-rider');q.selectedSlotIndex=1;hand(q,undefined);sitOnFurniture(q,mid);assert.throws(()=>recoverFurniture(p,mid),x=>x.code==='SEAT_OCCUPIED');q.isSneaking=true;tickFurniture();recoverFurniture(p,mid);assert.equal(left.permutation.getState(CONNECTION),SOFA_CONNECTION.SINGLE);assert.equal(right.permutation.getState(CONNECTION),SOFA_CONNECTION.SINGLE);});
test('sofa tick repair recomputes externally stale connection state',()=>{const {b}=sofa();b.setPermutation(b.permutation.withState(CONNECTION,SOFA_CONNECTION.MIDDLE));assert(syncSofa(b));assert.equal(b.permutation.getState(CONNECTION),SOFA_CONNECTION.SINGLE);});
test('three Bar Counters reuse Sofa right-middle-left connection states',()=>{const p=player(),mid=barCounter(p,{x:0,y:64,z:0},0).b,east=barCounter(p,{x:1,y:64,z:0},0).b,west=barCounter(p,{x:-1,y:64,z:0},0).b;assert.equal(west.permutation.getState(CONNECTION),SOFA_CONNECTION.RIGHT);assert.equal(mid.permutation.getState(CONNECTION),SOFA_CONNECTION.MIDDLE);assert.equal(east.permutation.getState(CONNECTION),SOFA_CONNECTION.LEFT);});
test('perpendicular Bar Counter forms the same source corner state as Sofa',()=>{const p=player(),a=barCounter(p,{x:0,y:64,z:0},0).b,b=barCounter(p,{x:0,y:64,z:-1},90).b;assert.equal(a.permutation.getState(CONNECTION),SOFA_CONNECTION.RIGHT_CORNER);assert([SOFA_CONNECTION.LEFT_CORNER,SOFA_CONNECTION.RIGHT_CORNER,SOFA_CONNECTION.LEFT,SOFA_CONNECTION.RIGHT,SOFA_CONNECTION.SINGLE].includes(b.permutation.getState(CONNECTION)));});
test('removing middle Bar Counter reconnects both remaining ends and returns one item',()=>{const p=player(),mid=barCounter(p,{x:0,y:64,z:0},0).b,east=barCounter(p,{x:1,y:64,z:0},0).b,west=barCounter(p,{x:-1,y:64,z:0},0).b;const before=count(p,NS+':bar_counter');recoverFurniture(p,mid);assert(mid.isAir);assert.equal(west.permutation.getState(CONNECTION),SOFA_CONNECTION.SINGLE);assert.equal(east.permutation.getState(CONNECTION),SOFA_CONNECTION.SINGLE);assert.equal(count(p,NS+':bar_counter'),before+1);});
test('Bar Counter 20-tick repair collapses stale state without neighbors',()=>{const {b}=barCounter();b.setPermutation(b.permutation.withState(CONNECTION,SOFA_CONNECTION.MIDDLE));assert(syncBarCounter(b));assert.equal(b.permutation.getState(CONNECTION),SOFA_CONNECTION.SINGLE);});
test('Glassware Holder fills four exact quadrants and extracts into empty hand',()=>{const {p,b}=glasswareHolder();hand(p,NS+':empty_glassware',4);for(const q of[{x:.25,z:.25},{x:.75,z:.25},{x:.25,z:.75},{x:.75,z:.75}])assert(useGlasswareHolder(p,b,q));assert.equal(count(p,NS+':empty_glassware'),0);for(const st of GLASSWARE_SLOTS)assert.equal(b.permutation.getState(st),1);assert(useGlasswareHolder(p,b,{x:.75,z:.75}));assert.equal(count(p,NS+':empty_glassware'),1);assert.equal(b.permutation.getState(GLASSWARE_SLOTS[3]),0);});
test('Glassware Holder rejects occupied insert and metadata without loss',()=>{const {p,b}=glasswareHolder();hand(p,NS+':empty_glassware',2);assert(useGlasswareHolder(p,b,{x:.25,z:.25}));const n=count(p,NS+':empty_glassware');assert.equal(useGlasswareHolder(p,b,{x:.25,z:.25}),false);assert.equal(count(p,NS+':empty_glassware'),n);const custom=new ItemStack(NS+':empty_glassware',1);custom.nameTag='keep';hand(p,custom);assert.throws(()=>useGlasswareHolder(p,b,{x:.75,z:.25}),x=>x.code==='METADATA_ITEM_REJECTED');assert.equal(p.inventory.getItem(p.selectedSlotIndex).nameTag,'keep');});
test('Glassware Holder recovery returns all occupied glasses with holder',()=>{const {p,b}=glasswareHolder();hand(p,NS+':empty_glassware',3);for(const q of[{x:.25,z:.25},{x:.75,z:.25},{x:.25,z:.75}])assert(useGlasswareHolder(p,b,q));hand(p,undefined);const before=count(p,NS+':glassware_holder');recoverFurniture(p,b);assert(b.isAir);assert.equal(count(p,NS+':glassware_holder'),before+1);assert.equal(count(p,NS+':empty_glassware'),3);});
test('Glassware Holder event route uses faceLocation quadrant',()=>{const {p,b}=glasswareHolder();hand(p,NS+':empty_glassware',2);const e=click(p,b,'Down',{x:.8,y:.1,z:.2});assert(e.cancel);assert.equal(b.permutation.getState(GLASSWARE_SLOTS[1]),1);p.selectedSlotIndex=2;hand(p,undefined);click(p,b,'Down',{x:.8,y:.1,z:.2});assert.equal(b.permutation.getState(GLASSWARE_SLOTS[1]),0);});
test('three source tables form X-axis LEFT/MIDDLE/RIGHT and preserve exact model-state semantics',()=>{const p=player(),mid=table(p,{x:0,y:64,z:0},0).b,right=table(p,{x:1,y:64,z:0},0).b,left=table(p,{x:-1,y:64,z:0},0).b;assert.equal(left.permutation.getState(AXIS),TABLE_AXIS.X);assert.equal(left.permutation.getState(POSITION),TABLE_POSITION.LEFT);assert.equal(mid.permutation.getState(POSITION),TABLE_POSITION.MIDDLE);assert.equal(right.permutation.getState(POSITION),TABLE_POSITION.RIGHT);});
test('connected table row rejects perpendicular takeover while a standalone table can form a Z row',()=>{const p=player(),mid=table(p,{x:0,y:64,z:0},0).b;table(p,{x:1,y:64,z:0},0);table(p,{x:-1,y:64,z:0},0);const cross=table(p,{x:0,y:64,z:-1},90).b;assert.equal(mid.permutation.getState(AXIS),TABLE_AXIS.X);assert.equal(mid.permutation.getState(POSITION),TABLE_POSITION.MIDDLE);assert.equal(cross.permutation.getState(POSITION),TABLE_POSITION.SINGLE);const q=player('z-row'),a=table(q,{x:4,y:64,z:0},90).b,b=table(q,{x:4,y:64,z:-1},90).b;assert.equal(a.permutation.getState(AXIS),TABLE_AXIS.Z);assert.notEqual(a.permutation.getState(POSITION),TABLE_POSITION.SINGLE);assert.equal(b.permutation.getState(AXIS),TABLE_AXIS.Z);});
test('removing middle table reconnects both remaining ends to SINGLE and returns exactly one table',()=>{const p=player(),mid=table(p,{x:0,y:64,z:0},0).b,right=table(p,{x:1,y:64,z:0},0).b,left=table(p,{x:-1,y:64,z:0},0).b;const before=count(p,NS+':table');recoverFurniture(p,mid);assert(mid.isAir);assert.equal(left.permutation.getState(POSITION),TABLE_POSITION.SINGLE);assert.equal(right.permutation.getState(POSITION),TABLE_POSITION.SINGLE);assert.equal(count(p,NS+':table'),before+1);});
test('table 20-tick repair collapses stale connected state without a neighbor',()=>{const {b}=table();b.setPermutation(b.permutation.withState(AXIS,TABLE_AXIS.X).withState(POSITION,TABLE_POSITION.MIDDLE));assert(syncTable(b));assert.equal(b.permutation.getState(POSITION),TABLE_POSITION.SINGLE);});
test('before-event furniture route consumes1 from stack, no vanilla duplicate',()=>{const p=player();d.getBlock({...pos,y:63}).setType('minecraft:stone');p.isSneaking=true;hand(p,NS+':blue_bar_stool',16);const e=click(p,d.getBlock({...pos,y:63}));assert(e.cancel);assert.equal(d.getBlock(pos).typeId,NS+':stool_blue');assert.equal(count(p,NS+':blue_bar_stool'),15);});
test('other addon cancelled event is respected',()=>{const p=player();hand(p,NS+':blue_bar_stool');p.isSneaking=true;const e={player:p,block:d.getBlock({...pos,y:63}),blockFace:'Up',cancel:true};world.beforeEvents.playerInteractWithBlock.emit(e);system.advance();assert.equal(count(p,NS+':blue_bar_stool'),1);assert(d.getBlock(pos).isAir);});
test('repeat held-button before events do not double-place',()=>{const p=player();hand(p,NS+':blue_bar_stool',16);p.isSneaking=true;d.getBlock({...pos,y:63}).setType('minecraft:stone');const b=d.getBlock({...pos,y:63});world.beforeEvents.playerInteractWithBlock.emit({player:p,block:b,blockFace:'Up',cancel:false,isFirstEvent:false});system.advance();assert.equal(count(p,NS+':blue_bar_stool'),16);});
test('stale hand, metadata changes and changed dimensions do not place',()=>{const p=player();hand(p,NS+':blue_bar_stool',16);p.isSneaking=true;const b=d.getBlock({...pos,y:63});b.setType('minecraft:stone');world.beforeEvents.playerInteractWithBlock.emit({player:p,block:b,blockFace:'Up',isFirstEvent:true,cancel:false});const replacement=new ItemStack(NS+':blue_bar_stool',16);replacement.nameTag='do not lose';hand(p,replacement);system.advance();assert(d.getBlock(pos).isAir);assert.equal(p.inventory.getItem(0).nameTag,'do not lose');});
test('two players attempting same seat get one rider only',()=>{const {p,b,e}=stool();const q=player('second');sitOnFurniture(p,b);assert.throws(()=>sitOnFurniture(q,b),x=>x.code==='SEAT_OCCUPIED');assert.deepEqual(e.rideable.getRiders(),[p]);assert.equal(q.ridingOn,undefined);});
test('occupied stool cannot be mined or recovered, no item duplicated',()=>{const {p,b}=stool();const q=player();sitOnFurniture(p,b);assert.throws(()=>recoverFurniture(q,b),x=>x.code==='SEAT_OCCUPIED');assert.equal(count(q,NS+':blue_bar_stool'),0);const event={player:q,block:b,cancel:false};world.beforeEvents.playerBreakBlock.emit(event);system.advance();assert(event.cancel);assert.equal(b.typeId,NS+':stool_blue');});
test('riding a boat or horse is not interrupted by stool interaction',()=>{const {p,b}=stool();p.ridingOn=new Entity('minecraft:boat',d,p.location);assert.throws(()=>sitOnFurniture(p,b),x=>x.code==='ALREADY_RIDING');assert.equal(p.ridingOn.typeId,'minecraft:boat');});
test('native addRider rejection never fabricates success',()=>{const {p,b,e}=stool();e.rejectRider=true;const before=furnitureDiagnostics.seated;assert.throws(()=>sitOnFurniture(p,b),x=>x.code==='SEAT_REJECTED');assert.equal(furnitureDiagnostics.seated,before);assert.equal(e.rideable.getRiders().length,0);});
test('full inventory recovery keeps physical block and native helper',()=>{const {p,b,e}=stool();full(p);assert.throws(()=>recoverFurniture(p,b),x=>x.code==='INVENTORY_FULL');assert.equal(b.typeId,NS+':stool_blue');assert(!e.removed);});
test('two deferred break callbacks return one furniture item',()=>{const {p,b}=stool();for(let i=0;i<2;i++)world.beforeEvents.playerBreakBlock.emit({player:p,block:b,cancel:false});system.advance();assert.equal(count(p,NS+':blue_bar_stool'),2);assert(b.isAir);});
test('block write exception restores held stack, no helper spawned',()=>{const p=player();hand(p,NS+':red_bar_stool',16);d.getBlock({...pos,y:63}).setType('minecraft:stone');d.getBlock(pos).failSet=true;assert.throws(()=>placeFurniture(p,pos),/BLOCK_FAILURE/);assert.equal(count(p,NS+':red_bar_stool'),16);assert(d.getBlock(pos).isAir);assert.equal(d.entities.size,0);});
test('inventory write exception prevents block placement',()=>{const p=player();hand(p,NS+':red_bar_stool',16);d.getBlock({...pos,y:63}).setType('minecraft:stone');p.inventory.failAt=p.inventory.writes;assert.throws(()=>placeFurniture(p,pos),/WRITE_FAILURE/);assert.equal(count(p,NS+':red_bar_stool'),16);assert(d.getBlock(pos).isAir);});
test('helper failure leaves one recoverable block, reconstructs without paying twice',()=>{const p=player();hand(p,NS+':red_bar_stool',2);d.getBlock({...pos,y:63}).setType('minecraft:stone');d.failSpawn=true;const b=placeFurniture(p,pos);assert.equal(count(p,NS+':red_bar_stool'),1);assert.equal(b.typeId,NS+':stool_red');d.failSpawn=false;regs.blocks.get(NS+':stool').onTick({block:b});assert.equal(d.entities.size,1);recoverFurniture(p,b);assert.equal(count(p,NS+':red_bar_stool'),2);});
test('lost helper reconstructed from block without world DP inventory state',()=>{const {p,b,e}=stool();e.remove();FURNITURE_TEST.helpers.clear();const next=ensureSeat(b);assert.notEqual(next.id,e.id);assert.equal(count(p,NS+':blue_bar_stool'),1);assert.equal(next.getDynamicProperty(SEAT_ANCHOR),anchorKey(d.id,pos));});
test('occupied duplicate wins and empty duplicate cannot drop another stool',()=>{const {p,b,e}=stool();sitOnFurniture(p,b);const copy=d.spawnEntity(seatId('blue'),e.location);copy.setDynamicProperty(SEAT_ANCHOR,anchorKey(d.id,pos));assert.equal(ensureSeat(b),e);assert(copy.removed);assert.equal(count(p,NS+':blue_bar_stool'),1);assert.deepEqual(e.rideable.getRiders(),[p]);});
test('unloaded block is not considered air and does not eject or delete helper',()=>{const {p,b,e}=stool();sitOnFurniture(p,b);d.unloaded.add('0_64_0');maintainSeat(e);assert(!e.removed);assert.equal(e.rideable.getRiders()[0],p);});
test('external command replacing stool ejects rider, removes helper, no item minted',()=>{const {p,b,e}=stool();sitOnFurniture(p,b);b.setType('minecraft:stone');maintainSeat(e);assert(e.removed);assert.equal(p.ridingOn,undefined);assert.equal(count(p,NS+':blue_bar_stool'),1);assert.equal(b.typeId,'minecraft:stone');});
test('unanchored manually summoned helper is deleted rather than becoming a free chair',()=>{const e=d.spawnEntity(seatId('blue'),pos);world.afterEvents.entityLoad.emit({entity:e});system.advance();assert(e.removed);});
test('no support or obstructed headroom rejects stool without consumption',()=>{const p=player();hand(p,NS+':blue_bar_stool');assert.throws(()=>placeFurniture(p,pos),x=>x.code==='NEEDS_SOLID_SUPPORT');d.getBlock({...pos,y:63}).setType('minecraft:stone');d.getBlock({...pos,y:65}).setType('minecraft:stone');assert.throws(()=>placeFurniture(p,pos),x=>x.code==='SEAT_HEADROOM');assert.equal(count(p,NS+':blue_bar_stool'),1);});
test('sitting rechecks changed headroom and support',()=>{const {p,b}=stool();d.getBlock({...pos,y:65}).setType('minecraft:stone');assert.throws(()=>sitOnFurniture(p,b),x=>x.code==='SEAT_HEADROOM');d.getBlock({...pos,y:65}).setType('minecraft:air');d.getBlock({...pos,y:63}).setType('minecraft:air');assert.throws(()=>sitOnFurniture(p,b),x=>x.code==='NEEDS_SOLID_SUPPORT');recoverFurniture(p,b);assert(b.isAir);});
test('dye switches full design and preserves facing; same color costs nothing',()=>{const {p,b}=light('red');b.setPermutation(b.permutation.withState(FACING,3));hand(p,'minecraft:green_dye',16);assert(recolorLight(p,b));assert.equal(count(p,'minecraft:green_dye'),15);assert.equal(b.typeId,NS+':light_green');assert.equal(b.permutation.getState(FACING),3);assert.equal(recolorLight(p,b),false);assert.equal(count(p,'minecraft:green_dye'),15);assert.equal(count(p,NS+':string_lights_red'),1);});
test('dye write failure restores16 dyes and old light variant',()=>{const {p,b}=light('red');hand(p,'minecraft:green_dye',16);b.failSet=true;assert.throws(()=>recolorLight(p,b),/BLOCK_FAILURE/);assert.equal(count(p,'minecraft:green_dye'),16);assert.equal(b.typeId,NS+':light_red');});
test('source metadata dye rejected with source stack preserved',()=>{const {p,b}=light('red');const dye=new ItemStack('minecraft:green_dye',16);dye.nameTag='label';hand(p,dye);assert.throws(()=>recolorLight(p,b),x=>x.code==='METADATA_ITEM_REJECTED');assert.equal(p.inventory.getItem(p.selectedSlotIndex).nameTag,'label');assert.equal(b.typeId,NS+':light_red');});
test('creative furniture still consumes real placed item and returns one',()=>{const p=player();p.mode=GameMode.Creative;const {b}=stool('blue',p);assert.equal(count(p,NS+':blue_bar_stool'),1);recoverFurniture(p,b);assert.equal(count(p,NS+':blue_bar_stool'),2);});
test('spectator/adventure cannot place/sit/recover furniture',()=>{const {p,b}=stool();for(const mode of[GameMode.Adventure,GameMode.Spectator]){p.mode=mode;assert.throws(()=>sitOnFurniture(p,b),x=>x.code==='GAME_MODE_LOCKED');assert.throws(()=>recoverFurniture(p,b),x=>x.code==='GAME_MODE_LOCKED');}});
test('explosion protection leaves unrelated blocks in impacted list',()=>{const {b}=light();const vanilla=d.getBlock({x:1,y:64,z:0});vanilla.setType('minecraft:stone');let out=[b,vanilla];world.beforeEvents.explosion.emit({getImpactedBlocks:()=>out,setImpactedBlocks:v=>out=v});assert.deepEqual(out,[vanilla]);});
test('Shriek completed drink applies source damage, additive impulse and16 particles',()=>{const p=player();p.health=mockHealth(10,20);const e=mob(p);e.velocity={x:1,y:-.5,z:2};hand(p,NS+':sculk_special',16);const before=p.inventory.getItem(0);const out=consumeCocktail({source:p,itemStack:before},()=>0);assert.equal(out[0].status,'APPLIED_CUSTOM');assert.equal(e.damageCalls[0].amount,12);assert.equal(e.damageCalls[0].opts.cause,'sonicBoom');assert.equal(e.damageCalls[0].opts.damagingEntity,p);assert.equal(e.velocity.x,1);assert(Math.abs(e.velocity.y+.22)<1e-12);assert.equal(e.velocity.z,2.63);assert.equal(d.particles.length,16);assert.equal(d.particles[0].id,'minecraft:sonic_explosion');assert.deepEqual(p.inventory.getItem(0),before);assert.equal(count(p,NS+':empty_glassware'),0);});
test('Shriek source rules hit in corridor only and do not stop at walls',()=>{const p=player(),hit=mob(p,{z:30}),rear=mob(p,{z:-5}),far=mob(p,{z:32.01}),side=mob(p,{x:1.31,z:8});d.getBlock({x:0,y:66,z:5}).setType('minecraft:stone');performShriek(p);assert.equal(hit.damageCalls.length,1);assert.equal(rear.damageCalls,undefined);assert.equal(far.damageCalls,undefined);assert.equal(side.damageCalls,undefined);assert.equal(d.getBlock({x:0,y:66,z:5}).typeId,'minecraft:stone');});
test('PvE only excludes players, own helpers, XP orbs and dead mobs',()=>{const p=player(),q=player('friend');q.location={...p.location,z:8};d.entities.set(q.id,q);const helper=mob(p,{type:seatId('blue')}),orb=d.spawnEntity('minecraft:xp_orb',{...p.location,z:8}),dead=mob(p,{health:0});performShriek(p);assert.equal(q.health.currentValue,20);assert.equal(helper.damageCalls,undefined);assert.equal(orb.damageCalls,undefined);assert.equal(dead.damageCalls,undefined);});
test('rejected native damage produces no forced HP change or knockback',()=>{const p=player(),e=mob(p);e.rejectDamage=true;e.velocity={x:1,y:2,z:3};performShriek(p);assert.equal(e.health.currentValue,100);assert.deepEqual(e.velocity,{x:1,y:2,z:3});});
test('bad target and cosmetic failures do not repeat attack or cancel later target',()=>{const p=player(),bad=mob(p,{z:3}),good=mob(p,{z:8});bad.failDamage=true;d.failAudio=true;d.failParticles=true;performShriek(p);assert.equal(good.damageCalls.length,1);assert(combatDiagnostics.errors.length<=16);});
test('missing engine AABB capability skips unsupported target, not guessed hitbox',()=>{const p=player(),e=mob(p);e.getAABB=undefined;const old=combatDiagnostics.missingAabb;performShriek(p);assert.equal(e.damageCalls,undefined);assert.equal(combatDiagnostics.missingAabb,old+1);});
test('duplicate same-tick callback does not damage twice or repeat particles',()=>{const p=player(),e=mob(p);performShriek(p);performShriek(p);assert.equal(e.damageCalls.length,1);assert.equal(d.particles.length,16);system.advance();performShriek(p);assert.equal(e.damageCalls.length,2);});
test('dead or locked source produces no sonic attack',()=>{const p=player(),e=mob(p);p.health.currentValue=0;assert.equal(performShriek(p),false);p.health.currentValue=20;p.mode=GameMode.Spectator;assert.equal(performShriek(p),false);assert.equal(e.damageCalls,undefined);});
test('wide-target halfwidth expands hit radius, diagonal source uses full ray',()=>{const p=player();const big=mob(p,{x:2.5,z:8,extent:2});performShriek(p);assert.equal(big.damageCalls.length,1);});
test('target cap bounds damage to256, records truncation, no invulnerability bypass',()=>{const p=player();const mobs=Array.from({length:270},(_,i)=>mob(p,{z:3+i*.001}));performShriek(p);assert.equal(mobs.filter(e=>e.damageCalls).length,256);assert(combatDiagnostics.cappedQueries>0);});
test('Shriek applied through signature/custom dispatcher is instant, no saved timer',()=>{const p=player(),e=mob(p);assert(applyCustomEffect(p,{effect:NS+':shriek_attack',duration:1,amplifier:0}));assert.equal(e.damageCalls.length,1);assert.equal(p.getDynamicProperty(NS+':custom_effects'),undefined);});
test('Screwdriver upside-down renames only alive mobs inside Java-style inflated AABB and stays instant',()=>{const p=player(),near=mob(p,{z:16.5}),far=mob(p,{z:16.61}),dead=mob(p,{z:8,health:0}),q=player('upside-friend');q.location={...p.location,z:p.location.z+8};q.health=mockHealth(20,20);q.box={center:{x:q.location.x,y:q.location.y+1,z:q.location.z},extent:{x:.3,y:1,z:.3}};d.entities.set(q.id,q);hand(p,NS+':screwdriver');const before=customEffectDiagnostics.upsideDownRenames;const out=consumeCocktail({source:p,itemStack:p.inventory.getItem(0)},()=>0);assert.equal(out[0].status,'APPLIED_CUSTOM');assert.equal(near.nameTag,'Grumm');assert.equal(far.nameTag,undefined);assert.equal(dead.nameTag,undefined);assert.equal(q.nameTag,undefined);assert.equal(p.getDynamicProperty(NS+':custom_effects'),undefined);assert.equal(customEffectDiagnostics.upsideDownRenames,before+1);});
test('Mojito Vision persists then refreshes Glowing on Java 50-tick countdown boundaries',()=>{const p=player(),near=mob(p,{z:5}),q=player('vision-friend');q.location={...p.location,z:p.location.z+4};q.health=mockHealth(20,20);q.box={center:{x:q.location.x,y:q.location.y+1,z:q.location.z},extent:{x:.3,y:1,z:.3}};d.entities.set(q.id,q);hand(p,NS+':mojito');const out=consumeCocktail({source:p,itemStack:p.inventory.getItem(0)},()=>0);assert.equal(out[0].status,'APPLIED_CUSTOM');const saved=JSON.parse(p.getDynamicProperty(NS+':custom_effects'));assert(saved.entries.some(e=>e.id===NS+':vision'&&e.ticks===36000&&e.amplifier===0));const before=customEffectDiagnostics.visionPulses;system.advance(5);assert(customEffectDiagnostics.visionPulses>before);assert.equal(near.getEffect('glowing').ticks,60);assert.equal(q.getEffect('glowing').ticks,60);assert(d.sounds.some(s=>s.id==='kt_assets_a17.effect.vision'));const sounds=d.sounds.length;system.advance(50);assert.equal(d.sounds.length,sounds);});
test('Vision radius caps at18 and excludes dead self outside and Tavern helpers',()=>{const p=player(),edge=mob(p,{x:18.2,z:0}),touch=mob(p,{x:18.6,z:0}),outside=mob(p,{x:18.61,z:0}),dead=mob(p,{x:3,z:0,health:0}),helper=mob(p,{x:3,z:0,type:seatId('blue')});const sounds=d.sounds.length,n=pulseVision(p,2);assert.equal(n,1);assert.equal(edge.getEffect('glowing').ticks,60);assert.equal(touch.getEffect('glowing'),undefined);assert.equal(outside.getEffect('glowing'),undefined);assert.equal(dead.getEffect('glowing'),undefined);assert.equal(helper.getEffect('glowing'),undefined);assert.equal(p.getEffect('glowing'),undefined);assert.equal(d.sounds.length,sounds+1);});
test('Nether Special Tomb Raider disarms eligible mob, wears item to1 durability and enforces40tick pickup delay',()=>{const p=player(),target=equipMob(mob(p,{type:'minecraft:pillager',z:3}));target._held.nameTag='source weapon';assert(applyCustomEffect(p,{effect:NS+':tomb_raider',duration:90,amplifier:0}));const before=system.currentTick;assert(handleTombRaider({hurtEntity:target,damageSource:{damagingEntity:p}},()=>.299));assert.equal(target._held,undefined);const drop=[...d.entities.values()].find(e=>e.typeId==='minecraft:item');assert(drop);const stack=drop.getComponent('minecraft:item').itemStack,dur=stack.getComponent('minecraft:durability');assert.equal(stack.typeId,'minecraft:diamond_sword');assert.equal(stack.nameTag,'source weapon');assert.equal(dur.damage,dur.maxDurability-1);assert.equal(drop.getDynamicProperty(TOMB_PICKUP_UNLOCK),before+40);let ev={entity:p,item:drop,cancel:false};world.beforeEvents.entityItemPickup.emit(ev);assert(ev.cancel);system.advance(39);ev={entity:p,item:drop,cancel:false};world.beforeEvents.entityItemPickup.emit(ev);assert(ev.cancel);system.advance(1);ev={entity:p,item:drop,cancel:false};world.beforeEvents.entityItemPickup.emit(ev);assert.equal(ev.cancel,false);});
test('Tomb Raider excludes non-source mobs and Java 0.3F boundary does not proc',()=>{const p=player(),creeper=equipMob(mob(p,{type:'minecraft:creeper'})),pillager=equipMob(mob(p,{type:'minecraft:pillager',z:4}));assert(applyCustomEffect(p,{effect:NS+':tomb_raider',duration:90,amplifier:0}));assert.equal(handleTombRaider({hurtEntity:creeper,damageSource:{damagingEntity:p}},()=>0),false);assert.equal(handleTombRaider({hurtEntity:pillager,damageSource:{damagingEntity:p}},()=>.3),false);assert.equal(creeper._held.typeId,'minecraft:diamond_sword');assert.equal(pillager._held.typeId,'minecraft:diamond_sword');assert.equal([...d.entities.values()].filter(e=>e.typeId==='minecraft:item').length,0);});
test('Tomb Raider spawn failure restores original mainhand instead of deleting it',()=>{const p=player(),target=equipMob(mob(p,{type:'minecraft:wither_skeleton'}));target._held.nameTag='keep me';const original=target._held.clone();assert(applyCustomEffect(p,{effect:NS+':tomb_raider',duration:90,amplifier:0}));d.failSpawnItem=true;assert.equal(handleTombRaider({hurtEntity:target,damageSource:{damagingEntity:p}},()=>0),false);assert.deepEqual(target._held,original);assert.equal([...d.entities.values()].filter(e=>e.typeId==='minecraft:item').length,0);d.failSpawnItem=false;});
test('Depth Charge and Brass Heart both persist source 300-second Ardent Heat',()=>{for(const id of[NS+':depth_charge',NS+':brass_heart']){const p=player();hand(p,id);const out=consumeCocktail({source:p,itemStack:p.inventory.getItem(0)},()=>0);assert.equal(out[0].status,'APPLIED_CUSTOM');const saved=JSON.parse(p.getDynamicProperty(NS+':custom_effects'));assert(saved.entries.some(e=>e.id===NS+':ardent_heat'&&e.ticks===6000&&e.amplifier===0));}});
test('Ardent Heat sprint breaks exact front-plane source stones, maps vanilla drops and charges exhaustion once',()=>{const p=player();assert(applyCustomEffect(p,{effect:NS+':ardent_heat',duration:300,amplifier:0}));p.isSprinting=true;d.getBlock({x:-1,y:65,z:3}).setType('minecraft:stone');d.getBlock({x:0,y:66,z:3}).setType('minecraft:deepslate');d.getBlock({x:1,y:67,z:3}).setType('minecraft:cobblestone');const n=pulseArdentHeat(p,()=>0);assert.equal(n,2);assert(d.getBlock({x:-1,y:65,z:3}).isAir);assert(d.getBlock({x:0,y:66,z:3}).isAir);assert.equal(d.getBlock({x:1,y:67,z:3}).typeId,'minecraft:cobblestone');const drops=[...d.entities.values()].filter(e=>e.typeId==='minecraft:item').map(e=>e.getComponent('minecraft:item').itemStack.typeId).sort();assert.deepEqual(drops,['minecraft:cobbled_deepslate','minecraft:cobblestone']);assert(Math.abs(p.exhaustion.currentValue-1.2)<1e-12);});
test('Ardent Heat damages one randomly selected worn armor item once per successful sprint collision tick',()=>{const p=equipPlayer(player());assert(applyCustomEffect(p,{effect:NS+':ardent_heat',duration:300,amplifier:0}));p.isSprinting=true;d.getBlock({x:0,y:65,z:3}).setType('minecraft:basalt');assert.equal(pulseArdentHeat(p,()=>0),1);const helmet=p._armor.get('Head'),dur=helmet.getComponent('minecraft:durability');assert.equal(dur.damage,1);assert.equal(p.health.currentValue,20);});
test('Ardent Heat bare collision counter deals one generic damage every fifth successful tick',()=>{const p=player();assert(applyCustomEffect(p,{effect:NS+':ardent_heat',duration:300,amplifier:0}));p.isSprinting=true;for(let i=0;i<5;i++){d.getBlock({x:0,y:65,z:3}).setType('minecraft:blackstone');assert.equal(pulseArdentHeat(p,()=>0),1);}assert.equal(p.health.currentValue,19);assert.equal(p.getDynamicProperty(ARDENT_COLLISION_COUNT),0);assert.equal(p.damageCalls.length,1);});
test('Ardent Heat item-spawn failure restores the source block and does not charge collision costs',()=>{const p=player();assert(applyCustomEffect(p,{effect:NS+':ardent_heat',duration:300,amplifier:0}));p.isSprinting=true;const b=d.getBlock({x:0,y:65,z:3});b.setType('minecraft:end_stone');d.failSpawnItem=true;assert.equal(pulseArdentHeat(p,()=>0),0);assert.equal(b.typeId,'minecraft:end_stone');assert.equal(p.exhaustion.currentValue,0);assert.equal(p.getDynamicProperty(ARDENT_COLLISION_COUNT),undefined);assert.equal([...d.entities.values()].filter(e=>e.typeId==='minecraft:item').length,0);});
test('Ardent Heat natural expiry and zero hunger+saturation both add source 600-tick Hunger',()=>{const p=player();assert(applyCustomEffect(p,{effect:NS+':ardent_heat',duration:1,amplifier:0}));system.advance(20);assert.equal(p.getEffect('hunger').ticks,600);assert.equal(p.getDynamicProperty(NS+':custom_effects'),undefined);const q=player();q.hunger.setCurrentValue(0);q.saturation.setCurrentValue(0);assert(applyCustomEffect(q,{effect:NS+':ardent_heat',duration:300,amplifier:0}));system.advance(5);assert.equal(q.getEffect('hunger').ticks,600);assert.equal(q.getDynamicProperty(NS+':custom_effects'),undefined);});
test('White Lady High Heels persists source 3600 seconds and climbs one blocked one-block obstacle',()=>{const p=player();hand(p,NS+':white_lady');const out=consumeCocktail({source:p,itemStack:p.inventory.getItem(0)},()=>0);assert.equal(out[0].status,'APPLIED_CUSTOM');const saved=JSON.parse(p.getDynamicProperty(NS+':custom_effects'));assert(saved.entries.some(e=>e.id===NS+':high_heels'&&e.ticks===72000&&e.amplifier===0));p.location={x:.5,y:65,z:2.7};p.inputInfo.movement={x:0,y:1};p.velocity={x:0,y:0,z:0};d.getBlock({x:0,y:65,z:3}).setType('minecraft:stone');const before=customEffectDiagnostics.highHeelsSteps;assert(pulseHighHeels(p));assert.equal(p.location.y,66);assert(Math.abs(p.location.z-2.9)<1e-12);assert.equal(customEffectDiagnostics.highHeelsSteps,before+1);});
test('High Heels refuses normal motion, jumping, two-block walls and repeated vertical wall climbing',()=>{const p=player();assert(applyCustomEffect(p,{effect:NS+':high_heels',duration:100,amplifier:0}));p.location={x:.5,y:65,z:2.7};p.inputInfo.movement={x:0,y:1};d.getBlock({x:0,y:65,z:3}).setType('minecraft:stone');p.velocity={x:0,y:0,z:.1};assert.equal(pulseHighHeels(p),false);p.velocity={x:0,y:0,z:0};p.isJumping=true;assert.equal(pulseHighHeels(p),false);p.isJumping=false;d.getBlock({x:0,y:66,z:3}).setType('minecraft:stone');assert.equal(pulseHighHeels(p),false);d.getBlock({x:0,y:66,z:3}).setType('minecraft:air');assert(pulseHighHeels(p));d.getBlock({x:0,y:66,z:3}).setType('minecraft:stone');d.getBlock({x:0,y:67,z:3}).setType('minecraft:air');d.getBlock({x:0,y:68,z:3}).setType('minecraft:air');assert.equal(pulseHighHeels(p),false);assert.equal(p.location.y,66);});
test('remaining unsupported effects are still not substituted with arbitrary buffs',()=>{for(const id of['slightly_tipsy','grass_stealth','long_reach']){const p=player();assert.equal(applyCustomEffect(p,{effect:NS+':'+id,duration:100,amplifier:0}),false);assert.equal(p.effects.length,0);}});
test('independent guide includes new furniture/effect pages; recipe API count stays41',()=>{assert.equal(runtimeRegistry().allRecipes().length,41);const ids=runtimeRegistry().allPages().map(x=>x.id);assert(ids.includes(NS+':c6_furniture'));assert(ids.includes(NS+':c6_sonic'));assert.equal(diagnosticSnapshot().build,'C6 / 0.6.0');assert.equal(diagnosticSnapshot().independentGuidebook,true);});
