/** Full C6 adapter calls on deterministic API doubles, NOT Minecraft/Realms/player animation tests. */
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import './c6-fixtures.js';
import {world,system,startup,Player,Entity,ItemStack,GameMode,BlockPermutation,mockHealth} from './fake-server.js';
import {runtimeRegistry,diagnosticSnapshot} from '../runtime/BP/scripts/main.js';
import {placeFurniture,sitOnFurniture,recoverFurniture,recolorLight,ensureSeat,maintainSeat,tickFurniture,FURNITURE_TEST,furnitureDiagnostics} from '../runtime/BP/scripts/bedrock/furniture.js';
import {NS,COLORS,LIGHT_COLORS,FACING,SEAT_ANCHOR,anchorKey,seatId} from '../runtime/BP/scripts/core/furniture.js';
import {performShriek,COMBAT_TEST,combatDiagnostics} from '../runtime/BP/scripts/bedrock/combat-effects.js';
import {applyCustomEffect,clearCustomEffects,customEffectDiagnostics} from '../runtime/BP/scripts/bedrock/custom-effects.js';
import {consumeCocktail} from '../runtime/BP/scripts/bedrock/mixology.js';
const regs=startup();system.advance(2);const d=world.getDimension('overworld');let seq=0,online=[];world.getAllPlayers=()=>online;
const pos={x:0,y:64,z:0};
const hand=(p,id,n=1)=>p.inventory.setItem(p.selectedSlotIndex,id?typeof id==='string'?new ItemStack(id,n):id:undefined);
const count=(p,id)=>p.inventory.items.filter(v=>v?.typeId===id).reduce((a,b)=>a+b.amount,0);
function player(name){const p=new Player(name??'c6-'+(++seq),d);p.location={x:.5,y:65,z:2};p.health=mockHealth(20,20);online.push(p);return p;}
function stool(color='blue',p=player()){d.getBlock({...pos,y:63}).setType('minecraft:stone');hand(p,NS+':'+color+'_bar_stool',2);const b=placeFurniture(p,pos);p.selectedSlotIndex=1;hand(p,undefined);return {p,b,e:ensureSeat(b)};}
function light(color='colorless',p=player()){d.getBlock({...pos,y:63}).setType('minecraft:stone');hand(p,NS+':string_lights_'+color,2);const b=placeFurniture(p,pos);p.selectedSlotIndex=1;hand(p,undefined);return {p,b};}
function mob(p,{x=0,y=0,z=8,type='minecraft:zombie',health=100,extent=.3}={}){const h=p.getHeadLocation(),e=d.spawnEntity(type,{x:h.x+x,y:h.y+y-1,z:h.z+z});e.health=mockHealth(health,health);e.box={center:{x:h.x+x,y:h.y+y,z:h.z+z},extent:{x:extent,y:1,z:extent}};return e;}
function click(p,b,face='Up'){const event={player:p,block:b,blockFace:face,isFirstEvent:true,cancel:false};world.beforeEvents.playerInteractWithBlock.emit(event);system.advance();return event;}
function full(p){for(let i=0;i<36;i++)p.inventory.setItem(i,new ItemStack('minecraft:stone',64));}
test.beforeEach(()=>{d.blocks.clear();d.entities.clear();d.unloaded.clear();d.failSpawn=false;d.failAudio=false;d.failParticles=false;d.sounds=[];d.particles=[];world.dp.clear();online=[];FURNITURE_TEST.helpers.clear();COMBAT_TEST.lastCast.clear();});
for(const c of COLORS)test('full place -> sit -> turn -> dismount -> recover '+c,()=>{const {p,b,e}=stool(c);assert.equal(count(p,NS+':'+c+'_bar_stool'),1);assert.equal(b.typeId,NS+':stool_'+c);assert.equal(e.typeId,seatId(c));assert.equal(sitOnFurniture(p,b),e);assert.equal(e.rideable.getRiders()[0],p);p.rotation.y=45;tickFurniture();assert.equal(e.getProperty(NS+':seat_yaw'),-135);assert.deepEqual(e.rotation,{x:0,y:180});p.isSneaking=true;tickFurniture();assert.equal(e.rideable.getRiders().length,0);recoverFurniture(p,b);assert(b.isAir);assert(e.removed);assert.equal(count(p,NS+':'+c+'_bar_stool'),2);});
for(const c of LIGHT_COLORS)test('place and recover exact light design '+c,()=>{const {p,b}=light(c);assert.equal(b.typeId,NS+':light_'+c);assert.equal(recoverFurniture(p,b),NS+':string_lights_'+c);assert(b.isAir);assert.equal(count(p,NS+':string_lights_'+c),2);});
test('before-event furniture route consumes1 from stack, no vanilla duplicate',()=>{const p=player();d.getBlock({...pos,y:63}).setType('minecraft:stone');p.isSneaking=true;hand(p,NS+':blue_bar_stool',16);const e=click(p,d.getBlock({...pos,y:63}));assert(e.cancel);assert.equal(d.getBlock(pos).typeId,NS+':stool_blue');assert.equal(count(p,NS+':blue_bar_stool'),15);});
test('other addon cancelled event is respected',()=>{const p=player();hand(p,NS+':blue_bar_stool');p.isSneaking=true;const e={player:p,block:d.getBlock({...pos,y:63}),blockFace:'Up',cancel:true};world.beforeEvents.playerInteractWithBlock.emit(e);system.advance();assert.equal(count(p,NS+':blue_bar_stool'),1);assert(d.getBlock(pos).isAir);});
test('repeat held-button before events do not double-place',()=>{const p=player();hand(p,NS+':blue_bar_stool',16);p.isSneaking=true;d.getBlock({...pos,y:63}).setType('minecraft:stone');const b=d.getBlock({...pos,y:63});world.beforeEvents.playerInteractWithBlock.emit({player:p,block:b,blockFace:'Up',cancel:false,isFirstEvent:false});system.advance();assert.equal(count(p,NS+':blue_bar_stool'),16);});
test('stale hand, metadata changes and changed dimensions do not place',()=>{const p=player();hand(p,NS+':blue_bar_stool',16);p.isSneaking=true;const b=d.getBlock({...pos,y:63});b.setType('minecraft:stone');world.beforeEvents.playerInteractWithBlock.emit({player:p,block:b,blockFace:'Up',isFirstEvent:true,cancel:false});const replacement=new ItemStack(NS+':blue_bar_stool',16);replacement.nameTag='do not lose';hand(p,replacement);system.advance();assert(d.getBlock(pos).isAir);assert.equal(p.inventory.getItem(0).nameTag,'do not lose');});
test('two players attempting same seat get one rider only',()=>{const {p,b,e}=stool();const q=player('second');sitOnFurniture(p,b);assert.throws(()=>sitOnFurniture(q,b),x=>x.code==='SEAT_OCCUPIED');assert.deepEqual(e.rideable.getRiders(),[p]);assert.equal(q.ridingOn,undefined);});
test('occupied stool cannot be mined or recovered, no item duplicated',()=>{const {p,b}=stool();const q=player();sitOnFurniture(p,b);assert.throws(()=>recoverFurniture(q,b),x=>x.code==='SEAT_OCCUPIED');assert.equal(count(q,NS+':blue_bar_stool'),0);const event={player:q,block:b,cancel:false};world.beforeEvents.playerBreakBlock.emit(event);system.advance();assert(event.cancel);assert.equal(b.typeId,NS+':stool_blue');});
test('riding a boat or horse is not interrupted by stool interaction',()=>{const {p,b}=stool();p.ridingOn=new Entity('minecraft:boat',d,p.location);assert.throws(()=>sitOnFurniture(p,b),x=>x.code==='ALREADY_RIDING');assert.equal(p.ridingOn.typeId,'minecraft:boat');});
test('native addRider rejection never fabricates success',()=>{const {p,b,e}=stool();e.rejectRider=true;const before=furnitureDiagnostics.seated;assert.throws(()=>sitOnFurniture(p,b),x=>x.code==='SEAT_REJECTED');assert.equal(furnitureDiagnostics.seated,before);assert.equal(e.rideable.getRiders().length,0);});
test('full inventory recovery keeps physical block and native helper',()=>{const {p,b,e}=stool();full(p);assert.throws(()=>recoverFurniture(p,b),x=>x.code==='INVENTORY_FULL');assert.equal(b.typeId,NS+':stool_blue');assert(!e.removed);});
test('two deferred break callbacks return one furniture item',()=>{const {p,b}=stool();for(let i=0;i<2;i++)world.beforeEvents.playerBreakBlock.emit({player:p,block:b,cancel:false});system.advance();assert.equal(count(p,NS+':blue_bar_stool'),2);assert(b.isAir);});
test('block write exception restores held stack, no helper spawned',()=>{const p=player();hand(p,NS+':red_bar_stool',16);d.getBlock({...pos,y:63}).setType('minecraft:stone');d.getBlock(pos).failSet=true;assert.throws(()=>placeFurniture(p,pos),/BLOCK_FAILURE/);assert.equal(count(p,NS+':red_bar_stool'),16);assert(d.getBlock(pos).isAir);assert.equal(d.entities.size,0);});
test('inventory write exception prevents block placement',()=>{const p=player();hand(p,NS+':red_bar_stool',16);d.getBlock({...pos,y:63}).setType('minecraft:stone');p.inventory.failAt=p.inventory.writes;assert.throws(()=>placeFurniture(p,pos),/WRITE_FAILURE/);assert.equal(count(p,NS+':red_bar_stool'),16);assert(d.getBlock(pos).isAir);});
test('helper failure leaves one recoverable block, reconstructs without paying twice',()=>{const p=player();hand(p,NS+':red_bar_stool',2);d.getBlock({...pos,y:63}).setType('minecraft:stone');d.failSpawn=true;const b=placeFurniture(p,pos);assert.equal(count(p,NS+':red_bar_stool'),1);assert.equal(b.typeId,NS+':stool_red');d.failSpawn=false;regs.blocks.get(NS+':stool').onTick({block:b});assert.equal(d.entities.size,1);recoverFurniture(p,b);assert.equal(count(p,NS+':red_bar_stool'),2);});
test('lost helper reconstructed from block without world DP inventory state',()=>{const {p,b,e}=stool();e.remove();FURNITURE_TEST.helpers.clear();const next=ensureSeat(b);assert.notEqual(next.id,e.id);assert.equal(count(p,NS+':blue_bar_stool'),1);assert.equal(next.getDynamicProperty(SEAT_ANCHOR),anchorKey(d.id,pos));});
test('occupied duplicate wins and empty duplicate cannot drop another stool',()=>{const {p,b,e}=stool();sitOnFurniture(p,b);const copy=d.spawnEntity(seatId('blue'),e.location);copy.setDynamicProperty(SEAT_ANCHOR,anchorKey(d.id,pos));assert.equal(ensureSeat(b),e);assert(copy.removed);assert.equal(count(p,NS+':blue_bar_stool'),1);assert.deepEqual(e.rideable.getRiders(),[p]);});
test('unloaded block is not considered air and does not eject or delete helper',()=>{const {p,b,e}=stool();sitOnFurniture(p,b);d.unloaded.add('0_64_0');maintainSeat(e);assert(!e.removed);assert.equal(e.rideable.getRiders()[0],p);});
test('external command replacing stool ejects rider, removes helper, no item minted',()=>{const {p,b,e}=stool();sitOnFurniture(p,b);b.setType('minecraft:stone');maintainSeat(e);assert(e.removed);assert.equal(p.ridingOn,undefined);assert.equal(count(p,NS+':blue_bar_stool'),1);assert.equal(b.typeId,'minecraft:stone');});
test('unanchored manually summoned helper is deleted rather than becoming a free chair',()=>{const e=d.spawnEntity(seatId('blue'),pos);world.afterEvents.entityLoad.emit({entity:e});system.advance();assert(e.removed);});
test('no support or obstructed headroom rejects stool without consumption',()=>{const p=player();hand(p,NS+':blue_bar_stool');assert.throws(()=>placeFurniture(p,pos),x=>x.code==='NEEDS_SOLID_SUPPORT');d.getBlock({...pos,y:63}).setType('minecraft:stone');d.getBlock({...pos,y:65}).setType('minecraft:stone');assert.throws(()=>placeFurniture(p,pos),x=>x.code==='SEAT_HEADROOM');assert.equal(count(p,NS+':blue_bar_stool'),1);});
test('sitting rechecks changed headroom and support',()=>{const {p,b}=stool();d.getBlock({...pos,y:65}).setType('minecraft:stone');assert.throws(()=>sitOnFurniture(p,b),x=>x.code==='SEAT_HEADROOM');d.getBlock({...pos,y:65}).setType('minecraft:air');d.getBlock({...pos,y:63}).setType('minecraft:air');assert.throws(()=>sitOnFurniture(p,b),x=>x.code==='NEEDS_SOLID_SUPPORT');recoverFurniture(p,b);assert(b.isAir);});
test('dye switches full design and preserves facing; same color costs nothing',()=>{const {p,b}=light('red');b.setPermutation(b.permutation.withState(FACING,3));hand(p,'minecraft:green_dye',16);assert(recolorLight(p,b));assert.equal(count(p,'minecraft:green_dye'),15);assert.equal(b.typeId,NS+':light_green');assert.equal(b.permutation.getState(FACING),3);assert.equal(recolorLight(p,b),false);assert.equal(count(p,'minecraft:green_dye'),15);assert.equal(count(p,NS+':string_lights_red'),1);});
test('dye write failure restores16 dyes and old light variant',()=>{const {p,b}=light('red');hand(p,'minecraft:green_dye',16);b.failSet=true;assert.throws(()=>recolorLight(p,b),/BLOCK_FAILURE/);assert.equal(count(p,'minecraft:green_dye'),16);assert.equal(b.typeId,NS+':light_red');});
test('source metadata dye rejected with source stack preserved',()=>{const {p,b}=light('red');const dye=new ItemStack('minecraft:green_dye',16);dye.nameTag='label';hand(p,dye);assert.throws(()=>recolorLight(p,b),x=>x.code==='METADATA_ITEM_REJECTED');assert.equal(p.inventory.getItem(p.selectedSlotIndex).nameTag,'label');assert.equal(b.typeId,NS+':light_red');});
test('creative furniture still consumes real placed item and returns one',()=>{const p=player();p.mode=GameMode.Creative;const {b}=stool('blue',p);assert.equal(count(p,NS+':blue_bar_stool'),1);recoverFurniture(p,b);assert.equal(count(p,NS+':blue_bar_stool'),2);});
test('spectator/adventure cannot place/sit/recover furniture',()=>{const {p,b}=stool();for(const mode of[GameMode.Adventure,GameMode.Spectator]){p.mode=mode;assert.throws(()=>sitOnFurniture(p,b),x=>x.code==='GAME_MODE_LOCKED');assert.throws(()=>recoverFurniture(p,b),x=>x.code==='GAME_MODE_LOCKED');}});
test('explosion protection leaves unrelated blocks in impacted list',()=>{const {b}=light();const vanilla=d.getBlock({x:1,y:64,z:0});vanilla.setType('minecraft:stone');let out=[b,vanilla];world.beforeEvents.explosion.emit({getImpactedBlocks:()=>out,setImpactedBlocks:v=>out=v});assert.deepEqual(out,[vanilla]);});
test('Shriek completed drink applies source damage, additive impulse and16 particles',()=>{const p=player();p.health=mockHealth(10,20);const e=mob(p);e.velocity={x:1,y:-.5,z:2};hand(p,NS+':sculk_special',16);const before=p.inventory.getItem(0);const out=consumeCocktail({source:p,itemStack:before},()=>0);assert.equal(out[0].status,'APPLIED_CUSTOM');assert.equal(e.damageCalls[0].amount,12);assert.equal(e.damageCalls[0].opts.cause,'sonicBoom');assert.equal(e.damageCalls[0].opts.damagingEntity,p);assert.equal(e.velocity.x,1);assert(Math.abs(e.velocity.y+.22)<1e-12);assert.equal(e.velocity.z,2.63);assert.equal(d.particles.length,16);assert.equal(d.particles[0].id,'minecraft:sonic_explosion');assert.deepEqual(p.inventory.getItem(0),before);assert.equal(count(p,NS+':empty_glassware'),0);});
test('Shriek source rules hit in corridor only and do not stop at walls',()=>{const p=player(),hit=mob(p,{z:30}),rear=mob(p,{z:-5}),far=mob(p,{z:32.01}),side=mob(p,{x:1.31,z:8});d.getBlock({x:0,y:66,z:5}).setType('minecraft:stone');performShriek(p);assert.equal(hit.damageCalls.length,1);assert.equal(rear.damageCalls,undefined);assert.equal(far.damageCalls,undefined);assert.equal(side.damageCalls,undefined);assert.equal(d.getBlock({x:0,y:66,z:5}).typeId,'minecraft:stone');});
test('PvE only excludes players, own helpers, XP orbs and dead mobs',()=>{const p=player(),q=player('friend');q.location={...p.location,z:8};d.entities.set(q.id,q);const helper=mob(p,{type:seatId('blue')}),orb=d.spawnEntity('minecraft:xp_orb',{...p.location,z:8}),dead=mob(p,{health:0});performShriek(p);assert.equal(q.health.currentValue,20);assert.equal(helper.damageCalls,undefined);assert.equal(orb.damageCalls,undefined);assert.equal(dead.damageCalls,undefined);});
test('rejected native damage produces no forced HP change or knockback',()=>{const p=player(),e=mob(p);e.rejectDamage=true;e.velocity={x:1,y:2,z:3};performShriek(p);assert.equal(e.health.currentValue,100);assert.deepEqual(e.velocity,{x:1,y:2,z:3});});
test('bad target and cosmetic failures do not repeat attack or cancel later target',()=>{const p=player(),bad=mob(p,{z:3}),good=mob(p,{z:8});bad.failDamage=true;d.failAudio=true;d.failParticles=true;performShriek(p);assert.equal(good.damageCalls.length,1);assert(combatDiagnostics.errors.length<=16);});
test('missing engine AABB capability skips unsupported target, not guessed hitbox',()=>{const p=player(),e=mob(p);e.getAABB=undefined;const old=combatDiagnostics.missingAabb;performShriek(p);assert.equal(e.damageCalls,undefined);assert.equal(combatDiagnostics.missingAabb,old+1);});
test('duplicate same-tick callback does not damage twice or repeat particles',()=>{const p=player(),e=mob(p);performShriek(p);performShriek(p);assert.equal(e.damageCalls.length,1);assert.equal(d.particles.length,16);system.advance();performShriek(p);assert.equal(e.damageCalls.length,2);});
test('dead or locked source produces no sonic attack',()=>{const p=player(),e=mob(p);p.health.currentValue=0;assert.equal(performShriek(p),false);p.health.currentValue=20;p.mode=GameMode.Spectator;assert.equal(performShriek(p),false);assert.equal(e.damageCalls,undefined);});
test('wide-target halfwidth expands hit radius, diagonal source uses full ray',()=>{const p=player();const big=mob(p,{x:2.5,z:8,extent:2});performShriek(p);assert.equal(big.damageCalls.length,1);});
test('target cap bounds damage to256, records truncation, no invulnerability bypass',()=>{const p=player();const mobs=Array.from({length:270},(_,i)=>mob(p,{z:3+i*.001}));performShriek(p);assert.equal(mobs.filter(e=>e.damageCalls).length,256);assert(combatDiagnostics.cappedQueries>0);});
test('Shriek applied through signature/custom dispatcher is instant, no saved timer',()=>{const p=player(),e=mob(p);assert(applyCustomEffect(p,{effect:NS+':shriek_attack',duration:1,amplifier:0}));assert.equal(e.damageCalls.length,1);assert.equal(p.getDynamicProperty(NS+':custom_effects'),undefined);});
test('Screwdriver upside-down renames only alive mobs inside Java-style inflated AABB and stays instant',()=>{const p=player(),near=mob(p,{z:16.5}),far=mob(p,{z:16.61}),dead=mob(p,{z:8,health:0}),q=player('upside-friend');q.location={...p.location,z:p.location.z+8};q.health=mockHealth(20,20);q.box={center:{x:q.location.x,y:q.location.y+1,z:q.location.z},extent:{x:.3,y:1,z:.3}};d.entities.set(q.id,q);hand(p,NS+':screwdriver');const before=customEffectDiagnostics.upsideDownRenames;const out=consumeCocktail({source:p,itemStack:p.inventory.getItem(0)},()=>0);assert.equal(out[0].status,'APPLIED_CUSTOM');assert.equal(near.nameTag,'Grumm');assert.equal(far.nameTag,undefined);assert.equal(dead.nameTag,undefined);assert.equal(q.nameTag,undefined);assert.equal(p.getDynamicProperty(NS+':custom_effects'),undefined);assert.equal(customEffectDiagnostics.upsideDownRenames,before+1);});
test('remaining unsupported effects are still not substituted with arbitrary buffs',()=>{const p=player();assert.equal(applyCustomEffect(p,{effect:NS+':long_reach',duration:100,amplifier:0}),false);assert.equal(p.effects.length,0);});
test('independent guide includes new furniture/effect pages; recipe API count stays41',()=>{assert.equal(runtimeRegistry().allRecipes().length,41);const ids=runtimeRegistry().allPages().map(x=>x.id);assert(ids.includes(NS+':c6_furniture'));assert(ids.includes(NS+':c6_sonic'));assert.equal(diagnosticSnapshot().build,'C6 / 0.6.0');assert.equal(diagnosticSnapshot().independentGuidebook,true);});
