import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {ExtensionRegistry,matchIngredients}from '../runtime/BP/scripts/core/registry.js';
import {ExtensionTransport,packetsFor,EVENTS}from '../runtime/BP/scripts/core/transport.js';
import {newMachine,interact,advanceBarrel,filledItem,validateMachine,barrelCells}from '../runtime/BP/scripts/core/machines.js';
import {MachineStore,machineKey,Locks}from '../runtime/BP/scripts/core/storage.js';
import {planInventory,commitInventory,isPlainIngredient}from '../runtime/BP/scripts/core/inventory.js';
import {BUILTIN_RECIPES}from '../runtime/BP/scripts/data/recipes.js';import {FLUIDS}from '../runtime/BP/scripts/data/fluids.js';
import {GUIDE_PAGES}from '../runtime/BP/scripts/data/guide-pages.js';import {NAMES}from '../runtime/BP/scripts/data/names.js';
import {inputSnapshot}from '../runtime/BP/scripts/core/mixology.js';
import {guideEntries,searchEntries,paginate}from '../runtime/BP/scripts/core/guide.js';import {utf8Bytes,canonical,digest}from '../runtime/BP/scripts/core/util.js';
import {ItemStack,Container,Properties}from './fake-server.js';
const NS='kaleidoscope_tavern',make=(id,n)=>new ItemStack(id,n),reg=()=>new ExtensionRegistry({recipes:BUILTIN_RECIPES,fluids:FLUIDS,pages:GUIDE_PAGES});
const payload=JSON.parse(fs.readFileSync(new URL('../examples/extension-payload.json',import.meta.url)));
function throws(fn,code){assert.throws(fn,e=>e.code===code);}
function use(s,id,count=1,r=reg()){return interact(s,{action:'use',held:{id,count}},r,FLUIDS);}
function full(fluid=NS+':grape_juice'){const s=newMachine('barrel','test');s.fluid=fluid;s.amount=4000;return s;}

test('exact production recipe counts and disabled Molotov',()=>{assert.equal(BUILTIN_RECIPES.filter(x=>x.kind==='barrel').length,23);assert.equal(BUILTIN_RECIPES.filter(x=>x.kind==='pressing').length,6);assert(!BUILTIN_RECIPES.some(x=>x.id.includes('molotov')));});
test('all 23 recipes match their concrete ingredients and six output variants',()=>{const r=reg();for(const recipe of r.allRecipes().filter(x=>x.kind==='barrel')){assert.equal(r.findBarrel(recipe.fluid,recipe.ingredients.map(s=>({id:s[0],count:3}))).id,recipe.id);assert.equal(recipe.output.byQuality.length,6);}});
test('alternative matching uses backtracking and duplicate counts',()=>{assert(matchIngredients([['a:a','b:b'],['a:a']],[{id:'a:a'},{id:'b:b'}]));assert(!matchIngredients([['a:a'],['a:a']],[{id:'a:a'}]));assert(!matchIngredients([['a:a']],[{id:'a:a'},{id:'a:a'}]));});
test('eight stomps yield exactly 1000mB and consume eight grapes',()=>{let s=newMachine('pressing_tub','x');s=use(s,NS+':grape',32).state;for(let i=0;i<8;i++)s=interact(s,{action:'press'},reg(),FLUIDS).state;assert.equal(s.amount,1000);assert.equal(s.slots[0].count,24);throws(()=>interact(s,{action:'press'},reg(),FLUIDS),'FLUID_FULL');});
test('Java pressing-tub removal takes one normally and up to64 when sneaking; barrel still returns the whole slot',()=>{let t=newMachine('pressing_tub','x');t.slots[0]={id:NS+':grape',count:10};let tx=interact(t,{action:'remove_ingredient',removeCount:1},reg(),FLUIDS);assert.deepEqual(tx.give,[{id:NS+':grape',count:1}]);assert.equal(tx.state.slots[0].count,9);tx=interact(tx.state,{action:'remove_ingredient',removeCount:64},reg(),FLUIDS);assert.deepEqual(tx.give,[{id:NS+':grape',count:9}]);assert.equal(tx.state.slots[0],null);let b=full();b.slots[0]={id:'minecraft:sugar',count:7};tx=interact(b,{action:'remove_ingredient',removeCount:1},reg(),FLUIDS);assert.deepEqual(tx.give,[{id:'minecraft:sugar',count:7}]);assert.equal(tx.state.slots[0],null);});
test('all six pressing recipes resolve to their own fluid',()=>{for(const r of BUILTIN_RECIPES.filter(x=>x.kind==='pressing')){let s=newMachine('pressing_tub','x');s=use(s,r.input[0]).state;s=interact(s,{action:'press'},reg(),FLUIDS).state;assert.equal(s.fluid,r.fluid);assert.equal(s.amount,125);}});
test('mixed fluids and partial bucket extraction reject without mutating state',()=>{let s=newMachine('pressing_tub','x');s.amount=125;s.fluid=NS+':grape_juice';const raw=JSON.stringify(s);throws(()=>use(s,'minecraft:bucket',16),'NOT_ENOUGH_FLUID');throws(()=>use(s,'minecraft:sweet_berries',1),'MIXED_FLUID');assert.equal(JSON.stringify(s),raw);});
test('16 empty buckets retain 15 plus one filled bucket',()=>{const c=new Container(3);c.setItem(0,make('minecraft:bucket',16));const p=planInventory(c,0,1,[{id:NS+':grape_bucket',count:1}],make);commitInventory(p,c,()=>{},()=>{});assert.equal(c.getItem(0).amount,15);assert.equal(c.getItem(1).typeId,NS+':grape_bucket');});
test('full inventory rejects exchange; no machine mutation',()=>{const c=new Container(2);c.setItem(0,make('minecraft:bucket',16));c.setItem(1,make('minecraft:stone',64));throws(()=>planInventory(c,0,1,[{id:NS+':grape_bucket',count:1}],make),'INVENTORY_FULL');assert.equal(c.getItem(0).amount,16);});
test('last empty bucket frees its own slot even when inventory is otherwise full',()=>{const c=new Container(2);c.setItem(0,make('minecraft:bucket',1));c.setItem(1,make('minecraft:stone',64));const p=planInventory(c,0,1,[{id:NS+':grape_bucket',count:1}],make);commitInventory(p,c,()=>{},()=>{});assert.equal(c.getItem(0).typeId,NS+':grape_bucket');});
test('inventory write exception restores already written slots',()=>{const c=new Container(3);c.setItem(0,make('minecraft:bucket',16));c.failAt=c.writes+1;const p=planInventory(c,0,1,[{id:NS+':grape_bucket',count:1}],make);assert.throws(()=>commitInventory(p,c,()=>{},()=>{}),/INJECTED/);assert.equal(c.getItem(0).amount,16);assert.equal(c.getItem(1),undefined);});
test('storage failure rolls inventory back',()=>{const c=new Container(3);c.setItem(0,make('minecraft:bucket',16));const p=planInventory(c,0,1,[{id:NS+':grape_bucket',count:1}],make);assert.throws(()=>commitInventory(p,c,()=>{throw Error('save failed')},()=>{}));assert.equal(c.getItem(0).amount,16);assert.equal(c.getItem(1),undefined);});
test('rollback failure is reported, not swallowed',()=>{const c=new Container(1);c.setItem(0,make('minecraft:bucket',1));const p=planInventory(c,0,1,[],make);throws(()=>commitInventory(p,c,()=>{throw Error('save')},()=>{throw Error('undo')}),'ROLLBACK_FAILED');});
test('named, lore, dynamic and durability ingredients rejected; plain filled bucket accepted',()=>{for(const meta of [{lore:['x']},{dp:{x:1}},{'minecraft:durability':{damage:0}},{canPlaceOn:['minecraft:stone']}]){const item=make(NS+':grape',1);item.meta=meta;assert(!isPlainIngredient(item,make));}const named=make(NS+':grape',2);named.nameTag='My fruit';assert(!isPlainIngredient(named,make));assert(isPlainIngredient(make(NS+':grape_bucket',1),make));});
test('untouched metadata survives transactions',()=>{const c=new Container(4);const named=make('minecraft:stone',16);named.nameTag='Keep me';c.setItem(1,named);c.setItem(0,make('minecraft:bucket',16));const p=planInventory(c,0,1,[{id:NS+':grape_bucket',count:1}],make);commitInventory(p,c,()=>{},()=>{});assert.equal(c.getItem(1).nameTag,'Keep me');});
test('randomized bucket conservation for 500 deterministic inventories',()=>{let seed=17;for(let t=0;t<500;t++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const n=seed%16+1,c=new Container(4);c.setItem(0,make('minecraft:bucket',n));if(seed&1)c.setItem(2,make('minecraft:stone',64));const p=planInventory(c,0,1,[{id:NS+':grape_bucket',count:1}],make);commitInventory(p,c,()=>{},()=>{});const items=Array.from({length:c.size},(_,i)=>c.getItem(i)).filter(Boolean);assert.equal(items.filter(x=>x.typeId==='minecraft:bucket').reduce((a,x)=>a+x.amount,0),n-1);assert.equal(items.filter(x=>x.typeId===NS+':grape_bucket').reduce((a,x)=>a+x.amount,0),1);}});
test('four slots cap at16 and filled-before-ingredients enforcement',()=>{throws(()=>use(newMachine('barrel','x'),'minecraft:sugar',16),'FILL_BARREL_FIRST');let s=full();s=use(s,'minecraft:sugar',64).state;assert.equal(s.slots[0].count,16);assert.equal(s.slots.filter(Boolean).length,1);});
test('fermentation uses snapshot output and minimum ingredient count',()=>{let s=full(NS+':green_grape_juice');s.slots=[{id:'minecraft:sugar_cane',count:9},{id:'minecraft:sugar',count:3},null,null];s.open=false;s=advanceBarrel(s,reg());assert.equal(s.batch.remaining,3);assert.equal(s.batch.quality,1);assert.equal(s.amount,0);assert(s.slots.every(x=>!x));});
test('no ingredient and invalid mixtures yield16, invalid→vinegar',()=>{for(const bad of [false,true]){let s=full();if(bad)s.slots[0]={id:'minecraft:dirt',count:1};s.open=false;s=advanceBarrel(s,reg());assert.equal(s.batch.remaining,16);assert.equal(filledItem(s),NS+':'+(bad?'vinegar':'wine')+'_q1');}});
test('open/empty barrel does not advance and source97 cadence stays capped',()=>{let s=full();assert.equal(advanceBarrel(s,reg()),s);s.open=false;s=advanceBarrel(s,reg());for(let i=0;i<500;i++)s=advanceBarrel(s,reg());assert.equal(s.batch.quality,6);assert.equal(advanceBarrel(s,reg()),s);});
test('serving consumes one bottle and exactly one output; final serving resets while the Java lid stays closed',()=>{let s=full();s.open=false;s=advanceBarrel(s,reg());for(let i=0;i<16;i++){const tx=interact(s,{action:'extract',held:{id:NS+':empty_bottle',count:16}},reg(),FLUIDS);assert.equal(tx.take,1);assert.equal(tx.give[0].count,1);s=tx.state;}assert.equal(s.batch,null);assert.equal(s.open,false);throws(()=>interact(s,{action:'extract',held:{id:NS+':empty_bottle',count:1}},reg(),FLUIDS),'NO_PRODUCT');});
test('state roundtrip, revision conflict and malformed data fail closed',()=>{const b=new Properties(),s=new MachineStore(b),key=machineKey('minecraft:overworld',{x:-1,y:60,z:0}),m=newMachine('barrel','x');s.save(key,m,-1);assert.deepEqual(new MachineStore(b).load(key),m);throws(()=>s.save(key,m,-1),'STATE_CONFLICT');b.setDynamicProperty(key,'{broken');throws(()=>s.load(key),'CORRUPT_STATE');});
test('unsupported future state version is not reset',()=>{const b=new Properties(),s=new MachineStore(b);b.setDynamicProperty('x',JSON.stringify({...newMachine('barrel','x'),schema:99}));throws(()=>s.load('x'),'STATE_SCHEMA');assert(b.getDynamicProperty('x').includes('99'));});
test('reentrancy locks stop double claim and release after failure',()=>{const l=new Locks();throws(()=>l.with(['x'],()=>l.with(['x'],()=>1)),'BUSY');assert.equal(l.with(['x'],()=>7),7);});
test('barrel structure has27 unique cells and correct single origin',()=>{const cells=barrelCells({x:10,y:20,z:30});assert.equal(cells.length,27);assert.equal(new Set(cells.map(x=>`${x.x},${x.y},${x.z}`)).size,27);assert.equal(cells.filter(x=>x.core).length,1);});
test('Pressing Tub uses native placement traits, source tilt model and stable water containment',()=>{const b=JSON.parse(fs.readFileSync(new URL('../runtime/BP/blocks/pressing_tub.json',import.meta.url)))['minecraft:block'];assert.deepEqual(b.description.traits['minecraft:placement_position'],{enabled_states:['minecraft:block_face']});assert.deepEqual(b.description.traits['minecraft:placement_direction'],{enabled_states:['minecraft:cardinal_direction'],y_rotation_offset:180});assert.deepEqual(b.components['minecraft:liquid_detection'].detection_rules,[{liquid_type:'water',can_contain_liquid:true,on_liquid_touches:'blocking',use_liquid_clipping:false}]);const tilted=b.permutations.filter(x=>x.components['minecraft:geometry']?.identifier==='geometry.kt_assets_a1.pressing_tub_tilt');assert.equal(tilted.length,4);assert.deepEqual(new Set(tilted.map(x=>x.condition.match(/== '([^']+)'/)[1])),new Set(['north','east','south','west']));assert.deepEqual(tilted.map(x=>x.components['minecraft:transformation'].rotation[1]),[0,-90,-180,-270]);const flat=b.permutations.filter(x=>x.components['minecraft:geometry']?.identifier==='geometry.kt_assets_a1.pressing_tub');assert.equal(flat.length,4);assert(flat.every(x=>x.condition.includes("minecraft:block_face') == 'up'")&&x.condition.includes("minecraft:block_face') == 'down'")));});
test('extension install idempotent; core recipes remain first',()=>{const r=reg(),n=r.allRecipes().length;r.install(payload);r.install(payload);assert.equal(r.allRecipes().length,n+1);const collision=structuredClone(payload);collision.recipes[0].fluid=NS+':grape_juice';collision.recipes[0].ingredients=[];r.install(collision);assert.equal(r.findBarrel(NS+':grape_juice',[]).source,NS);});
test('extension ordering does not depend on load order',()=>{const x=structuredClone(payload),y=structuredClone(payload);x.source='aaa';x.recipes[0].id='aaa:r';x.pages=[];y.source='zzz';y.recipes[0].id='zzz:r';y.pages=[];const a=reg(),b=reg();a.install(x);a.install(y);b.install(y);b.install(x);assert.deepEqual(a.allRecipes(),b.allRecipes());});
test('bad bundle cannot overwrite valid previous extension',()=>{const r=reg();r.install(payload);const old=canonical(r.allRecipes()),bad=structuredClone(payload);bad.pages[0].recipeIds=['evil:missing'];throws(()=>r.install(bad),'UNKNOWN_PAGE_RECIPE');assert.equal(canonical(r.allRecipes()),old);});
test('reserved and foreign namespaces reject',()=>{const r=reg(),p=structuredClone(payload);p.source=NS;throws(()=>r.install(p),'RESERVED_SOURCE');p.source='tavern_demo';p.recipes[0].id=NS+':wine';throws(()=>r.install(p),'FOREIGN_NAMESPACE');});
test('unknown kind, fluid, item and API version are rejected',()=>{for(const mutate of [p=>p.api=99,p=>p.recipes[0].kind='future_machine',p=>p.recipes[0].fluid='test:unknown',p=>p.recipes[0].unitTime=Infinity]){const p=structuredClone(payload);mutate(p);assert.throws(()=>reg().install(p));}const r=new ExtensionRegistry({fluids:FLUIDS,itemExists:()=>false});throws(()=>r.install(payload),'UNKNOWN_ITEM');});
test('registry subscribers observe atomic install/remove rebuilds without owning recipe semantics',()=>{const r=reg();let changes=0;const off=r.subscribe(()=>changes++);r.install(payload);assert.equal(changes,1);r.remove('tavern_demo');assert.equal(changes,2);off();r.install(payload);assert.equal(changes,2);});
test('session reload removes extensions; stored batch snapshot remains usable',()=>{const r=reg();r.install(payload);let s=full('minecraft:water');s.slots[0]={id:'minecraft:glow_berries',count:3};s.open=false;s=advanceBarrel(s,r);assert.equal(s.batch.recipeId,'tavern_demo:berry_test');const fresh=reg();assert(!fresh.recipe('tavern_demo:berry_test'));assert.equal(filledItem(s),NS+':wine_q1');});
test('out-of-order chunks, duplicate exact chunks and unicode roundtrip',()=>{const r=reg(),t=new ExtensionTransport(r),p=structuredClone(payload);p.pages[0].body.zh_TW='葡萄🍇'.repeat(500);const packets=packetsFor(p);assert(packets.every(x=>utf8Bytes(x.message)<=1900));t.receive(packets[0].id,packets[0].message,0);for(const x of packets.slice(1,-1).reverse()){t.receive(x.id,x.message,1);t.receive(x.id,x.message,1);}const result=t.receive(packets.at(-1).id,packets.at(-1).message,2);assert(result.ok);assert.equal(r.allPages().at(-1).body.zh_TW,p.pages[0].body.zh_TW);});
test('incomplete or corrupt transmission never partially installs',()=>{const r=reg(),t=new ExtensionTransport(r),p=packetsFor(payload);t.receive(p[0].id,p[0].message,0);throws(()=>t.receive(p.at(-1).id,p.at(-1).message,2),'MISSING_CHUNKS');assert.equal(r.list().length,0);t.receive(p[0].id,p[0].message,3);for(const x of p.slice(1,-1)){const c=JSON.parse(x.message);c.data=c.data.replace('實驗','測驗');t.receive(x.id,JSON.stringify(c),3);}throws(()=>t.receive(p.at(-1).id,p.at(-1).message,4),'DIGEST_MISMATCH');});
test('oversize, expiry, pending limit and conflicting duplicate chunk guarded',()=>{const r=reg(),t=new ExtensionTransport(r),p=packetsFor(payload);throws(()=>t.receive(EVENTS.begin,'x'.repeat(1901),0),'PACKET_TOO_LARGE');t.receive(p[0].id,p[0].message,0);t.cleanup(601);throws(()=>t.receive(p[1].id,p[1].message,602),'NO_PENDING_TRANSFER');t.receive(p[0].id,p[0].message,603);t.receive(p[1].id,p[1].message,603);const c=JSON.parse(p[1].message);c.data+='x';throws(()=>t.receive(p[1].id,JSON.stringify(c),603),'CONFLICTING_CHUNK');for(let i=0;i<15;i++){const b=JSON.parse(p[0].message);b.source='source'+i;t.receive(EVENTS.begin,JSON.stringify(b),603);}const b=JSON.parse(p[0].message);b.source='overflow';throws(()=>t.receive(EVENTS.begin,JSON.stringify(b),603),'PENDING_LIMIT');});
test('guide recipes are generated from registry not a second recipe table',()=>{const r=reg();assert.equal(guideEntries(r,'zh_TW',NAMES.zh_TW).filter(x=>x.kind==='recipe').length,29);r.install(payload);assert.equal(guideEntries(r,'zh_TW',NAMES.zh_TW).filter(x=>x.kind==='recipe').length,30);assert(searchEntries(guideEntries(r,'zh_TW',NAMES.zh_TW),'附屬示範').length>0);});
test('guide pagination respects8 items and removed add-on pages disappear',()=>{const r=reg();r.install(payload);let entries=guideEntries(r,'en_US');assert.equal(paginate(entries,0).entries.length,8);assert.equal(paginate([],999).page,0);r.remove('tavern_demo');entries=guideEntries(r,'en_US');assert(!entries.some(x=>x.source==='tavern_demo'));});
test('source correction: all Q1–Q6 use one complete-use drink lifecycle without food competition',()=>{for(const q of [1,2,3,4,5,6]){const d=JSON.parse(fs.readFileSync(new URL(`../runtime/BP/items/wine_q${q}.json`,import.meta.url)))['minecraft:item'].components;assert.equal(d['minecraft:food'],undefined);assert(d[NS+':drink_effects']);assert.equal(d['minecraft:use_animation'],'drink');assert.deepEqual(d['minecraft:use_modifiers'],{use_duration:1.6,movement_modifier:.35,start_using:'if_first'});}});

test("ack retains caller transfer revision distinct from registry counter",()=>{const r=reg(),t=new ExtensionTransport(r);let result;for(const p of packetsFor(payload,"request_revision_123"))result=t.receive(p.id,p.message,10);assert.equal(result.revision,"request_revision_123");assert.equal(typeof result.registryRevision,"number");});

test('guide and recipe IDs cannot collide within one extension',()=>{const r=reg(),x=structuredClone(payload);x.pages[0].id=x.recipes[0].id;throws(()=>r.install(x),'PAGE_RECIPE_ID_COLLISION');assert.equal(r.list().length,0);});


test('World Liquor-style external shaker input descriptor is explicit, snapshotted and removable',()=>{
 const r=new ExtensionRegistry({fluids:FLUIDS,itemExists:()=>true});
 const x={api:1,source:'world_liquor_demo',version:'1.0.0',shakerInputs:[{item:'world_liquor_demo:gin',container:'minecraft:glass_bottle',color:0x77aaff,effects:[{effect:'minecraft:speed',duration:30,amplifier:0,probability:1}]}]};
 const installed=r.install(x);assert.equal(installed.shakerInputs,1);assert.equal(r.list()[0].shakerInputs,1);assert(r.acceptsShakerInput('world_liquor_demo:gin'));
 assert.deepEqual(inputSnapshot('world_liquor_demo:gin',r),{item:'world_liquor_demo:gin',container:'minecraft:glass_bottle',color:0x77aaff,effects:[{effect:'minecraft:speed',duration:30,amplifier:0,probability:1}]});
 r.remove('world_liquor_demo');assert.equal(r.acceptsShakerInput('world_liquor_demo:gin'),false);
});
test('external shaker descriptors cannot claim another add-on namespace or partially replace a valid bundle',()=>{
 const r=new ExtensionRegistry({fluids:FLUIDS,itemExists:()=>true}),good={api:1,source:'world_liquor_demo',version:'1.0.0',shakerInputs:[{item:'world_liquor_demo:gin',color:0x123456}]};
 r.install(good);const before=canonical(r.list()),bad=structuredClone(good);bad.shakerInputs[0].item='other_addon:gin';throws(()=>r.install(bad),'FOREIGN_NAMESPACE');assert.equal(canonical(r.list()),before);assert(r.shakerInput('world_liquor_demo:gin'));
});
