/** Script regression only: a deterministic double queues real naturalBreak on
 * replacement, as the engine did in the reported bug. No Minecraft/BDS/client
 * or simulated-player acceptance is claimed.
 * Run: node --experimental-vm-modules --test tools/tap/tap-regression.test.mjs
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
const NS='kaleidoscope_tavern',EMPTY=NS+':bottle_empty',ITEM=NS+':empty_bottle';
import {fixture} from './fixture.mjs';
export {fixture};

for(const synchronous of [false,true])test(`placed wine: one conversion, no empty drop (${synchronous?'synchronous':'queued'} onBreak)`,async()=>{
 const f=await fixture({synchronous});f.machines.finishTapExtraction(f.tap);f.advance(5);
 assert.equal(f.bottle.typeId,NS+':bottle_wine');assert.equal(f.state().batch.remaining,3);assert.deepEqual(f.display().items,[NS+':wine_q3']);assert.equal(f.display().facing,1);assert.equal(f.items().length,0);
});
test('placed BottleBlockItem replaces the carrier directly, without an air intermediate',async()=>{const f=await fixture();f.machines.finishTapExtraction(f.tap);const transitions=f.changes.filter(x=>x.p.z===-2&&x.p.y===0);assert.equal(transitions.length,1);assert.equal(transitions[0].from,EMPTY);assert.equal(transitions[0].to,NS+':bottle_wine');});
test('all four placed bottle directions survive conversion',async()=>{for(const[cardinal,expected]of [['north',0],['east',1],['south',2],['west',3]]){const f=await fixture();f.bottle.permutation=f.Permutation.resolve(EMPTY,{'minecraft:cardinal_direction':cardinal});f.machines.finishTapExtraction(f.tap);f.advance(4);assert.equal(f.display().facing,expected);assert.equal(f.items().length,0);}});
test('last output clears the batch without refunding its carrier',async()=>{const f=await fixture();const s=f.state();s.batch.remaining=1;f.writeState(s);f.machines.finishTapExtraction(f.tap);f.advance(4);assert.equal(f.state().batch,null);assert.equal(f.items().length,0);assert.equal(f.display().items.length,1);});
test('dropped stack consumes exactly one empty carrier and retains the remainder metadata',async()=>{const f=await fixture();f.bottle.permutation=f.Permutation.resolve('minecraft:air');const stack=new f.ItemStack(ITEM,3);stack.nameTag='retained';f.dimension.spawnItem(stack,{x:.5,y:.5,z:-1.5});f.machines.finishTapExtraction(f.tap);f.advance(4);assert.equal(f.items().length,1);assert.equal(f.items()[0].typeId,ITEM);assert.equal(f.items()[0].amount,2);assert.equal(f.items()[0].nameTag,'retained');assert.equal(f.state().batch.remaining,3);});
test('one dropped carrier leaves no empty item',async()=>{const f=await fixture();f.bottle.permutation=f.Permutation.resolve('minecraft:air');f.dimension.spawnItem(new f.ItemStack(ITEM),{x:.5,y:.5,z:-1.5});f.machines.finishTapExtraction(f.tap);f.advance(4);assert.equal(f.items().length,0);assert.equal(f.display().items.length,1);});
test('ordinary non-BottleBlockItem output drops once and does not refund an empty bottle',async()=>{const f=await fixture();const s=f.state();s.batch.output={item:'minecraft:stick'};f.writeState(s);f.machines.finishTapExtraction(f.tap);f.advance(4);assert.equal(f.bottle.typeId,'minecraft:air');assert.deepEqual(f.items().map(s=>s.typeId),['minecraft:stick']);assert.equal(f.state().batch.remaining,3);});
for(const synchronous of [false,true])test(`failed barrel commit restores carrier and stock with no phantom drops (${synchronous?'synchronous':'queued'})`,async()=>{const f=await fixture({synchronous});const old=f.records.get(f.key);f.failStorage(k=>k===f.key);assert.throws(()=>f.machines.finishTapExtraction(f.tap),/injected storage failure/);f.advance(5);assert.equal(f.bottle.typeId,EMPTY);assert.equal(f.bottle.permutation.getState('minecraft:cardinal_direction'),'east');assert.equal(f.records.get(f.key),old);assert.equal(f.display(),undefined);assert.equal(f.items().length,0);});
test('failed bottle-state write restores empty carrier without a quality bottle drop',async()=>{const f=await fixture();const old=f.records.get(f.key);f.failStorage(k=>k===f.drinkKey);assert.throws(()=>f.machines.finishTapExtraction(f.tap),/injected storage failure/);f.advance(5);assert.equal(f.bottle.typeId,EMPTY);assert.equal(f.records.get(f.key),old);assert.equal(f.display(),undefined);assert.equal(f.items().length,0);});
test('failed output placement does not consume the bottle or stock',async()=>{const f=await fixture();const old=f.records.get(f.key);f.failPermutation((b,next)=>b===f.bottle&&next.type.id===NS+':bottle_wine');assert.throws(()=>f.machines.finishTapExtraction(f.tap),/injected block failure/);f.advance(5);assert.equal(f.bottle.typeId,EMPTY);assert.equal(f.records.get(f.key),old);assert.equal(f.items().length,0);});
test('missing output item is rejected without loss',async()=>{const f=await fixture();const s=f.state();s.batch.output={item:'missing:item'};f.writeState(s);const old=f.records.get(f.key);assert.throws(()=>f.machines.finishTapExtraction(f.tap),/UNKNOWN_ITEM/);f.advance(5);assert.equal(f.records.get(f.key),old);assert.equal(f.bottle.typeId,EMPTY);assert.equal(f.items().length,0);});
test('water-cauldron conversion also suppresses the spent empty carrier callback',async()=>{const f=await fixture();f.block('minecraft:cauldron',{x:0,y:1,z:-1},{cauldron_liquid:'water',fill_level:6});assert.equal(f.machines.finishWaterCauldronTap(f.tap),true);f.advance(5);assert.equal(f.bottle.typeId,NS+':bottle_water');assert.equal(f.items().length,0);});
test('genuine destruction of an empty bottle still drops exactly one empty bottle',async()=>{const f=await fixture();f.bottle.setType('minecraft:air');f.advance(5);assert.deepEqual(f.items().map(s=>s.typeId),[ITEM]);});
test('genuine destruction of filled bottle still releases its stored quality once',async()=>{const f=await fixture();f.machines.finishTapExtraction(f.tap);f.advance(5);f.bottle.setType('minecraft:air');f.advance(5);assert.deepEqual(f.items().map(s=>s.typeId),[NS+':wine_q3']);assert.equal(f.display(),undefined);});
test('missing carrier at completion preserves the barrel output',async()=>{const f=await fixture();f.bottle.permutation=f.Permutation.resolve('minecraft:air');const old=f.records.get(f.key);assert.throws(()=>f.machines.finishTapExtraction(f.tap),/TAP_CARRIER_CHANGED/);assert.equal(f.records.get(f.key),old);assert.equal(f.items().length,0);});
test('successful session remains 30 ticks and emits drip parents only during ticks 1..5',async()=>{const f=await fixture();f.machines.tryOpenTap(f.tap);f.advance(29);assert.equal(f.bottle.typeId,EMPTY);assert.equal(f.state().batch.remaining,4);assert.deepEqual(f.particles.map(p=>p.tick),[1,2,3,4,5]);f.advance(1);assert.equal(f.bottle.typeId,NS+':bottle_wine');f.advance(5);assert.equal(f.items().length,0);assert.equal(f.state().batch.remaining,3);});
test('manually cancelling before completion does not consume a carrier or output',async()=>{const f=await fixture();f.machines.tryOpenTap(f.tap);f.advance(10);f.machines.toggleTap(f.tap);f.advance(30);assert.equal(f.bottle.typeId,EMPTY);assert.equal(f.state().batch.remaining,4);assert.equal(f.items().length,0);});
