# Static inspection only: give items, no clearing or world construction.
give @s kt_assets_a7:rum_1 1
give @s kt_assets_a7:rum_2 1
give @s kt_assets_a7:rum_3 1
give @s kt_assets_a7:rum_4 1
give @s kt_assets_a7:sherry_1 1
give @s kt_assets_a7:sherry_2 1
give @s kt_assets_a7:sherry_3 1
give @s kt_assets_a7:sherry_4 1
give @s kt_assets_a7:red_queen_1 1
give @s kt_assets_a7:red_queen_2 1
give @s kt_assets_a7:red_queen_3 1
give @s kt_assets_a7:red_queen_4 1
give @s kt_assets_a7:vinegar_1 1
give @s kt_assets_a7:vinegar_2 1
give @s kt_assets_a7:vinegar_3 1
give @s kt_assets_a7:vinegar_4 1
give @s kt_assets_a7:whiskey_1 1
give @s kt_assets_a7:whiskey_2 1
