# Static inspection only: give items, no clearing or world construction.
give @s kt_assets_a7:whiskey_3 1
give @s kt_assets_a7:whiskey_4 1
give @s kt_assets_a7:miners_star_1 1
give @s kt_assets_a7:miners_star_2 1
give @s kt_assets_a7:miners_star_3 1
give @s kt_assets_a7:miners_star_4 1
give @s kt_assets_a7:sauvignon_blanc_dry_white_1 1
give @s kt_assets_a7:sauvignon_blanc_dry_white_2 1
give @s kt_assets_a7:sauvignon_blanc_dry_white_3 1
give @s kt_assets_a7:sauvignon_blanc_dry_white_4 1
give @s kt_assets_a7:sweet_berry_wine_1 1
give @s kt_assets_a7:sweet_berry_wine_2 1
give @s kt_assets_a7:sweet_berry_wine_3 1
give @s kt_assets_a7:sweet_berry_wine_4 1
give @s kt_assets_a7:sakura_wine_1 1
give @s kt_assets_a7:sakura_wine_2 1
give @s kt_assets_a7:sakura_wine_3 1
give @s kt_assets_a7:sakura_wine_4 1
