import {world,system,BlockPermutation} from '@minecraft/server';
import {NS,CELLAR_CABINET,cellarCabinetItem,cellarCabinetSlot,emptyCellarCabinet,cellarCabinetPut,cellarCabinetTake,cellarCabinetPosition,cellarCabinetKey,cellarCabinetAnchor,parseCellarCabinetAnchor,cellarCabinetVisualPose,CellarCabinetStore} from '../core/cellar-cabinet.js';
import {FACING,POSITION,facingForYaw,facingVector,faceOffset} from '../core/furniture.js';
import {check} from '../core/util.js';
import {planInventory,commitInventory,isPlainIngredient} from '../core/inventory.js';
import {makeStack,hand,inventory,handSnapshot,sameHand,canWrite,blockAt,plus,tell,safe,air,breakDropTransaction} from './transactions.js';
const HELPER=NS+':cellar_cabinet_bottle_visual',ANCHOR=NS+':cellar_cabinet_anchor',store=new CellarCabinetStore(world),visuals=new Map();let cursor=0;
export const cellarCabinetDiagnostics={placed:0,inserted:0,taken:0,recovered:0,spawned:0,orphans:0,duplicates:0,repairs:0,errors:[],redstone:'NOT_ADAPTED'};
function error(e){cellarCabinetDiagnostics.errors.push(String(e));if(cellarCabinetDiagnostics.errors.length>16)cellarCabinetDiagnostics.errors.shift();}
function center(p){return {x:p.x+.5,y:p.y+.5,z:p.z+.5};}
function near(player,d,p){check(player.dimension.id===d.id,'DIMENSION_CHANGED');check(Math.hypot(player.location.x-p.x-.5,player.location.y-p.y-.5,player.location.z-p.z-.5)<=6,'OUT_OF_REACH');}
function neighborState(block,p){const b=blockAt(block.dimension,p);return b?.typeId===CELLAR_CABINET?{typeId:b.typeId,facing:b.permutation.getState(FACING)}:undefined;}
function cabinetNeighbors(block){const f=block.permutation.getState(FACING)??0;return {left:neighborState(block,plus(block.location,facingVector((f+1)%4))),right:neighborState(block,plus(block.location,facingVector((f+3)%4)))};}
export function syncCellarCabinetConnection(block){if(block?.typeId!==CELLAR_CABINET)return false;const f=block.permutation.getState(FACING)??0,want=cellarCabinetPosition(f,cabinetNeighbors(block)),cur=block.permutation.getState(POSITION)??0;if(cur===want)return false;block.setPermutation(block.permutation.withState(POSITION,want));cellarCabinetDiagnostics.repairs++;return true;}
export function syncCellarCabinetNeighborhood(block){if(block?.typeId!==CELLAR_CABINET)return 0;const f=block.permutation.getState(FACING)??0,ps=[block.location,plus(block.location,facingVector((f+1)%4)),plus(block.location,facingVector((f+3)%4))];let n=0;for(let pass=0;pass<3;pass++)for(const p of ps){const b=blockAt(block.dimension,p);if(b?.typeId===CELLAR_CABINET&&syncCellarCabinetConnection(b))n++;}return n;}
function slotHelpers(block,slot){const a=cellarCabinetAnchor(cellarCabinetKey(block.dimension.id,block.location),slot);return block.dimension.getEntities({type:HELPER,location:center(block.location),maxDistance:2}).filter(e=>e.getDynamicProperty(ANCHOR)===a);}
function discard(e,reason){e.remove();visuals.delete(e.id);cellarCabinetDiagnostics[reason]=(cellarCabinetDiagnostics[reason]??0)+1;}
export function syncCellarCabinetVisuals(block,state=store.load(cellarCabinetKey(block.dimension.id,block.location))){if(state)check(block?.typeId===CELLAR_CABINET,'NOT_CELLAR_CABINET');const facing=block?.permutation.getState(FACING)??0;for(let slot=0;slot<9;slot++){const item=state?.slots[slot]??null,all=slotHelpers(block,slot);if(!item){for(const e of all)discard(e,'orphans');continue;}const bottle=cellarCabinetItem(item);check(bottle,'CELLAR_CABINET_ITEM');all.sort((a,b)=>a.id.localeCompare(b.id));let e=all[0];for(const x of all.slice(1))discard(x,'duplicates');const pose=cellarCabinetVisualPose(slot,facing),at={x:block.location.x+pose.offset.x,y:block.location.y+pose.offset.y,z:block.location.z+pose.offset.z};if(!e){e=block.dimension.spawnEntity(HELPER,at);e.setDynamicProperty(ANCHOR,cellarCabinetAnchor(cellarCabinetKey(block.dimension.id,block.location),slot));e.addTag('kaleidoscope_tavern:visual_helper');cellarCabinetDiagnostics.spawned++;}e.setProperty(NS+':storage_kind',bottle.kind);e.setRotation(pose.rotation);e.tryTeleport(at,{checkForBlocks:false});visuals.set(e.id,e);}}
function visualSafe(block,state){try{syncCellarCabinetVisuals(block,state);}catch(e){error(e);}}
function transact(player,block,old,next,take,give,perm,dropSound){const k=cellarCabinetKey(block.dimension.id,block.location),raw=store.raw(k),oldp=block.permutation;if(dropSound)breakDropTransaction(player,block,give,()=>{block.setPermutation(perm);store.save(k,next,old?.revision??-1);},()=>{block.setPermutation(oldp);store.restore(k,raw);},dropSound);else{const c=inventory(player),plan=planInventory(c,player.selectedSlotIndex,take,give,makeStack);commitInventory(plan,c,()=>{block.setPermutation(perm);store.save(k,next,old?.revision??-1);},()=>{block.setPermutation(oldp);store.restore(k,raw);});}visualSafe(block,next);return next;}
export function placeCellarCabinet(player,target){canWrite(player);const d=player.dimension;near(player,d,target);const block=blockAt(d,target);check(block&&block.isAir,'SPACE_NOT_CLEAR');const h=hand(player);check(h?.typeId===CELLAR_CABINET,'NEED_CELLAR_CABINET');check(isPlainIngredient(h,makeStack),'METADATA_ITEM_REJECTED');const k=cellarCabinetKey(d.id,target);check(store.raw(k)===undefined,'STORAGE_CONFLICT');const facing=facingForYaw(player.getRotation().y),left=blockAt(d,plus(target,facingVector((facing+1)%4))),right=blockAt(d,plus(target,facingVector((facing+3)%4))),ns=b=>b?.typeId===CELLAR_CABINET?{typeId:b.typeId,facing:b.permutation.getState(FACING)}:undefined,pos=cellarCabinetPosition(facing,{left:ns(left),right:ns(right)}),state=emptyCellarCabinet(),plan=planInventory(inventory(player),player.selectedSlotIndex,1,[],makeStack),oldp=block.permutation;commitInventory(plan,inventory(player),()=>{block.setPermutation(BlockPermutation.resolve(CELLAR_CABINET,{[FACING]:facing,[POSITION]:pos}));store.save(k,state,-1);},()=>{block.setPermutation(oldp);store.restore(k,undefined);});syncCellarCabinetNeighborhood(block);cellarCabinetDiagnostics.placed++;return block;}
export function useCellarCabinet(player,block,face,faceLocation,{expectedRevision}={}){canWrite(player);near(player,block.dimension,block.location);check(block.typeId===CELLAR_CABINET,'NOT_CELLAR_CABINET');const slot=cellarCabinetSlot(block.permutation.getState(FACING)??0,face,faceLocation);if(slot<0)return false;const k=cellarCabinetKey(block.dimension.id,block.location),old=store.load(k);check(old,'MISSING_CELLAR_CABINET_STATE');if(expectedRevision!==undefined)check(old.revision===expectedRevision,'STATE_CONFLICT');const h=hand(player);if(!h){if(old.slots[slot]===null)return false;const tx=cellarCabinetTake(old,slot);transact(player,block,old,tx.state,0,[{id:tx.item,count:1}],block.permutation);cellarCabinetDiagnostics.taken++;return {slot,item:tx.item,state:tx.state};}const bottle=cellarCabinetItem(h.typeId);check(bottle,'NOT_CELLAR_CABINET_BOTTLE');check(isPlainIngredient(h,makeStack),'METADATA_ITEM_REJECTED');if(old.slots[slot]!==null)return false;const next=cellarCabinetPut(old,slot,h.typeId);transact(player,block,old,next,1,[],block.permutation);cellarCabinetDiagnostics.inserted++;return {slot,state:next};}
export function recoverCellarCabinet(player,block,{expectedRevision,drop=false}={}){canWrite(player);near(player,block.dimension,block.location);check(block.typeId===CELLAR_CABINET,'NOT_CELLAR_CABINET');const k=cellarCabinetKey(block.dimension.id,block.location),old=store.load(k);check(old,'MISSING_CELLAR_CABINET_STATE');if(expectedRevision!==undefined)check(old.revision===expectedRevision,'STATE_CONFLICT');const give=[{id:CELLAR_CABINET,count:1},...old.slots.filter(Boolean).map(id=>({id,count:1}))],f=block.permutation.getState(FACING)??0;transact(player,block,old,undefined,0,give,air(),drop?'wood':undefined);for(const p of[plus(block.location,facingVector((f+1)%4)),plus(block.location,facingVector((f+3)%4))]){const b=blockAt(block.dimension,p);if(b?.typeId===CELLAR_CABINET)syncCellarCabinetNeighborhood(b);}cellarCabinetDiagnostics.recovered++;return give;}
export function maintainCellarCabinetVisual(e){if(e?.typeId!==HELPER)return;try{const a=parseCellarCabinetAnchor(e.getDynamicProperty(ANCHOR));if(e.dimension.id!==a.dimension){discard(e,'orphans');return;}const block=blockAt(e.dimension,a.position);if(block?.typeId!==CELLAR_CABINET){discard(e,'orphans');return;}const state=store.load(cellarCabinetKey(e.dimension.id,a.position));if(!state?.slots[a.slot]){discard(e,'orphans');return;}visuals.set(e.id,e);syncCellarCabinetVisuals(block,state);}catch(x){error(x);try{discard(e,'orphans');}catch{}}}
export function tickCellarCabinets(){const list=[...visuals.values()];if(list.length){const n=Math.min(128,list.length);for(let i=0;i<n;i++)maintainCellarCabinetVisual(list[(cursor+i)%list.length]);cursor=(cursor+n)%Math.max(list.length,1);}}
export function registerCellarCabinetComponents({blockComponentRegistry:r}){r.registerCustomComponent(NS+':cellar_cabinet',{onTick:e=>{try{syncCellarCabinetConnection(e.block);const s=store.load(cellarCabinetKey(e.block.dimension.id,e.block.location));if(s)syncCellarCabinetVisuals(e.block,s);}catch(x){error(x);}}});}
export function installCellarCabinetEvents(openBook){world.beforeEvents.playerInteractWithBlock.subscribe(e=>{if(e.cancel)return;const existing=e.block.typeId===CELLAR_CABINET,hs=handSnapshot(e.player),placing=!existing&&hs.id===CELLAR_CABINET;if(!existing&&!placing)return;e.cancel=true;if(e.isFirstEvent===false)return;const d=e.block.dimension,p={...e.block.location},id=e.block.typeId,face=e.blockFace,loc=e.faceLocation?{...e.faceLocation}:undefined,target=existing?p:plus(p,faceOffset(face));let revision=-1;if(existing)try{revision=store.load(cellarCabinetKey(d.id,p))?.revision??-1;}catch{}system.run(()=>safe(e.player,()=>{sameHand(e.player,hs);check(e.player.dimension.id===d.id,'DIMENSION_CHANGED');const clicked=blockAt(d,p);check(clicked?.typeId===id,'BLOCK_CHANGED');if([NS+':guidebook',NS+':recipe_book'].includes(hs.id))return openBook(e.player,hs.id.endsWith(':recipe_book'));if(!existing){check(e.player.isSneaking,'SNEAK_TO_PLACE');return placeCellarCabinet(e.player,target);}if(!hs.id&&e.player.isSneaking)return recoverCellarCabinet(e.player,clicked,{expectedRevision:revision});if(!hs.id||cellarCabinetItem(hs.id))return useCellarCabinet(e.player,clicked,face,loc,{expectedRevision:revision});tell(e.player,'§e[Tavern] 窖藏酒櫃只接受來源允許的酒瓶；必須點正面九宮格。');}));});world.beforeEvents.playerBreakBlock.subscribe(e=>{if(e.cancel||e.block.typeId!==CELLAR_CABINET)return;e.cancel=true;const d=e.block.dimension,p={...e.block.location};let revision=-1;try{revision=store.load(cellarCabinetKey(d.id,p))?.revision??-1;}catch{}system.run(()=>safe(e.player,()=>{const b=blockAt(d,p);check(b?.typeId===CELLAR_CABINET,'BLOCK_CHANGED');return recoverCellarCabinet(e.player,b,{expectedRevision:revision,drop:true});}));});world.beforeEvents.explosion.subscribe(e=>e.setImpactedBlocks(e.getImpactedBlocks().filter(b=>b.typeId!==CELLAR_CABINET)));world.afterEvents.entityLoad.subscribe(e=>{if(e.entity.typeId===HELPER){visuals.set(e.entity.id,e.entity);system.run(()=>maintainCellarCabinetVisual(e.entity));}});system.runInterval(tickCellarCabinets,20);}
export const CELLAR_CABINET_TEST={store,visuals,HELPER,ANCHOR};
