import {world,system,BlockPermutation,ItemStack} from '@minecraft/server';
import {ModalFormData} from '@minecraft/server-ui';
import {NS,DYE_COLORS,ALIGNMENTS,chalkKey,newChalk,validateChalk,editChalk,dyeChalk,glowChalk,waxChalk,mergeableChalk,ChalkStore} from '../core/chalkboard-c7.js';
import {facingForYaw,facingYaw,faceOffset,dyeColor} from '../core/furniture.js';
import {Locks} from '../core/storage.js';
import {check} from '../core/util.js';
import {makeStack,hand,canWrite,blockAt,plus,tell,safe,handSnapshot,sameHand,inventory} from './transactions.js';
const CORE=NS+':chalkboard_core',PART=NS+':chalkboard_part',ITEM=NS+':chalkboard',ANCHOR='kt:chalk_anchor',TEXT=NS+':chalk_text_display',store=new ChalkStore(world),locks=new Locks(),editing=new Map();
export const chalkDiagnostics={placed:0,merged:0,edited:0,dyed:0,waxed:0,glowChanged:0,recovered:0,helpers:0,errors:[],renderAdapter:'entity nametag; font/alignment/glow not engine-parity'};
function log(e){chalkDiagnostics.errors.push(String(e));if(chalkDiagnostics.errors.length>16)chalkDiagnostics.errors.shift();}
function coreKey(b){return chalkKey(b.dimension.id,b.location);}
function localAxis(f){return f%2===0?'x':'z';}
function sideOffsets(f){return localAxis(f)==='x'?[{x:-1,y:0,z:0},{x:1,y:0,z:0}]:[{x:0,y:0,z:-1},{x:0,y:0,z:1}];}
function cells(p,size,f){const out=[{...p,core:true,dx:0,dy:0,dz:0},{x:p.x,y:p.y+1,z:p.z,dx:0,dy:1,dz:0}];if(size==='large')for(const o of sideOffsets(f))for(let y=0;y<2;y++)out.push({x:p.x+o.x,y:p.y+y,z:p.z+o.z,dx:o.x,dy:y,dz:o.z});return out;}
function resolveCore(block){if(block?.typeId===CORE)return block;if(block?.typeId!==PART)return;const p=block.location;return blockAt(block.dimension,{x:p.x-(block.permutation.getState(NS+':dx')??0),y:p.y-(block.permutation.getState(NS+':dy')??0),z:p.z-(block.permutation.getState(NS+':dz')??0)});}
function visuals(core,state){const k=coreKey(core),near=core.dimension.getEntities({families:['kt_chalk_helper'],location:{x:core.location.x+.5,y:core.location.y+1,z:core.location.z+.5},maxDistance:3}).filter(e=>e.getDynamicProperty(ANCHOR)===k),wantModel=NS+':chalkboard_'+state.size+'_visual';let model,text;for(const e of near){if(e.typeId===wantModel&&!model)model=e;else if(e.typeId===TEXT&&!text)text=e;else try{e.remove();}catch{}}
 if(!model){model=core.dimension.spawnEntity(wantModel,{x:core.location.x+.5,y:core.location.y,z:core.location.z+.5});model.setDynamicProperty(ANCHOR,k);model.addTag?.('kaleidoscope_tavern:visual_helper');chalkDiagnostics.helpers++;}model.setRotation({x:0,y:facingYaw(state.facing)});
 const pos={0:{x:.5,y:1.535,z:.92},1:{x:.08,y:1.535,z:.5},2:{x:.5,y:1.535,z:.08},3:{x:.92,y:1.535,z:.5}}[state.facing];if(!text){text=core.dimension.spawnEntity(TEXT,{x:core.location.x+pos.x,y:core.location.y+pos.y,z:core.location.z+pos.z});text.setDynamicProperty(ANCHOR,k);text.addTag?.('kaleidoscope_tavern:visual_helper');chalkDiagnostics.helpers++;}else text.tryTeleport?.({x:core.location.x+pos.x,y:core.location.y+pos.y,z:core.location.z+pos.z},{checkForBlocks:false});text.setRotation({x:0,y:facingYaw(state.facing)});const codes={white:'f',light_gray:'7',gray:'8',black:'0',brown:'6',red:'c',orange:'6',yellow:'e',lime:'a',green:'2',cyan:'3',light_blue:'b',blue:'9',purple:'5',magenta:'d',pink:'d'};const lines=state.text.split('\n').slice(0,11);text.nameTag=`§${codes[state.color]??'f'}${state.glowing?'§l':''}${lines.join('\n')}`;return {model,text};}
function removeVisuals(core){const k=coreKey(core);for(const e of core.dimension.getEntities({families:['kt_chalk_helper'],location:{x:core.location.x+.5,y:core.location.y+1,z:core.location.z+.5},maxDistance:3}))if(e.getDynamicProperty(ANCHOR)===k)try{e.remove();}catch{}}
function setStructure(core,state){for(const c of cells(core.location,state.size,state.facing)){const b=blockAt(core.dimension,c);check(b,'UNLOADED_TARGET');if(c.core)b.setPermutation(BlockPermutation.resolve(CORE,{[NS+':facing']:state.facing,[NS+':size']:state.size}));else b.setPermutation(BlockPermutation.resolve(PART,{[NS+':dx']:c.dx,[NS+':dy']:c.dy,[NS+':dz']:c.dz}));}visuals(core,state);}
function clearStructure(core,state){for(const c of cells(core.location,state.size,state.facing)){const b=blockAt(core.dimension,c);if(b&&[CORE,PART].includes(b.typeId))b.setType('minecraft:air');}removeVisuals(core);}
function consumeOne(player){const c=inventory(player),i=player.selectedSlotIndex,h=c.getItem(i);check(h?.typeId===ITEM,'STALE_HAND');if(h.amount===1)c.setItem(i,undefined);else{h.amount--;c.setItem(i,h);}}
export function placeChalk(player,pos){canWrite(player);const facing=facingForYaw(player.getRotation().y),state=newChalk('small',facing),needed=cells(pos,'small',facing).map(c=>blockAt(player.dimension,c));check(needed.every(b=>b?.isAir),'SPACE_NOT_CLEAR');consumeOne(player);const core=needed[0],k=chalkKey(player.dimension.id,pos);try{store.save(k,state,-1);setStructure(core,state);}catch(e){try{store.restore(k,undefined);for(const b of needed)b?.setType('minecraft:air');}catch{}throw e;}chalkDiagnostics.placed++;system.run(()=>tryMerge(core));return core;}
export function tryMerge(core){try{const s=store.load(coreKey(core));if(!mergeableChalk(s,s.facing))return false;const sides=sideOffsets(s.facing),candidates=[];for(let start=-2;start<=0;start++){const arr=[];for(let i=0;i<3;i++){const n=start+i,o={x:sides[1].x*n,y:0,z:sides[1].z*n},b=blockAt(core.dimension,plus(core.location,o));if(b?.typeId!==CORE){arr.length=0;break;}const st=store.load(coreKey(b));if(!mergeableChalk(st,s.facing)){arr.length=0;break;}arr.push([b,st]);}if(arr.length===3&&arr.some(x=>x[0].location.x===core.location.x&&x[0].location.z===core.location.z)){candidates.push(arr);break;}}if(!candidates.length)return false;const arr=candidates[0],mid=arr[1][0],newState={...arr[1][1],size:'large',revision:arr[1][1].revision+1};for(const[b,st]of arr){if(b.location.x===mid.location.x&&b.location.y===mid.location.y&&b.location.z===mid.location.z)continue;clearStructure(b,st);store.remove(coreKey(b),st.revision);}clearStructure(mid,arr[1][1]);store.save(coreKey(mid),newState,arr[1][1].revision);setStructure(mid,newState);chalkDiagnostics.merged++;return true;}catch(e){log(e);return false;}}
async function edit(player,core,state){const k=coreKey(core);check(!state.waxed,'CHALK_WAXED');const held=editing.get(k);check(!held||held===player.id,'CHALK_EDIT_LOCKED');editing.set(k,player.id);try{const result=await new ModalFormData().title(state.size==='large'?'Large Chalkboard':'Chalkboard').textField('Text / 文字',state.size==='large'?'最多1500字':'最多350字',{defaultValue:state.text}).dropdown('Alignment / 對齊',['Left / 左','Center / 中','Right / 右'],{defaultValueIndex:ALIGNMENTS.indexOf(state.alignment)}).show(player);if(result.canceled)return;check(player.dimension.id===core.dimension.id&&Math.hypot(player.location.x-core.location.x,player.location.y-core.location.y,player.location.z-core.location.z)<=8,'OUT_OF_REACH');const current=store.load(k);check(current?.revision===state.revision,'STATE_CONFLICT');const next=editChalk(current,{text:String(result.formValues?.[0]??''),alignment:ALIGNMENTS[result.formValues?.[1]??1]});store.save(k,next,current.revision);visuals(core,next);chalkDiagnostics.edited++;}finally{if(editing.get(k)===player.id)editing.delete(k);}}
export function interactChalk(player,block){const core=resolveCore(block);check(core,'CHALK_CORE_MISSING');const k=coreKey(core),s=store.load(k);check(s,'MISSING_CHALK');const h=hand(player);if(s.waxed){tell(player,'§7黑板已上蠟，無法修改。');return;}const dye=dyeColor(h?.typeId);if(dye){consumeOne(player);const n=dyeChalk(s,dye);store.save(k,n,s.revision);visuals(core,n);chalkDiagnostics.dyed++;return;}if(h?.typeId==='minecraft:glow_ink_sac'&&!s.glowing){consumeOne(player);const n=glowChalk(s,true);store.save(k,n,s.revision);visuals(core,n);chalkDiagnostics.glowChanged++;return;}if(h?.typeId==='minecraft:ink_sac'&&s.glowing){consumeOne(player);const n=glowChalk(s,false);store.save(k,n,s.revision);visuals(core,n);chalkDiagnostics.glowChanged++;return;}if(h?.typeId==='minecraft:honeycomb'){consumeOne(player);const n=waxChalk(s);store.save(k,n,s.revision);visuals(core,n);chalkDiagnostics.waxed++;return;}if(!h)return edit(player,core,s);tell(player,'§e[Tavern] 空手編輯；染料改色；螢光墨/墨囊切換發光；蜂巢上蠟。');}
export function recoverChalk(player,block){canWrite(player);const core=resolveCore(block);check(core,'CHALK_CORE_MISSING');const k=coreKey(core),s=store.load(k);check(s,'MISSING_CHALK');const c=inventory(player);let slot=-1;for(let i=0;i<c.size;i++){const x=c.getItem(i);if(x?.typeId===ITEM&&x.amount<x.maxAmount){slot=i;break;}if(!x&&slot<0)slot=i;}check(slot>=0,'INVENTORY_FULL');const old=c.getItem(slot),give=old?old.clone():new ItemStack(ITEM,1);if(old)give.amount++;try{c.setItem(slot,give);clearStructure(core,s);store.remove(k,s.revision);}catch(e){try{c.setItem(slot,old);store.restore(k,JSON.stringify(s));setStructure(core,s);}catch{}throw e;}chalkDiagnostics.recovered++;}
export function registerChalkComponents({blockComponentRegistry:r}){r.registerCustomComponent(NS+':chalk_core',{onTick:e=>{try{const s=store.load(coreKey(e.block));if(s)visuals(e.block,s);}catch(x){log(x);}}});r.registerCustomComponent(NS+':chalk_part',{});}
export function installChalkEvents(){world.beforeEvents.playerInteractWithBlock.subscribe(e=>{if(e.cancel)return;const is=[CORE,PART].includes(e.block.typeId),hs=handSnapshot(e.player);if(!is&&hs.id!==ITEM)return;e.cancel=true;if(e.isFirstEvent===false)return;const d=e.block.dimension,p={...e.block.location},id=e.block.typeId,target=is?p:plus(p,faceOffset(e.blockFace));system.run(()=>safe(e.player,()=>{sameHand(e.player,hs);const b=blockAt(d,p);check(b?.typeId===id,'BLOCK_CHANGED');if(!is){check(e.player.isSneaking,'SNEAK_TO_PLACE');return placeChalk(e.player,target);}return interactChalk(e.player,b);}));});world.beforeEvents.playerBreakBlock.subscribe(e=>{if(e.cancel||![CORE,PART].includes(e.block.typeId))return;e.cancel=true;const d=e.block.dimension,p={...e.block.location},id=e.block.typeId;system.run(()=>safe(e.player,()=>{const b=blockAt(d,p);check(b?.typeId===id,'BLOCK_CHANGED');return recoverChalk(e.player,b);}));});world.beforeEvents.explosion.subscribe(e=>e.setImpactedBlocks(e.getImpactedBlocks().filter(b=>![CORE,PART].includes(b.typeId))));}
export const CHALK_TEST={store,editing,resolveCore,cells};
