import {world,system,BlockPermutation} from '@minecraft/server';
import {NS,CIRCULAR_RACK,circularRackItem,circularRackSlot,emptyCircularRack,circularRackPut,circularRackTake,circularRackKey,circularRackAnchor,parseCircularRackAnchor,circularRackVisualPose,circularParticlePoint,CircularRackStore} from '../core/circular-rack.js';
import {FACING,facingForYaw,faceOffset} from '../core/furniture.js';
import {check} from '../core/util.js';
import {planInventory,commitInventory,isPlainIngredient} from '../core/inventory.js';
import {makeStack,hand,inventory,handSnapshot,sameHand,canWrite,blockAt,plus,tell,safe,finishPlayerBreak,air} from './transactions.js';
const HELPER=NS+':circular_rack_bottle_visual',ANCHOR=NS+':circular_rack_anchor',store=new CircularRackStore(world),visuals=new Map();let cursor=0;
export const circularRackDiagnostics={placed:0,inserted:0,taken:0,recovered:0,spawned:0,orphans:0,duplicates:0,particles:0,errors:[],redstone:'NOT_ADAPTED'};
function error(e){circularRackDiagnostics.errors.push(String(e));if(circularRackDiagnostics.errors.length>16)circularRackDiagnostics.errors.shift();}
function center(p){return {x:p.x+.5,y:p.y+.5,z:p.z+.5};}
function near(player,d,p){check(player.dimension.id===d.id,'DIMENSION_CHANGED');check(Math.hypot(player.location.x-p.x-.5,player.location.y-p.y-.5,player.location.z-p.z-.5)<=6,'OUT_OF_REACH');}
function slotHelpers(block,slot){const a=circularRackAnchor(circularRackKey(block.dimension.id,block.location),slot);return block.dimension.getEntities({type:HELPER,location:center(block.location),maxDistance:2}).filter(e=>e.getDynamicProperty(ANCHOR)===a);}
function discard(e,reason){e.remove();visuals.delete(e.id);circularRackDiagnostics[reason]=(circularRackDiagnostics[reason]??0)+1;}
function position(block,slot,facing){const p=circularRackVisualPose(slot,facing).offset;return {x:block.location.x+p.x,y:block.location.y+p.y,z:block.location.z+p.z};}
export function syncCircularRackVisuals(block,state=store.load(circularRackKey(block.dimension.id,block.location))){if(state)check(block?.typeId===CIRCULAR_RACK,'NOT_CIRCULAR_RACK');const facing=block?.permutation.getState(FACING)??0;for(let slot=0;slot<6;slot++){const item=state?.slots[slot]??null,all=slotHelpers(block,slot);if(!item){for(const e of all)discard(e,'orphans');continue;}const bottle=circularRackItem(item);check(bottle,'CIRCULAR_RACK_ITEM');all.sort((a,b)=>a.id.localeCompare(b.id));let e=all[0];for(const x of all.slice(1))discard(x,'duplicates');const at=position(block,slot,facing),pose=circularRackVisualPose(slot,facing);if(!e){e=block.dimension.spawnEntity(HELPER,at);e.setDynamicProperty(ANCHOR,circularRackAnchor(circularRackKey(block.dimension.id,block.location),slot));e.addTag('kaleidoscope_tavern:visual_helper');circularRackDiagnostics.spawned++;}e.setProperty(NS+':storage_kind',bottle.kind);e.setRotation(pose.rotation);e.tryTeleport(at,{checkForBlocks:false});visuals.set(e.id,e);}}
function visualSafe(block,state){try{syncCircularRackVisuals(block,state);}catch(e){error(e);}}
function transact(player,block,old,next,take,give,permutation){const k=circularRackKey(block.dimension.id,block.location),raw=store.raw(k),oldPermutation=block.permutation,c=inventory(player),plan=planInventory(c,player.selectedSlotIndex,take,give,makeStack);commitInventory(plan,c,()=>{block.setPermutation(permutation);store.save(k,next,old?.revision??-1);},()=>{block.setPermutation(oldPermutation);store.restore(k,raw);});visualSafe(block,next);return next;}
export function placeCircularRack(player,target){canWrite(player);const d=player.dimension;near(player,d,target);const b=blockAt(d,target);check(b&&b.isAir,'SPACE_NOT_CLEAR');const h=hand(player);check(h?.typeId===CIRCULAR_RACK,'NEED_CIRCULAR_RACK');check(isPlainIngredient(h,makeStack),'METADATA_ITEM_REJECTED');const k=circularRackKey(d.id,target);check(store.raw(k)===undefined,'STORAGE_CONFLICT');const state=emptyCircularRack(),facing=facingForYaw(player.getRotation().y),c=inventory(player),plan=planInventory(c,player.selectedSlotIndex,1,[],makeStack),old=b.permutation;commitInventory(plan,c,()=>{b.setPermutation(BlockPermutation.resolve(CIRCULAR_RACK,{[FACING]:facing}));store.save(k,state,-1);},()=>{b.setPermutation(old);store.restore(k,undefined);});circularRackDiagnostics.placed++;return b;}
export function putCircularRackBottle(player,block,faceLocation,{expectedRevision}={}){canWrite(player);near(player,block.dimension,block.location);check(block.typeId===CIRCULAR_RACK,'NOT_CIRCULAR_RACK');const k=circularRackKey(block.dimension.id,block.location),old=store.load(k);check(old,'MISSING_CIRCULAR_RACK_STATE');if(expectedRevision!==undefined)check(old.revision===expectedRevision,'STATE_CONFLICT');const h=hand(player),bottle=circularRackItem(h?.typeId);check(bottle,'NOT_CIRCULAR_RACK_BOTTLE');check(isPlainIngredient(h,makeStack),'METADATA_ITEM_REJECTED');const slot=circularRackSlot(block.permutation.getState(FACING)??0,faceLocation);if(old.slots[slot]!==null)return false;const next=circularRackPut(old,slot,h.typeId);transact(player,block,old,next,1,[],block.permutation);circularRackDiagnostics.inserted++;return {slot,state:next};}
export function takeCircularRackBottle(player,block,faceLocation,{expectedRevision}={}){canWrite(player);near(player,block.dimension,block.location);check(!hand(player),'EMPTY_HAND_REQUIRED');const k=circularRackKey(block.dimension.id,block.location),old=store.load(k);check(old,'MISSING_CIRCULAR_RACK_STATE');if(expectedRevision!==undefined)check(old.revision===expectedRevision,'STATE_CONFLICT');const slot=circularRackSlot(block.permutation.getState(FACING)??0,faceLocation);if(old.slots[slot]===null)return false;const tx=circularRackTake(old,slot);transact(player,block,old,tx.state,0,[{id:tx.item,count:1}],block.permutation);circularRackDiagnostics.taken++;return {slot,item:tx.item,state:tx.state};}
export function recoverCircularRack(player,block,{expectedRevision}={}){canWrite(player);near(player,block.dimension,block.location);check(block.typeId===CIRCULAR_RACK,'NOT_CIRCULAR_RACK');const k=circularRackKey(block.dimension.id,block.location),old=store.load(k);check(old,'MISSING_CIRCULAR_RACK_STATE');if(expectedRevision!==undefined)check(old.revision===expectedRevision,'STATE_CONFLICT');const give=[{id:CIRCULAR_RACK,count:1},...old.slots.filter(Boolean).map(id=>({id,count:1}))];transact(player,block,old,undefined,0,give,air());circularRackDiagnostics.recovered++;return give;}
export function pulseCircularRackParticle(block,random=Math.random){try{if(block?.typeId!==CIRCULAR_RACK)return false;const state=store.load(circularRackKey(block.dimension.id,block.location));if(!state?.slots.some(Boolean))return false;block.dimension.spawnParticle('minecraft:endrod',circularParticlePoint(block.location,random));circularRackDiagnostics.particles++;return true;}catch(e){error(e);return false;}}
export function maintainCircularRackVisual(e){if(e?.typeId!==HELPER)return;try{const a=parseCircularRackAnchor(e.getDynamicProperty(ANCHOR));if(e.dimension.id!==a.dimension){discard(e,'orphans');return;}const block=blockAt(e.dimension,a.position);if(!block)return;if(block.typeId!==CIRCULAR_RACK){discard(e,'orphans');return;}const state=store.load(circularRackKey(e.dimension.id,a.position));if(!state?.slots[a.slot]){discard(e,'orphans');return;}visuals.set(e.id,e);syncCircularRackVisuals(block,state);}catch(x){error(x);try{discard(e,'orphans');}catch{}}}
export function tickCircularRackVisuals(){const list=[...visuals.values()];if(!list.length)return;const n=Math.min(128,list.length);for(let i=0;i<n;i++)maintainCircularRackVisual(list[(cursor+i)%list.length]);cursor=(cursor+n)%Math.max(list.length,1);}
export function registerCircularRackComponents({blockComponentRegistry:r}){r.registerCustomComponent(NS+':circular_rack',{onTick:e=>{try{const s=store.load(circularRackKey(e.block.dimension.id,e.block.location));if(s)syncCircularRackVisuals(e.block,s);pulseCircularRackParticle(e.block);}catch(x){error(x);}}});}
export function installCircularRackEvents(openBook){world.beforeEvents.playerInteractWithBlock.subscribe(e=>{if(e.cancel)return;const existing=e.block.typeId===CIRCULAR_RACK,hs=handSnapshot(e.player),placing=!existing&&hs.id===CIRCULAR_RACK;if(!existing&&!placing)return;e.cancel=true;if(e.isFirstEvent===false)return;const d=e.block.dimension,p={...e.block.location},id=e.block.typeId,face=e.blockFace,faceLocation=e.faceLocation?{...e.faceLocation}:undefined,target=existing?p:plus(p,faceOffset(face));let revision=-1;if(existing)try{revision=store.load(circularRackKey(d.id,p))?.revision??-1;}catch{}system.run(()=>safe(e.player,()=>{sameHand(e.player,hs);check(e.player.dimension.id===d.id,'DIMENSION_CHANGED');const clicked=blockAt(d,p);check(clicked?.typeId===id,'BLOCK_CHANGED');if([NS+':guidebook',NS+':recipe_book'].includes(hs.id))return openBook(e.player,hs.id.endsWith(':recipe_book'));if(!existing){check(e.player.isSneaking,'SNEAK_TO_PLACE');return placeCircularRack(e.player,target);}if(!hs.id)return e.player.isSneaking?recoverCircularRack(e.player,clicked,{expectedRevision:revision}):takeCircularRackBottle(e.player,clicked,faceLocation,{expectedRevision:revision});if(circularRackItem(hs.id))return putCircularRackBottle(e.player,clicked,faceLocation,{expectedRevision:revision});tell(e.player,'§e[Tavern] 圓形酒架只接受空酒瓶或品質酒瓶；空手取指定槽。');}));});world.beforeEvents.playerBreakBlock.subscribe(e=>{if(e.cancel||e.block.typeId!==CIRCULAR_RACK)return;e.cancel=true;const d=e.block.dimension,p={...e.block.location};let revision=-1;try{revision=store.load(circularRackKey(d.id,p))?.revision??-1;}catch{}system.run(()=>safe(e.player,()=>{const b=blockAt(d,p);check(b?.typeId===CIRCULAR_RACK,'BLOCK_CHANGED');return finishPlayerBreak(e.player,d,p,CIRCULAR_RACK,()=>recoverCircularRack(e.player,b,{expectedRevision:revision}));}));});world.beforeEvents.explosion.subscribe(e=>e.setImpactedBlocks(e.getImpactedBlocks().filter(b=>b.typeId!==CIRCULAR_RACK)));world.afterEvents.entityLoad.subscribe(e=>{if(e.entity.typeId===HELPER){visuals.set(e.entity.id,e.entity);system.run(()=>maintainCircularRackVisual(e.entity));}});system.runInterval(tickCircularRackVisuals,20);}
export const CIRCULAR_RACK_TEST={store,visuals,HELPER,ANCHOR};
