/** C7 custom-effect adapters. Exact source rules are kept where Bedrock exposes equivalent primitives. */
import {world,system,ItemStack} from '@minecraft/server';
import {C7_STATUS_KEY,C7_EFFECTS,C7_PENDING,readC7Status,addC7Status,advanceC7Status,c7Active,tipsyRoll,visionRadius,GRASS_STEALTH_PLANTS,ARDENT_BREAKABLE,TOMB_DISARMABLE,ardentFront,tombRoll,upsideRange} from '../core/effects-c7.js';
const tracks=new Map(),lastPos=new Map();
export const c7EffectDiagnostics={applied:0,visionScans:0,visionMarks:0,grassTicks:0,stepAssists:0,ardentBlocks:0,tombDisarms:0,upsideRenames:0,tipsyCommands:0,errors:[],pending:C7_PENDING};
function err(e){c7EffectDiagnostics.errors.push(String(e));if(c7EffectDiagnostics.errors.length>24)c7EffectDiagnostics.errors.shift();}
function write(p,s){p.setDynamicProperty(C7_STATUS_KEY,s.entries.length?JSON.stringify(s):undefined);tracks.set(p.id,{player:p,tick:system.currentTick});}
export function c7StatusNow(p){const s=readC7Status(p.getDynamicProperty(C7_STATUS_KEY)),t=tracks.get(p.id);return advanceC7Status(s,t?Math.max(0,system.currentTick-t.tick):0);}
export function clearC7Effects(p){try{if(p.runCommand)p.runCommand('camerashake stop @s');}catch{}write(p,{schema:1,entries:[]});tracks.delete(p.id);lastPos.delete(p.id);}
function grumm(p){let n=0;for(const e of p.dimension.getEntities({location:p.location,maxDistance:upsideRange()})){if(e.id===p.id||e.typeId==='minecraft:player'||e.typeId==='minecraft:item'||e.typeId==='minecraft:xp_orb'||e.hasTag?.('kaleidoscope_tavern:visual_helper'))continue;try{if(!e.getComponent?.('minecraft:health'))continue;e.nameTag='Grumm';n++;}catch(x){err(x);}}c7EffectDiagnostics.upsideRenames+=n;return true;}
export function applyC7Effect(p,row){
 if(!p||p.typeId!=='minecraft:player')return false;
 if(row.effect==='kaleidoscope_tavern:long_reach')return false;
 if(row.effect==='kaleidoscope_tavern:upside_down')return grumm(p);
 if(!C7_EFFECTS[row.effect])return false;
 const ticks=Math.max(1,Math.trunc(row.duration*20));write(p,addC7Status(c7StatusNow(p),row.effect,ticks,row.amplifier));c7EffectDiagnostics.applied++;return true;
}
function inStealthPlant(p){try{const base={x:Math.floor(p.location.x),y:Math.floor(p.location.y),z:Math.floor(p.location.z)};return GRASS_STEALTH_PLANTS.has(p.dimension.getBlock(base)?.typeId)||GRASS_STEALTH_PLANTS.has(p.dimension.getBlock({...base,y:base.y+1})?.typeId);}catch{return false;}}
function tickGrass(p){if(!p.isSneaking||!inStealthPlant(p))return;try{p.addEffect('invisibility',12,{amplifier:0,showParticles:false});c7EffectDiagnostics.grassTicks++;}catch(e){err(e);}for(const e of p.dimension.getEntities({location:p.location,maxDistance:32}).slice(0,128)){try{const t=e.getComponent?.('minecraft:target');if(t?.target?.id===p.id){try{t.target=undefined;}catch{} }}catch{}}}
function tickVision(p,entry){if(system.currentTick%50!==0)return;const radius=visionRadius(entry.amplifier);c7EffectDiagnostics.visionScans++;let any=false;for(const e of p.dimension.getEntities({location:p.location,maxDistance:radius}).slice(0,256)){if(e.id===p.id)continue;try{if(!e.getComponent?.('minecraft:health'))continue;const had=!!e.getEffect?.('glowing');e.addEffect?.('glowing',60,{amplifier:0,showParticles:false});if(!had)any=true;c7EffectDiagnostics.visionMarks++;}catch(x){err(x);}}if(any)try{p.dimension.playSound('kaleidoscope_tavern:effect.vision',p.location,{volume:.7,pitch:1});}catch{}}
function tickTipsy(p){if(system.currentTick%10!==0)return;try{if(p.runCommand){const roll=Math.abs(tipsyRoll(system.currentTick));p.runCommand(`camerashake add @s ${Math.max(.02,Math.min(.18,roll*.12)).toFixed(3)} 0.6 rotational`);c7EffectDiagnostics.tipsyCommands++;}}catch(e){err(e);}}
function tickHighHeels(p){const last=lastPos.get(p.id);lastPos.set(p.id,{...p.location});if(!last)return;const dx=p.location.x-last.x,dz=p.location.z-last.z;if(Math.hypot(dx,dz)<.03)return;const dir=Math.abs(dx)>=Math.abs(dz)?{x:Math.sign(dx),z:0}:{x:0,z:Math.sign(dz)},base={x:Math.floor(p.location.x),y:Math.floor(p.location.y),z:Math.floor(p.location.z)},front={x:base.x+dir.x,y:base.y,z:base.z+dir.z};try{const obstacle=p.dimension.getBlock(front),up=p.dimension.getBlock({...front,y:front.y+1}),head=p.dimension.getBlock({...front,y:front.y+2});if(obstacle&&!obstacle.isAir&&up?.isAir&&head?.isAir&&p.tryTeleport({x:p.location.x,y:p.location.y+1,z:p.location.z},{checkForBlocks:true})){c7EffectDiagnostics.stepAssists++;}}catch(e){err(e);}}
function tickArdent(p,entry){if(!p.isSprinting)return;const dir=p.getViewDirection?.()??{x:0,z:1};let broke=0;for(const pos of ardentFront(p.location,dir)){try{const b=p.dimension.getBlock(pos);if(!b||!ARDENT_BREAKABLE.has(b.typeId))continue;const id=b.typeId;b.setType('minecraft:air');try{p.dimension.spawnItem?.(new ItemStack(id,1),{x:pos.x+.5,y:pos.y+.5,z:pos.z+.5});}catch{}broke++;}catch(e){err(e);}}if(broke){c7EffectDiagnostics.ardentBlocks+=broke;try{p.addEffect('hunger',40,{amplifier:0,showParticles:false});}catch{}}if(entry.ticks<=5)try{p.addEffect('hunger',600,{amplifier:0,showParticles:true});}catch{}}
function disarmable(id){return TOMB_DISARMABLE.has(id)||id.startsWith('minecraft:zombie_');}
export function handleC7Hurt(event,rng=Math.random){try{const p=event.damageSource?.damagingEntity,target=event.hurtEntity;if(!p||p.typeId!=='minecraft:player'||!target||!c7Active(c7StatusNow(p),'kaleidoscope_tavern:tomb_raider')||!disarmable(target.typeId)||!tombRoll(rng()))return false;const eq=target.getComponent?.('minecraft:equippable');if(!eq)return false;let stack=eq.getEquipment?.('Mainhand');if(!stack)return false;stack=stack.clone();const dur=stack.getComponent?.('minecraft:durability');if(dur)dur.damage=Math.max(0,dur.maxDurability-1);eq.setEquipment?.('Mainhand',undefined);const drop=target.dimension.spawnItem?.(stack,target.location);try{drop?.addTag?.('kaleidoscope_tavern:tomb_raider_drop');}catch{}c7EffectDiagnostics.tombDisarms++;return true;}catch(e){err(e);return false;}}
export function tickC7Effects(){const players=world.getAllPlayers(),seen=new Set(players.map(p=>p.id));for(const p of players)try{const before=c7StatusNow(p);if(!before.entries.length){if(p.getDynamicProperty(C7_STATUS_KEY)!==undefined)clearC7Effects(p);continue;}for(const e of before.entries){if(e.id==='kaleidoscope_tavern:slightly_tipsy')tickTipsy(p);else if(e.id==='kaleidoscope_tavern:high_heels')tickHighHeels(p);else if(e.id==='kaleidoscope_tavern:grass_stealth')tickGrass(p);else if(e.id==='kaleidoscope_tavern:vision')tickVision(p,e);else if(e.id==='kaleidoscope_tavern:ardent_heat')tickArdent(p,e);}write(p,before);}catch(e){err(e);}for(const[id,t]of tracks)if(!seen.has(id)){try{write(t.player,c7StatusNow(t.player));}catch{}tracks.delete(id);lastPos.delete(id);}}
export function installC7Effects(){world.afterEvents.entityHurt?.subscribe(e=>handleC7Hurt(e));world.afterEvents.entityDie?.subscribe(e=>{if(e.deadEntity?.typeId==='minecraft:player')try{clearC7Effects(e.deadEntity);}catch(x){err(x);}});world.afterEvents.itemCompleteUse?.subscribe(e=>{if(e.itemStack?.typeId==='minecraft:milk_bucket')try{clearC7Effects(e.source);}catch(x){err(x);}});world.afterEvents.playerLeave?.subscribe(e=>{tracks.delete(e.playerId);lastPos.delete(e.playerId);});system.runInterval(tickC7Effects,5);}
