import {world,system,GameMode,BlockPermutation} from '@minecraft/server';
import {NS,MOLOTOV,throwReady,launchVelocity,ignitionOffsets} from '../core/molotov-c7.js';
import {inventory,hand} from './transactions.js';
const PROJECTILE=NS+':thrown_molotov',starts=new Map(),handled=new Set();
export const molotovDiagnostics={starts:0,throws:0,impacts:0,fires:0,cancelled:0,errors:[]};
function err(e){molotovDiagnostics.errors.push(String(e));if(molotovDiagnostics.errors.length>16)molotovDiagnostics.errors.shift();}
function consume(player){if(player.getGameMode()===GameMode.Creative)return;const c=inventory(player),i=player.selectedSlotIndex,h=c.getItem(i);if(!h||h.typeId!==MOLOTOV)return false;if(h.amount===1)c.setItem(i,undefined);else{h.amount--;c.setItem(i,h);}return true;}
function throwIt(player,ticks){if(!throwReady(ticks)){molotovDiagnostics.cancelled++;return false;}const h=hand(player);if(!h||h.typeId!==MOLOTOV)return false;const origin=player.getHeadLocation?.()??{...player.location,y:player.location.y+1.5};const e=player.dimension.spawnEntity(PROJECTILE,origin);const v=launchVelocity(player.getViewDirection());try{e.applyImpulse(v);}catch(x){try{e.getComponent('minecraft:projectile')?.shoot(v);}catch(y){e.remove();throw y;}}consume(player);try{player.dimension.playSound('random.bow',origin,{volume:.5,pitch:.8});}catch{}molotovDiagnostics.throws++;return true;}
function ignite(projectile,location){if(!projectile||handled.has(projectile.id))return;handled.add(projectile.id);molotovDiagnostics.impacts++;const d=projectile.dimension,center={x:Math.floor(location.x),y:Math.floor(location.y),z:Math.floor(location.z)};for(const o of ignitionOffsets()){for(let dy=-1;dy<=1;dy++){try{const p={x:center.x+o.dx,y:center.y+dy,z:center.z+o.dz},b=d.getBlock(p),below=d.getBlock({x:p.x,y:p.y-1,z:p.z});if(b?.isAir&&below&&!below.isAir){b.setPermutation(BlockPermutation.resolve('minecraft:fire'));molotovDiagnostics.fires++;break;}}catch(e){err(e);}}}try{d.playSound('fire.ignite',location,{volume:2,pitch:1});d.playSound('random.glass',location,{volume:2,pitch:1});for(let i=0;i<30;i++)d.spawnParticle('minecraft:basic_flame_particle',{x:location.x+(Math.random()-.5)*3,y:location.y+Math.random(),z:location.z+(Math.random()-.5)*3});for(let i=0;i<20;i++)d.spawnParticle('minecraft:basic_smoke_particle',{x:location.x+(Math.random()-.5)*3,y:location.y+Math.random(),z:location.z+(Math.random()-.5)*3});}catch(e){err(e);}try{projectile.remove();}catch{}}
export function installMolotovC7(){world.afterEvents.itemStartUse?.subscribe(e=>{if(e.itemStack?.typeId===MOLOTOV){starts.set(e.source.id,{tick:system.currentTick,slot:e.source.selectedSlotIndex});molotovDiagnostics.starts++;}});const end=e=>{if(e.itemStack?.typeId!==MOLOTOV)return;const s=starts.get(e.source.id);starts.delete(e.source.id);if(s)try{throwIt(e.source,Math.max(0,system.currentTick-s.tick));}catch(x){err(x);}};world.afterEvents.itemReleaseUse?.subscribe(end);world.afterEvents.itemStopUse?.subscribe(e=>{if(!starts.has(e.source?.id))return;if(e.itemStack?.typeId===MOLOTOV)return;starts.delete(e.source.id);molotovDiagnostics.cancelled++;});world.afterEvents.projectileHitBlock?.subscribe(e=>{if(e.projectile?.typeId===PROJECTILE)ignite(e.projectile,e.location??e.getBlockHit?.()?.block?.location??e.projectile.location);});world.afterEvents.projectileHitEntity?.subscribe(e=>{if(e.projectile?.typeId===PROJECTILE)ignite(e.projectile,e.location??e.projectile.location);});world.afterEvents.playerLeave?.subscribe(e=>starts.delete(e.playerId));system.runInterval(()=>{if(handled.size>1024)handled.clear();},1200);}
export const MOLOTOV_TEST={starts,throwIt,ignite};
