/** C7 source-capacity bottle/cup furniture. World DP stores contents; visual helpers are disposable mirrors. */
import {world,system,BlockPermutation,ItemStack} from '@minecraft/server';
import {NS,STORAGE_SPECS,IRREGULAR_BASES,storageKey,itemClass,accepts,emptyStorage,validateStorage,putStorage,takeStorage,storageEmpty,DecorStore} from '../core/storage-display.js';
import {FACING,facingForYaw,facingYaw,faceOffset} from '../core/furniture.js';
import {cabinetPosition,rotateLocal} from '../core/decor-c7.js';
import {SIGNATURE,SIGNATURE_DATA,validatePayload} from '../core/mixology.js';
import {STORAGE_VISUALS,STORAGE_ANCHORS} from '../data/storage-visuals.js';
import {Locks} from '../core/storage.js';
import {check,utf8Bytes} from '../core/util.js';
import {makeStack,hand,canWrite,blockAt,plus,tell,safe,handSnapshot,sameHand,inventory,exchangeBlocks,air} from './transactions.js';
const POSITION=NS+':position',HELPER_ANCHOR='kt:storage_anchor',HELPER_SLOT='kt:storage_slot',store=new DecorStore(world),locks=new Locks();
export const storageDiagnostics={placed:0,inserted:0,removed:0,recovered:0,helpers:0,orphans:0,errors:[]};
function log(e){storageDiagnostics.errors.push(String(e));if(storageDiagnostics.errors.length>20)storageDiagnostics.errors.shift();}
export function storageBlockKind(id){for(const k of Object.keys(STORAGE_SPECS))if(id===NS+':'+k)return k;}
export function storageItemKind(id){for(const k of Object.keys(STORAGE_SPECS))if(id===NS+':'+k)return k;}
function center(p){return {x:p.x+.5,y:p.y,z:p.z+.5};}
function key(block){return storageKey(block.dimension.id,block.location);}
function snapshotItem(stack){const c=itemClass(stack?.typeId);check(c,'INVALID_DISPLAY_ITEM');const out={id:stack.typeId};if(stack.typeId===SIGNATURE){check(stack.amount===1,'SIGNATURE_NONSTACKABLE');const raw=stack.getDynamicProperty(SIGNATURE_DATA);check(typeof raw==='string'&&utf8Bytes(raw)<=12000,'COCKTAIL_SCHEMA');validatePayload(JSON.parse(raw));out.data=raw;}else{check(!stack.nameTag&&!stack.getLore?.().length&&!stack.getDynamicPropertyIds?.().length,'METADATA_ITEM_REJECTED');}return out;}
function restored(item){const s=new ItemStack(item.id,1);if(item.id===SIGNATURE){validatePayload(JSON.parse(item.data));s.setDynamicProperty(SIGNATURE_DATA,item.data);}return s;}
function localFromEvent(e){const f=e.faceLocation;return f&&Number.isFinite(f.x)?{x:f.x,y:f.y,z:f.z}:{x:.5,y:.5,z:.5};}
function chooseSlot(kind,state,local,forInsert=false){const spec=STORAGE_SPECS[kind];if(kind==='bar_cabinet'||kind==='glass_bar_cabinet'){if(state.single)return 0;let slot=local.x<.5?0:1;if(forInsert&&state.items[slot]&&!state.items[1-slot])slot=1-slot;if(!forInsert&&!state.items[slot]&&state.items[1-slot])slot=1-slot;return slot;}if(kind==='cellar_cabinet'){const col=Math.max(0,Math.min(2,Math.floor((1-local.x)*3))),row=Math.max(0,Math.min(2,Math.floor((1-local.y)*3)));return row*3+col;}if(kind==='tilted_rack')return Math.max(0,Math.min(2,Math.floor((1-local.x)*3)));if(kind==='circular_rack'){const pts=[[.5,.125],[.875,.3125],[.875,.6875],[.5,.875],[.125,.6875],[.125,.3125]];let best=0,dist=99;for(let i=0;i<6;i++){const d=(local.x-pts[i][0])**2+(local.z-pts[i][1])**2;if(d<dist){dist=d;best=i;}}return best;}if(kind==='holder')return 0;if(kind==='glassware_holder')return (local.z>.5?2:0)+(local.x>.5?1:0);return Math.min(spec.slots-1,0);}
function cabinetNeighbor(block,dx,dz){const b=blockAt(block.dimension,{x:block.location.x+dx,y:block.location.y,z:block.location.z+dz});return b?.typeId===block.typeId&&(b.permutation.getState(FACING)??0)===(block.permutation.getState(FACING)??0);}
function updateCabinetShape(block){const kind=storageBlockKind(block.typeId);if(!['bar_cabinet','glass_bar_cabinet','cellar_cabinet'].includes(kind))return;const f=block.permutation.getState(FACING)??0,dir=[[0,-1],[1,0],[0,1],[-1,0]][f],left=[-dir[1],dir[0]],right=[dir[1],-dir[0]],pos=cabinetPosition(cabinetNeighbor(block,left[0],left[1]),cabinetNeighbor(block,right[0],right[1]));if(block.permutation.getState(POSITION)!==pos)block.setPermutation(block.permutation.withState(POSITION,pos));}
function helperAt(block,slot){const anchor=STORAGE_ANCHORS[storageBlockKind(block.typeId)]?.[slot]??{x:.5,y:.5,z:.5,xRot:0,yRot:0};const r=rotateLocal(anchor,block.permutation.getState(FACING)??0);return {x:block.location.x+r.x,y:block.location.y+r.y,z:block.location.z+r.z,rot:{x:anchor.xRot??0,y:facingYaw(block.permutation.getState(FACING)??0)+(anchor.yRot??0)}};}
function nearbyHelpers(block){return block.dimension.getEntities({families:['kt_storage_visual'],location:center(block.location),maxDistance:2});}
function visualType(item){const c=itemClass(item.id);if(!c)return;const base=c.base;return STORAGE_VISUALS[base]??STORAGE_VISUALS[item.id];}
export function syncStorageVisuals(block,state){validateStorage(state);const k=key(block),existing=nearbyHelpers(block).filter(e=>e.getDynamicProperty(HELPER_ANCHOR)===k),wanted=new Map();for(let i=0;i<state.items.length;i++){const item=state.items[i];if(!item)continue;const type=visualType(item);if(type)wanted.set(i,type);}const kept=new Set();for(const e of existing){const slot=Number(e.getDynamicProperty(HELPER_SLOT));if(!wanted.has(slot)||wanted.get(slot)!==e.typeId||kept.has(slot)){try{e.remove();storageDiagnostics.orphans++;}catch{}continue;}kept.add(slot);const a=helperAt(block,slot);try{e.tryTeleport(a,{checkForBlocks:false});e.setRotation(a.rot);}catch{}}
 for(const [slot,type]of wanted)if(!kept.has(slot)){try{const a=helperAt(block,slot),e=block.dimension.spawnEntity(type,a);e.setDynamicProperty(HELPER_ANCHOR,k);e.setDynamicProperty(HELPER_SLOT,slot);e.addTag?.('kaleidoscope_tavern:visual_helper');e.setRotation(a.rot);storageDiagnostics.helpers++;}catch(x){log(x);}}
}
export function initializeStorage(block){const k=key(block);check(store.raw(k)===undefined,'STORAGE_CONFLICT');const state=emptyStorage(storageBlockKind(block.typeId),block.permutation.getState(FACING)??0);store.save(k,state,-1);syncStorageVisuals(block,state);return state;}
export function placeStorage(player,pos,kind){canWrite(player);const h=hand(player);check(h?.typeId===NS+':'+kind,'STALE_HAND');const b=blockAt(player.dimension,pos);check(b?.isAir,'SPACE_NOT_CLEAR');const facing=facingForYaw(player.getRotation().y),states={[FACING]:facing};if(['bar_cabinet','glass_bar_cabinet','cellar_cabinet'].includes(kind))states[POSITION]='single';exchangeBlocks(player,1,[],[{block:b,permutation:BlockPermutation.resolve(NS+':'+kind,states)}]);try{initializeStorage(b);}catch(e){b.setType('minecraft:air');throw e;}storageDiagnostics.placed++;return b;}
export function useStorage(player,block,local){canWrite(player);const kind=storageBlockKind(block.typeId),k=key(block);check(kind,'NOT_STORAGE');return locks.with([k,player.id],()=>{const state=store.load(k);check(state,'MISSING_STORAGE');const h=hand(player),raw=store.raw(k),container=inventory(player);if(h){const item=snapshotItem(h);check(accepts(kind,item.id),'INVALID_DISPLAY_ITEM');let slot=chooseSlot(kind,state,local,true);if(['bar_cabinet','glass_bar_cabinet'].includes(kind)&&IRREGULAR_BASES.has(itemClass(item.id)?.base))slot=0;const next=putStorage(state,slot,item);const before=Array.from({length:container.size},(_,i)=>container.getItem(i)),selected=player.selectedSlotIndex,held=container.getItem(selected);check(held&&held.typeId===item.id,'STALE_HAND');const after=before.map(x=>x?.clone());if(held.amount===1)after[selected]=undefined;else{after[selected]=held.clone();after[selected].amount--;}try{container.setItem(selected,after[selected]);store.save(k,next,state.revision);}catch(e){try{container.setItem(selected,before[selected]);store.restore(k,raw);}catch{}throw e;}syncStorageVisuals(block,next);storageDiagnostics.inserted++;return next;}const slot=chooseSlot(kind,state,local,false),tx=takeStorage(state,slot),stack=restored(tx.item);const before=Array.from({length:container.size},(_,i)=>container.getItem(i));let target=-1;for(let i=0;i<container.size;i++){const x=before[i];if(x&&x.isStackableWith?.(stack)&&x.amount<x.maxAmount){target=i;break;}}if(target<0)for(let i=0;i<container.size;i++)if(!before[i]){target=i;break;}check(target>=0,'INVENTORY_FULL');const old=before[target],give=old?old.clone():stack.clone();if(old)give.amount++;try{container.setItem(target,give);store.save(k,tx.state,state.revision);}catch(e){try{container.setItem(target,old);store.restore(k,raw);}catch{}throw e;}syncStorageVisuals(block,tx.state);storageDiagnostics.removed++;return tx.state;});}
export function recoverStorage(player,block){canWrite(player);const kind=storageBlockKind(block.typeId),k=key(block);check(kind,'NOT_STORAGE');return locks.with([k,player.id],()=>{const state=store.load(k);check(state,'MISSING_STORAGE');const outputs=[{id:NS+':'+kind,count:1},...state.items.filter(Boolean).map(x=>({stack:restored(x),count:1}))];const container=inventory(player),before=Array.from({length:container.size},(_,i)=>container.getItem(i)),after=before.map(x=>x?.clone());for(const out of outputs){const t=out.stack??new ItemStack(out.id,1);let target=-1;for(let i=0;i<after.length;i++){const x=after[i];if(x&&x.isStackableWith?.(t)&&x.amount<x.maxAmount){target=i;break;}}if(target<0)target=after.findIndex(x=>!x);check(target>=0,'INVENTORY_FULL');if(after[target])after[target].amount++;else after[target]=t.clone();}const changes=[];for(let i=0;i<after.length;i++)if((before[i]?.typeId??'')!==(after[i]?.typeId??'')||(before[i]?.amount??0)!==(after[i]?.amount??0))changes.push(i);const perm=block.permutation,raw=store.raw(k);try{for(const i of changes)container.setItem(i,after[i]);block.setType('minecraft:air');store.remove(k,state.revision);}catch(e){try{for(const i of changes)container.setItem(i,before[i]);block.setPermutation(perm);store.restore(k,raw);}catch{}throw e;}for(const e of nearbyHelpers(block))if(e.getDynamicProperty(HELPER_ANCHOR)===k)try{e.remove();}catch{}storageDiagnostics.recovered++;return true;});}
export function tickStorage(block){try{updateCabinetShape(block);const state=store.load(key(block));if(state)syncStorageVisuals(block,state);}catch(e){log(e);}}
export function registerStorageComponents({blockComponentRegistry:r}){r.registerCustomComponent(NS+':decor_storage',{beforeOnPlayerPlace:e=>{try{check(store.raw(storageKey(e.block.dimension.id,e.block.location))===undefined,'STORAGE_CONFLICT');}catch{x=>x;e.cancel=true;}},onPlace:e=>{try{initializeStorage(e.block);}catch(x){log(x);}},onTick:e=>tickStorage(e.block)});}
export function installStorageEvents(openBook){world.beforeEvents.playerInteractWithBlock.subscribe(e=>{if(e.cancel)return;const kind=storageBlockKind(e.block.typeId),hs=handSnapshot(e.player),heldKind=storageItemKind(hs.id);if(!kind&&!heldKind)return;e.cancel=true;if(e.isFirstEvent===false)return;const d=e.block.dimension,p={...e.block.location},id=e.block.typeId,face=e.blockFace,target=kind?p:plus(p,faceOffset(face)),local=localFromEvent(e);system.run(()=>safe(e.player,()=>{sameHand(e.player,hs);const b=blockAt(d,p);check(b?.typeId===id,'BLOCK_CHANGED');if([NS+':guidebook',NS+':recipe_book'].includes(hs.id))return openBook(e.player,hs.id.endsWith(':recipe_book'));if(!kind){check(e.player.isSneaking,'SNEAK_TO_PLACE');return placeStorage(e.player,target,heldKind);}if(e.player.isSneaking&&!hs.id)return recoverStorage(e.player,b);return useStorage(e.player,b,local);}));});world.beforeEvents.playerBreakBlock.subscribe(e=>{if(e.cancel||!storageBlockKind(e.block.typeId))return;e.cancel=true;const d=e.block.dimension,p={...e.block.location},id=e.block.typeId;system.run(()=>safe(e.player,()=>{const b=blockAt(d,p);check(b?.typeId===id,'BLOCK_CHANGED');return recoverStorage(e.player,b);}));});world.beforeEvents.explosion.subscribe(e=>e.setImpactedBlocks(e.getImpactedBlocks().filter(b=>!storageBlockKind(b.typeId))));world.afterEvents.entityLoad?.subscribe(e=>{if(e.entity.hasTag?.('kaleidoscope_tavern:storage_visual'))system.run(()=>{try{const raw=e.entity.getDynamicProperty(HELPER_ANCHOR);if(!raw)return;const m=/^kt:decor_storage\/([^/]+)\/(-?\d+)_(-?\d+)_(-?\d+)$/.exec(raw);if(!m)return;const d=world.getDimension('minecraft:'+m[1]),b=blockAt(d,{x:+m[2],y:+m[3],z:+m[4]});if(!b||!storageBlockKind(b.typeId))e.entity.remove();}catch{}});});}
export const STORAGE_TEST={store,locks,chooseSlot,snapshotItem,restored};
