# Static inspection only: give items, no clearing or world construction.
give @s kt_assets_a9:brandy_1 1
give @s kt_assets_a9:brandy_2 1
give @s kt_assets_a9:brandy_3 1
give @s kt_assets_a9:carignan_1 1
give @s kt_assets_a9:carignan_2 1
give @s kt_assets_a9:carignan_3 1
give @s kt_assets_a9:madame_shexiang_1 1
give @s kt_assets_a9:madame_shexiang_2 1
give @s kt_assets_a9:madame_shexiang_3 1
give @s kt_assets_a9:madame_shexiang_4 1
give @s kt_assets_a9:mother_snow_1 1
give @s kt_assets_a9:mother_snow_2 1
give @s kt_assets_a9:mother_snow_3 1
give @s kt_assets_a9:mother_snow_4 1
give @s kt_assets_a9:plum_wine_1 1
give @s kt_assets_a9:plum_wine_2 1
give @s kt_assets_a9:plum_wine_3 1
give @s kt_assets_a9:plum_wine_4 1
