# A11 pose-lab helpers. Gives inspection items only; no world clearing.
give @s kt_assets_a2:trellis_single 1
give @s kt_assets_a2:trellis_east_west 1
give @s kt_assets_a2:trellis_north_south 1
give @s kt_assets_a2:trellis_cross_east_west 1
give @s kt_assets_a2:trellis_cross_north_south 1
give @s kt_assets_a2:trellis_cross_up_down 1
give @s kt_assets_a2:trellis_six_direction 1
give @s kt_assets_a4:sofa_white_single 1
give @s kt_assets_a4:sofa_orange_single 1
give @s kt_assets_a4:sofa_magenta_single 1
give @s kt_assets_a4:sofa_light_blue_single 1
give @s kt_assets_a4:sofa_yellow_single 1
give @s kt_assets_a4:sofa_lime_single 1
give @s kt_assets_a4:sofa_pink_single 1
give @s kt_assets_a4:sofa_gray_single 1
give @s kt_assets_a4:sofa_light_gray_single 1
give @s kt_assets_a4:sofa_cyan_single 1
give @s kt_assets_a4:sofa_purple_single 1
give @s kt_assets_a4:sofa_blue_single 1
give @s kt_assets_a4:sofa_brown_single 1
give @s kt_assets_a4:sofa_green_single 1
give @s kt_assets_a4:sofa_red_single 1
give @s kt_assets_a4:sofa_black_single 1
give @s kt_assets_a4:emerald 1
give @s kt_assets_a6:bar_cabinet_single 1
give @s kt_assets_a6:bar_cabinet_left 1
give @s kt_assets_a6:bar_cabinet_middle 1
give @s kt_assets_a6:bar_cabinet_right 1
give @s kt_assets_a6:glass_bar_cabinet_single 1
give @s kt_assets_a6:glass_bar_cabinet_left 1
give @s kt_assets_a6:glass_bar_cabinet_middle 1
give @s kt_assets_a6:glass_bar_cabinet_right 1
give @s kt_assets_a6:cellar_cabinet_single 1
give @s kt_assets_a6:cellar_cabinet_left 1
give @s kt_assets_a6:cellar_cabinet_middle 1
give @s kt_assets_a6:cellar_cabinet_right 1
give @s kt_assets_a6:tilted_rack 1
give @s kt_assets_a6:circular_rack 1
give @s kt_assets_a6:glassware_holder 1
give @s kt_assets_a7:empty_glassware 1
give @s kt_assets_a7:screwdriver 1
give @s kt_assets_a8:depth_charge 1
give @s kt_assets_a8:mojito 1
give @s kt_assets_a8:signature_cocktail 1
give @s kt_assets_a8:mystery_cocktail 1
give @s kt_assets_a9:white_lady 1
give @s kt_assets_a10:allium_garden 1
give @s kt_assets_a10:bloody_mary 1
give @s kt_assets_a10:brass_heart 1
give @s kt_assets_a10:godfather 1
give @s kt_assets_a10:grasshopper 1
give @s kt_assets_a10:nether_special 1
give @s kt_assets_a10:sculk_special 1
give @s kt_assets_a10:bar_counter_single 1
give @s kt_assets_a10:holder 1
