#!/usr/bin/env python3
"""Compile the reviewed ingredient catalogue into canonical render resources.

This is an explicit authoring step, never a packaging/runtime transformation.
Textures remain owned by the vanilla/family resource packs; no art is copied.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NS = 'kaleidoscope_tavern'

def outputs():
    catalog = json.loads((ROOT / 'data/barrel-materials.json').read_text())
    entries = catalog['materials']
    ids = [row['id'] for row in entries]
    assert len(ids) == len(set(ids)), 'Duplicate material IDs'
    assert all(row['model'] in ('card', 'cube') and row['texture'].startswith('textures/') for row in entries)
    kinds = {row['id']: i for i, row in enumerate(entries, 1)}
    result = {'runtime/BP/scripts/data/barrel-ingredient-visuals.js':
        '// Generated by tools/build_barrel_materials.py from data/barrel-materials.json.\n'
        'export const BARREL_INGREDIENT_KINDS=' + json.dumps(kinds, indent=2) + ';\n'}
    for slot in range(4):
        bp = f'runtime/BP/entities/barrel_ingredients_{slot}_visual.json'
        data = json.loads((ROOT / bp).read_text())
        data['minecraft:entity']['description']['properties'][NS + ':kind']['range'] = [1, len(entries)]
        result[bp] = json.dumps(data, indent=2) + '\n'
        rp = f'runtime/RP/entity/runtime_barrel_ingredients_{slot}.entity.json'
        data = json.loads((ROOT / rp).read_text())
        data['minecraft:client_entity']['description']['textures'] = {f'kind_{i}': row['texture'] for i, row in enumerate(entries, 1)}
        result[rp] = json.dumps(data, indent=2) + '\n'
    path = 'runtime/RP/render_controllers/runtime_barrel_ingredients.render_controllers.json'
    data = json.loads((ROOT / path).read_text())
    rc = data['render_controllers']['controller.render.kt_runtime.barrel_ingredients']
    rc['geometry'] = '(' + ' || '.join(f"q.property('{NS}:kind') == {i}" for i, row in enumerate(entries, 1) if row['model'] == 'cube') + ') ? Geometry.cube : Geometry.card'
    rc['arrays']['textures']['Array.kind'] = [f'Texture.kind_{i}' for i in range(1, len(entries) + 1)]
    result[path] = json.dumps(data, indent=2) + '\n'
    return result

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, text in outputs().items():
        path = ROOT / name
        if args.check:
            assert path.read_text() == text, 'Stale barrel material output: ' + name
        else:
            path.write_text(text)
    print('Barrel material resources ' + ('verified' if args.check else 'generated'))
