#!/usr/bin/env python3
"""C2 additions: cultivated grapes, bottle displays, native drink effects. Offline build."""
from pathlib import Path
import json,copy,hashlib
ROOT=Path(__file__).resolve().parents[1];BP=ROOT/'runtime/BP';RP=ROOT/'runtime/RP';ART=ROOT/'art';NS='kaleidoscope_tavern'
def load(p):return json.loads(p.read_text(encoding='utf-8'))
def dump(p,d):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
def js(p,name,data):p.parent.mkdir(parents=True,exist_ok=True);p.write_text('// Generated by build_c2.py from recorded source data.\nexport const '+name+' = '+json.dumps(data,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
SHAPES=['single','east_west','north_south','cross_east_west','cross_north_south','cross_up_down','six_direction']
KINDS=['grape','ice_grape','gold_grape']
NATIVE=['nausea','fire_resistance','resistance','haste','regeneration','strength','bad_omen','instant_health','night_vision','water_breathing','blindness','mining_fatigue','speed','jump_boost']
def main():
 lock=load(ROOT/'data/upstream/c2/source.lock.json')
 for row in lock['records']:assert hashlib.sha256((ROOT/row['path']).read_bytes()).hexdigest()==row['sha256']
 registry=load(ART/'interfaces/asset-registry.json');vis={x['key']:x for x in registry['visuals']}
 def visual(k,with_item=False):
  v=vis[k]['binding'];c={'minecraft:geometry':copy.deepcopy(v['geometry']),'minecraft:material_instances':copy.deepcopy(v['materials'])}
  if with_item:c['minecraft:item_visual']=copy.deepcopy(v.get('item_visual',{'geometry':v['geometry'],'material_instances':v['materials']}))
  return c
 def common(c):
  return {**c,'minecraft:destructible_by_mining':{'seconds_to_destroy':.6},'minecraft:destructible_by_explosion':{'explosion_resistance':3600000},'minecraft:movable':{'movement_type':'immovable'},'minecraft:loot':'loot_tables/empty.json','minecraft:light_dampening':0}
 def block(n,c,states,perms,menu=False,traits=None):
  d={'identifier':NS+':'+n,'states':states}
  if menu:d['menu_category']={'category':'construction'}
  if traits:d['traits']=traits
  dump(BP/'blocks'/f'{n}.json',{'format_version':'1.26.50','minecraft:block':{'description':d,'components':common(c),'permutations':perms}})
 def shape_box(s):
  # Three-axis unions need multiple engine collision boxes; this version uses an explicit bounding box.
  return {'origin':[-2,0,-2],'size':[4,16,4]} if s=='single' else {'origin':[-8,6,-2],'size':[16,4,4]} if s=='east_west' else {'origin':[-2,6,-8],'size':[4,4,16]} if s=='north_south' else {'origin':[-8,0,-8],'size':[16,16,16]}
 cond=lambda k,v:f"q.block_state('{NS}:{k}') == "+(json.dumps(v) if isinstance(v,str) else str(v))
 for kind in ['bare']+KINDS:
  name='trellis'if kind=='bare'else kind+'vine_trellis'
  default='trellis_single'if kind=='bare'else kind+'vine_stage0'
  c=visual(default,True);c.update({NS+':trellis':{},'minecraft:tick':{'interval_range':[40,40],'looping':True},'minecraft:collision_box':shape_box('single'),'minecraft:selection_box':{'origin':[-4,0,-4],'size':[8,16,8]}})
  states={NS+':shape':SHAPES}
  if kind=='bare':states[NS+':waxed']=[False,True]
  else:states[NS+':age']=[0,1,2,3]
  perms=[]
  for s in SHAPES:
   for age in ([None]if kind=='bare'else range(4)):
    vk='trellis_'+s if kind=='bare' else kind+'vine_'+('stage'+str(age) if s=='single'else s)
    rule=cond('shape',s)+((' && '+cond('age',age))if age is not None else '')
    pc=visual(vk);pc.update({'minecraft:collision_box':shape_box(s),'minecraft:selection_box':True})
    perms.append({'condition':rule,'components':pc})
  block(name,c,states,perms,kind=='bare',{'minecraft:placement_position':{'enabled_states':['minecraft:block_face']}})
  if kind!='bare':
   name=kind+'_crop';c=visual(kind+'_crop_stage0',True);c.update({NS+':grape_crop':{},'minecraft:tick':{'interval_range':[40,40],'looping':True},'minecraft:collision_box':False,'minecraft:selection_box':{'origin':[-6,6,-6],'size':[12,10,12]}})
   block(name,c,{NS+':age':list(range(6))},[{'condition':cond('age',age),'components':visual(kind+'_crop_stage'+str(age))}for age in range(6)])
 # Full crop/item visuals are from A17; bootstrap crafting is explicitly a port-only recipe.
 icons=load(RP/'textures/item_texture.json');icons['texture_data']['kt_c2_grapevine']={'textures':'textures/kaleidoscope_tavern_jar/item/grapevine'}
 dump(RP/'textures/item_texture.json',icons)
 dump(BP/'items/grapevine.json',{'format_version':'1.26.50','minecraft:item':{'description':{'identifier':NS+':grapevine','menu_category':{'category':'items'}},'components':{'minecraft:icon':'kt_c2_grapevine','minecraft:display_name':{'value':'item.'+NS+':grapevine.name'},'minecraft:max_stack_size':64}}})
 for kind in KINDS+['green_grape']:
  p=BP/'items'/f'{kind}.json';d=load(p);d['minecraft:item']['components'].update({'minecraft:food':{'nutrition':2,'saturation_modifier':.5,'can_always_eat':True},'minecraft:use_animation':'eat','minecraft:use_modifiers':{'use_duration':1.6,'movement_modifier':.35}});dump(p,d)
 trellis=load(ROOT/'data/upstream/recipes/trellis.json')
 dump(BP/'recipes/trellis.json',{'format_version':'1.20.10','minecraft:recipe_shaped':{'description':{'identifier':NS+':trellis'},'tags':['crafting_table'],'pattern':trellis['pattern'],'key':{k:{'item':x['item']}for k,x in trellis['key'].items()},'result':{'item':trellis['result']['id'],'count':trellis['result']['count']}}})
 dump(BP/'recipes/grapevine_starter.json',{'format_version':'1.20.10','minecraft:recipe_shapeless':{'description':{'identifier':NS+':grapevine_starter'},'tags':['crafting_table'],'ingredients':[{'item':'minecraft:vine'},{'item':'minecraft:sweet_berries'}],'result':{'item':NS+':grapevine','count':1}}})
 bases=sorted({p.stem[:-3]for p in(BP/'items').glob('*_q1.json')})
 bottles={}
 for base in bases:
  keys=[base+'_'+str(i) for i in range(1,5) if base+'_'+str(i) in vis];assert keys and len(keys)>=3,base
  bottles[base]={'maxCount':len(keys),'source':'assets/kaleidoscope_tavern/models/block/brew/drink/'+base,'qualities':6}
  c=visual(keys[0],True);c.update({NS+':bottle_display':{},'minecraft:collision_box':False,'minecraft:selection_box':{'origin':[-7,0,-7],'size':[14,16,14]}})
  perms=[{'condition':cond('count',i),'components':visual(k)}for i,k in enumerate(keys,1)]
  perms += [{'condition':cond('facing',i),'components':{'minecraft:transformation':{'rotation':[0,-90*i,0]}}}for i in range(4)]
  block('bottle_'+base,c,{NS+':count':list(range(1,len(keys)+1)),NS+':facing':list(range(4))},perms)
  for q in range(1,7):
   p=BP/'items'/f'{base}_q{q}.json';d=load(p);components=d['minecraft:item']['components'];components.pop('minecraft:food',None);components.update({NS+':drink_effects':{},'minecraft:use_animation':'drink','minecraft:use_modifiers':{'use_duration':1.6,'movement_modifier':.35,'start_using':'if_first'}});dump(p,d)
 empty={'minecraft:geometry':{'identifier':'geometry.kt_assets_a3.empty_bottle_faces'},'minecraft:material_instances':{'*':{'texture':'kt_assets_a3_empty_bottle_faces','render_method':'alpha_test','ambient_occlusion':0.0,'face_dimming':True}},'minecraft:collision_box':{'origin':[-3,0,-3],'size':[6,14,6]},'minecraft:selection_box':{'origin':[-3,0,-3],'size':[6,14,6]},'minecraft:liquid_detection':{'detection_rules':[{'liquid_type':'water','can_contain_liquid':True,'on_liquid_touches':'blocking','use_liquid_clipping':True}]}}
 empty_perms=[{'condition':f"q.block_state('minecraft:cardinal_direction') == '{direction}'",'components':{'minecraft:transformation':{'rotation':[0,rotation,0]}}}for direction,rotation in [('north',0),('east',-90),('south',-180),('west',-270)]]
 block('bottle_empty',empty,{},empty_perms,False,{'minecraft:placement_direction':{'enabled_states':['minecraft:cardinal_direction'],'y_rotation_offset':180.0}})
 p=BP/'blocks/bottle_empty.json';d=load(p);d['minecraft:block']['description'].pop('states',None);dump(p,d)
 simple_water={'minecraft:geometry':{'identifier':'geometry.kt_assets_a17.water_bottle'},'minecraft:material_instances':{'*':{'texture':'kt_assets_a17_water_bottle','render_method':'alpha_test','ambient_occlusion':0.0,'face_dimming':True}},'minecraft:collision_box':{'origin':[-3,0,-3],'size':[6,10,6]},'minecraft:selection_box':{'origin':[-3,0,-3],'size':[6,10,6]},'minecraft:liquid_detection':{'detection_rules':[{'liquid_type':'water','can_contain_liquid':True,'on_liquid_touches':'blocking','use_liquid_clipping':True}]}}
 simple_perms=[{'condition':f"q.block_state('minecraft:cardinal_direction') == '{direction}'",'components':{'minecraft:transformation':{'rotation':[0,rotation,0]}}}for direction,rotation in [('north',0),('east',-90),('south',-180),('west',-270)]]
 block('bottle_water',simple_water,{},simple_perms,False,{'minecraft:placement_direction':{'enabled_states':['minecraft:cardinal_direction'],'y_rotation_offset':180.0}})
 p=BP/'blocks/bottle_water.json';d=load(p);d['minecraft:block']['description'].pop('states',None);dump(p,d)
 js(BP/'scripts/data/bottles.js','BOTTLES',bottles)
 effects={base:load(ROOT/f'data/upstream/c2/data/{NS}/datamap/drink_effect/{base}.json')['effects'] for base in bases}
 js(BP/'scripts/data/drink-effects.js','DRINK_EFFECTS',effects)
 # Visible effect support report: unsupported effects are never substituted silently.
 effect_types=sorted({e['effect']for rows in effects.values()for row in rows for e in row})
 report={'source_units':'seconds; timed effects converted to ticks x20; instant_health uses a one-tick native instant effect','quality_index':'q-1, including q1','native_effects':[e for e in effect_types if e.split(':',1)[0]=='minecraft'],'custom_unimplemented':[e for e in effect_types if e.split(':',1)[0]!='minecraft'],'families':{base:{'native_entries':sum(e['effect'].startswith('minecraft:')for row in rows for e in row),'unsupported_custom_effects':sorted({e['effect']for row in rows for e in row if not e['effect'].startswith('minecraft:')})}for base,rows in effects.items()},'engine_acceptance':'NOT_RUN'}
 assert all(e[10:] in NATIVE for e in report['native_effects']);dump(ROOT/'docs/C2-EFFECT-COVERAGE.json',report)
 # Localized item/block names appended after the base language generator's marker.
 cn={'trellis':'葡萄藤架','grapevine':'葡萄藤','grape':'普通葡萄','ice_grape':'冰葡萄','gold_grape':'金葡萄'}
 for lc in ['zh_TW','zh_CN','en_US']:
  p=RP/f'texts/{lc}.lang';text=p.read_text().split('## C2 ADDITIONS')[0].rstrip()+'\n## C2 ADDITIONS\n'
  for kind in KINDS:
   title=kind.replace('_',' ').title()if lc=='en_US'else cn[kind]
   for suffix,role in [('vine_trellis','藤架'),('_crop','果實')]:text+=f'tile.{NS}:{kind}{suffix}.name='+title+(' '+suffix if lc=='en_US'else role)+'\n'
  text+=f'tile.{NS}:trellis.name='+('Trellis'if lc=='en_US'else'葡萄藤架')+'\n'
  for base in bases:text+=f'tile.{NS}:bottle_{base}.name='+base.replace('_',' ').title()+(' bottles'if lc=='en_US'else'・酒瓶陳列')+'\n'
  p.write_text(text,encoding='utf-8')
 # Generated book pages describe actual active code, plus explicit source differences.
 effect_names={'nausea':'噁心','regeneration':'生命恢復','speed':'速度','strength':'力量','resistance':'抗性','haste':'挖掘加速','mining_fatigue':'挖掘疲勞','night_vision':'夜視','water_breathing':'水下呼吸','fire_resistance':'抗火','blindness':'失明','instant_health':'瞬間治療','bad_omen':'不祥之兆','jump_boost':'跳躍提升'}
 def ep(base,lang):
  lines=['效果依每次飲用獨立抽選；秒×20轉為tick。'if lang!='en_US'else'Each entry rolls independently on consume. Seconds are converted to ticks.']
  for q,row in enumerate(effects[base],1):
   entries=[]
   for e in row:
    name=e['effect'].split(':')[1];implemented=name in NATIVE and e['effect'].startswith('minecraft:')
    label=effect_names.get(name,e['effect'])if lang!='en_US'else e['effect']
    entries.append(f"{label} Lv{e['amplifier']+1}, {e['duration']}s, {e['probability']*100:g}%"+(''if implemented else (' [待移植]'if lang!='en_US'else' [not implemented]')))
   lines.append('Q'+str(q)+': '+('; '.join(entries)or'—'))
  return '\n'.join(lines)
 pages=[]
 names_source=(BP/'scripts/data/names.js').read_text();names=json.loads(names_source.split(' = ',1)[1].rsplit(';',1)[0])
 for base in bases:
  pages.append({'id':NS+':effects/'+base,'source':NS,'title':{lc:('Effects: 'if lc=='en_US'else'酒效：')+names[lc].get(NS+':'+base,base)for lc in ['zh_TW','zh_CN','en_US']},'body':{lc:ep(base,lc)for lc in ['zh_TW','zh_CN','en_US']},'recipeIds':[]if base=='vinegar'else[NS+':barrel/'+base]})
 js(BP/'scripts/data/effect-pages.js','EFFECT_PAGES',pages)
 (BP/'functions/kt_c2_kit.mcfunction').write_text('\n'.join(['# Gives only; never clears world. Leave inventory space.','function kt_c1_kit',f'give @s {NS}:grapevine 6',f'give @s {NS}:trellis 24','give @s minecraft:bone_meal 64','give @s minecraft:shears 1',f'give @s {NS}:wine_q1 1',f'give @s {NS}:wine_q3 4',f'give @s {NS}:wine_q6 4'])+'\n')
 for p in [BP/'manifest.json',RP/'manifest.json']:
  d=load(p);d['header']['version']=[0,2,0];d['header']['name']=d['header']['name'].replace('C1','C2')
  for m in d['modules']:m['version']=[0,2,0]
  for dep in d.get('dependencies',[]):
   if dep.get('uuid')==load(RP/'manifest.json')['header']['uuid']:dep['version']=[0,2,0]
  dump(p,d)
 p=ROOT/'examples/Tavern-Extension-Demo/BP/manifest.json';d=load(p)
 for dep in d['dependencies']:
  if dep.get('uuid')==load(BP/'manifest.json')['header']['uuid']:dep['version']=[0,2,0]
 d['header']['version']=[0,2,0]
 for m in d['modules']:m['version']=[0,2,0]
 dump(p,d)
 config=load(ROOT/'config.json');config['name']='Kaleidoscope Tavern C2';dump(ROOT/'config.json',config)
 build=load(ROOT/'docs/C1-BUILD.json');build.update({'version':[0,2,0],'phase':'C2','crop_blocks':7,'display_blocks':len(bottles),'display_arrangements':sum(b['maxCount']for b in bottles.values()),'native_crafting_recipes':6,'source_effect_families':len(effects),'q1_drinkable':True,'soil_temperature_acceleration':'NOT_ADAPTED; natural fallback probability 0.25','worldgen':'NOT_ADAPTED; explicit port-only starter crafting','native_effect_types':len(report['native_effects']),'custom_effect_types_pending':len(report['custom_unimplemented'])});dump(ROOT/'docs/C2-BUILD.json',build)
 for x in build['planned_recipe_exclusions']:x['reason']=x['reason'].replace('C1','C2')
 dump(ROOT/'docs/C2-BUILD.json',build)
 print('C2 build:',len(bottles),'bottle families,',sum(b['maxCount']for b in bottles.values()),'arrangements, 7 farming blocks.')
if __name__=='__main__':main()
