#!/usr/bin/env python3
"""Bake exact Java ChatFormatting mixtures; no runtime shader color-mask dependency.

The glass and liquid remain separate passes. Every RGBA texel, including alpha,
comes from the upstream texture. A single atlas holds six frames per mixture.
Run after changing the source signature texture. Requires Pillow.
"""
import itertools
import json
from pathlib import Path
from PIL import Image, ImageChops

ROOT = Path(__file__).resolve().parents[1]
RP = ROOT / 'runtime/RP'
BP = ROOT / 'runtime/BP'
COLORS = [0x000000, 0x0000aa, 0x00aa00, 0x00aaaa, 0xaa0000, 0xaa00aa,
          0xffaa00, 0xaaaaaa, 0x555555, 0x5555ff, 0x55ff55, 0x55ffff,
          0xff5555, 0xff55ff, 0xffff55, 0xffffff]
palette = sorted({sum((sum(c >> s & 255 for c in row) // len(row)) << s
                      for s in (16, 8, 0))
                  for n in (1, 2, 3)
                  for row in itertools.combinations_with_replacement(COLORS, n)})

def read(p):
    return json.loads(p.read_text())

def write(p, value):
    p.write_text(json.dumps(value, ensure_ascii=False, indent=2) + '\n')

source = Image.open(RP / 'textures/kaleidoscope_tavern_jar/block/mixology/signature_cocktail.png').convert('RGBA')
assert source.size == (32, 192)
cols = 48
rows = (len(palette) * 6 + cols - 1) // cols
tile = 34  # 32 source pixels plus a replicated one-pixel sampling gutter.
atlas = Image.new('RGBA', (cols * tile, rows * tile))
for index, color in enumerate(palette):
    rgb = tuple(color >> shift & 255 for shift in (16, 8, 0))
    strip = ImageChops.multiply(source, Image.new('RGBA', source.size, (*rgb, 255)))
    for frame in range(6):
        image = strip.crop((0, frame * 32, 32, (frame + 1) * 32))
        x, y = ((index * 6 + frame) % cols) * tile, ((index * 6 + frame) // cols) * tile
        # Include edge and corner texels in the gutter to avoid adjacent-color bleed.
        for dy in range(tile):
            for dx in range(tile):
                atlas.putpixel((x + dx, y + dy), image.getpixel((min(31, max(0, dx - 1)), min(31, max(0, dy - 1)))))
atlas.save(RP / 'textures/kt_runtime/signature/mixtures.png')
(RP / 'materials').mkdir(exist_ok=True)
write(RP / 'materials/kt_signature.material', {'materials': {
    'version': '1.0.0', 'kt_signature_animated:entity_alphatest_one_sided': {'+defines': ['USE_UV_ANIM']}}})

(BP / 'scripts/data/signature-palette.js').write_text(
    '// Generated by tools/build_signature_palette.py. Exact Java mixtures of 1–3 colors.\n'
    + 'const PALETTE=' + json.dumps(palette) + ';\n'
    + 'const INDICES=new Map(PALETTE.map((color,index)=>[color,index]));\n'
    + 'export function signaturePaletteIndex(color){return INDICES.get(color)??-1;}\n')

for name in ('runtime_signature_cup', 'rig_signature_color'):
    p = RP / f'entity/{name}.entity.json'
    j = read(p)
    d = j['minecraft:client_entity']['description']
    # One-sided alpha test keeps alpha=0 glass holes and culls opposite faces.
    d['materials']['liquid'] = 'kt_signature_animated'
    d['textures'] = {f'frame_{i}': f'textures/kt_runtime/signature/frame_{i}' for i in range(6)}
    d['textures']['mixtures'] = 'textures/kt_runtime/signature/mixtures'
    write(p, j)

p = RP / 'render_controllers/signature_tint.json'
j = read(p)
c = j['render_controllers']['controller.render.kt_assets_a17.signature_tint']
c.pop('color', None)
c.pop('arrays', None)
c['textures'] = ['Texture.mixtures']
index = "(math.max(0, query.property('kt_art:palette')) * 6 + math.mod(math.floor(q.life_time * 10), 6))"
c['uv_anim'] = {'scale': [32 / atlas.width, 32 / atlas.height], 'offset': [
    f'(math.mod({index}, {cols}) * {tile} + 1) / {atlas.width}',
    f'(math.floor({index} / {cols}) * {tile} + 1) / {atlas.height}']}
# Third-party inputs may use arbitrary RGB values outside Java's tag palette.
# Preserve their actual RGB rather than silently choosing the nearest color.
# Native overlay is only the fallback; all Java mixtures retain texture shading.
c['overlay_color'] = {channel: f"query.property('kt_art:{name}') / 255"
                      for channel, name in [('r', 'red'), ('g', 'green'), ('b', 'blue')]}
c['overlay_color']['a'] = "query.property('kt_art:palette') < 0 ? 1 : 0"
write(p, j)
p = BP / 'entities/signature_cup_visual.json'
j = read(p)
j['minecraft:entity']['description']['properties']['kt_art:palette'] = {
    'type': 'int', 'range': [-1, len(palette) - 1], 'default': palette.index(0x5555ff), 'client_sync': True}
for event in j['minecraft:entity']['events'].values():
    props = event['set_property']
    rgb = sum(props[f'kt_art:{channel}'] << shift for channel, shift in [('red', 16), ('green', 8), ('blue', 0)])
    props['kt_art:palette'] = palette.index(rgb) if rgb in palette else -1
write(p, j)
print(f'Generated {len(palette)} exact Java RGB mixtures, six frames each.')
