#!/usr/bin/env python3
"""Build each guide icon from its own Java sprite or packaged item geometry.
Requires Pillow and NumPy for art regeneration; no game/player simulation.
"""
import json,re,importlib.util,subprocess
from pathlib import Path
from PIL import Image
ROOT=Path(__file__).resolve().parents[1];RP=ROOT/'runtime/RP';BP=ROOT/'runtime/BP'
spec=importlib.util.spec_from_file_location('art',ROOT/'art/tools/render_preview.py');art=importlib.util.module_from_spec(spec);spec.loader.exec_module(art)
terrain=json.loads((RP/'textures/terrain_texture.json').read_text())['texture_data'];itemtex=json.loads((RP/'textures/item_texture.json').read_text())['texture_data']
geos={g['description']['identifier']:g for p in (RP/'models').rglob('*.json') for g in json.loads(p.read_text()).get('minecraft:geometry',[])}
blocks={j['description']['identifier']:j for p in (BP/'blocks').glob('*.json') for j in [json.loads(p.read_text())['minecraft:block']]}
items={j['description']['identifier']:j for p in (BP/'items').glob('*.json') for j in [json.loads(p.read_text())['minecraft:item']]}
code="import {buildCookeryGuidePayload as b} from './runtime/BP/scripts/data/cookery-guide-payload.js';import {BUILTIN_RECIPES as r} from './runtime/BP/scripts/data/recipes.js';console.log(JSON.stringify(b({list:()=>[],allPages:()=>[],allRecipes:()=>r.map(x=>({...x,source:'kaleidoscope_tavern'}))})));"
payload=json.loads(subprocess.check_output(['node','--input-type=module','-e',code],cwd=ROOT,text=True))
def texpath(row):
 v=row['textures'];return v[0] if isinstance(v,list) else v
icons={};provenance={};out=RP/'textures/ui/tavern_entries';out.mkdir(parents=True,exist_ok=True)
for entry in payload['entries']:
 id=entry['id'];short=id.split(':')[1];base=re.sub('_q[1-6]$','',short.split('/')[-1]);slug=short.replace('/','__')
 sprite={'guide_grapes':'grapevine','guide_bottle_display':'empty_bottle','guide_quality_effects':'wine'}.get(base,base)
 source=RP/f'textures/kaleidoscope_tavern_jar/item/{sprite}.png'
 if source.exists():
  im=Image.open(source).convert('RGBA');im=im.crop((0,0,im.width,im.width));how={'sprite':str(source.relative_to(RP))}
 else:
  block=blocks.get(id) or blocks.get('kaleidoscope_tavern:stool_'+base.removesuffix('_bar_stool')) or blocks.get('kaleidoscope_tavern:light_'+base.removeprefix('string_lights_'))
  components=block.get('components',{}) if block else {};visual=components.get('minecraft:item_visual',components);g=visual.get('geometry') or visual.get('minecraft:geometry');g=g.get('identifier') if isinstance(g,dict) else g
  mat=visual.get('material_instances',visual.get('minecraft:material_instances',{})).get('*',{});texture=mat.get('texture')
  if g and g in geos and texture in terrain:
   geo=geos[g];atlas=texpath(terrain[texture]);tex=Image.open(RP/(atlas+'.png')).convert('RGBA')
   # The packaged geometry carries Java GUI transforms; render that view when supplied.
   faces=art.all_faces(art.decode_geo({'minecraft:geometry':[geo]}));gui=geo.get('item_display_transforms',{}).get('gui');yaw,pitch=35,25
   if gui and 'rotation' in gui:
    import numpy as np
    x,y,z=gui['rotation'];rotation=art.rot([x,0,0])@art.rot([0,y,0])@art.rot([0,0,z]);faces=[(pts@rotation.T,uv) for pts,uv in faces];yaw,pitch=180,0
   im=art.raster(faces,tex,size=128,yaw=yaw,pitch=pitch,cull=True);how={'geometry':g,'texture':atlas}
  else:
   item=items.get(id);key=item.get('components',{}).get('minecraft:icon') if item else None
   if isinstance(key,dict):key=key.get('textures',{}).get('default')
   assert key in itemtex,(id,'no exact item icon/geometry')
   path=texpath(itemtex[key]);im=Image.open(RP/(path+'.png')).convert('RGBA');how={'itemIcon':key,'texture':path}
 box=im.getbbox();assert box,(id,'empty icon');im=im.crop(box);scale=60/max(im.size);im=im.resize((max(1,round(im.width*scale)),max(1,round(im.height*scale))),Image.Resampling.NEAREST);canvas=Image.new('RGBA',(64,64));canvas.alpha_composite(im,((64-im.width)//2,(64-im.height)//2));canvas.save(out/(slug+'.png'),optimize=True)
 icons[id]='textures/ui/tavern_entries/'+slug;provenance[id]=how
(ROOT/'runtime/BP/scripts/data/guide-icons.js').write_text('// Exact per-entry sprites; generated by tools/build_guide_icons.py.\nexport const GUIDE_ENTRY_ICONS='+json.dumps(icons,ensure_ascii=False,indent=2)+';\n')
(ROOT/'data/guide-icon-sources.json').write_text(json.dumps(provenance,ensure_ascii=False,indent=2)+'\n')
print('Built',len(icons),'exact entry icons.')
