# A2 visual fixtures only
give @s kt_assets_a2:grape_crop_stage0 1
give @s kt_assets_a2:grape_crop_stage1 1
give @s kt_assets_a2:grape_crop_stage2 1
give @s kt_assets_a2:grape_crop_stage3 1
give @s kt_assets_a2:grape_crop_stage4 1
give @s kt_assets_a2:grape_crop_stage5 1
give @s kt_assets_a2:ice_grape_crop_stage0 1
give @s kt_assets_a2:ice_grape_crop_stage1 1
give @s kt_assets_a2:ice_grape_crop_stage2 1
give @s kt_assets_a2:ice_grape_crop_stage3 1
give @s kt_assets_a2:ice_grape_crop_stage4 1
give @s kt_assets_a2:ice_grape_crop_stage5 1
give @s kt_assets_a2:gold_grape_crop_stage0 1
give @s kt_assets_a2:gold_grape_crop_stage1 1
give @s kt_assets_a2:gold_grape_crop_stage2 1
give @s kt_assets_a2:gold_grape_crop_stage3 1
give @s kt_assets_a2:gold_grape_crop_stage4 1
give @s kt_assets_a2:gold_grape_crop_stage5 1
